This script is testing changes to the BBN model for small deer impact risk following phase 2 model validation interviews

```{r}
library(sf)
library(tidyverse)
library(raster)
library(igraph)
```

```{r}
#Read in NFI 2023 dataset

nfi <- st_read("C:/Users/ik929086/Documents/iDeer/data/raw-data/nfi-2023-raw/National_Forest_Inventory_GB_2023.shp")

unique(nfi$IFT_IOA)

#England and Wales 10k squares
ew10k <- sf::st_read("C:/Users/ik929086/Documents/iDeer/data/derived-data/10k_tiles_EW.shp")
bng <- st_crs(ew10k)

#Get Chilterns tile as an example
#SU79 <- ew10k %>% filter(tile_name %in% c("SU79"))

#Get first five 10k tiles as an example
tiles <- ew10k %>% filter(tile_name %in% c("SU79","SU78","SU88","SU89"))
#plot(tiles$geometry)

```

```{r}
#Explore dataset

woods_only <- nfi %>% filter(CATEGORY %in% c("Woodland"))
unique(woods_only$IFT_IOA)

non_woods <- nfi %>% filter(CATEGORY %in% c("Non woodland"))
unique(non_woods$IFT_IOA)
#Grassland, Agricultural land, Other vegetation and bare area would be areas for foraging
#Other things not usable habitat

#Mixed structure habitats = open areas, or areas with good potential for foraging resources
mixed_structure_habitats <- nfi %>% filter(IFT_IOA %in% c("Bare area","Assumed woodland","Failed","Coppice","Coppice with standards","Windblow","Grassland","Ground prep","Agriculture land","Other vegetation","Felled","Low density", "Young trees","Shrub"))

#Closed habitats = mature woodland
closed_habitats <- nfi %>% filter(IFT_IOA %in% c("Conifer","Broadleaved","Mixed mainly broadleaved","Mixed mainly conifer"))

#subset for testing

closed_habitats <- st_filter(closed_habitats, tiles)
mixed_structure_habitats <- st_filter(mixed_structure_habitats, tiles)

plot(closed_habitats$geometry, col = "red")
plot(mixed_structure_habitats$geometry, col = "blue",add=TRUE)
```

```{r}
#Make an NFI raster of the two habitat types

# Create the IFT_ID column based on the IFT_IOA values
#1 = open land cover types
#2 = mature woodland types
nfi <- nfi %>%
  mutate(group_ID = case_when(
    IFT_IOA %in% c("Bare area", "Assumed woodland", "Failed", "Coppice", 
                   "Coppice with standards", "Windblow", "Grassland", 
                   "Ground prep", "Agriculture land", "Other vegetation", 
                   "Shrub", "Felled", "Low density", "Young trees") ~ 1,
    IFT_IOA %in% c("Conifer", "Broadleaved", "Mixed mainly broadleaved", 
                   "Mixed mainly conifer") ~ 2,
    TRUE ~ NA_real_  # This handles other values (if needed, or you can leave it out)
  ))

#Make raster of NFI
template_rast <- raster("C:/Users/ik929086/Documents/iDeer/data/raw-data/lcm-2023/gblcm2023_25m.tif")

nfi_rast <- fasterize::fasterize(nfi, template_rast, field = "group_ID")

plot(nfi_rast)

# #Get boundaries between 1 and 2
# boundaries_nfi <- boundaries(nfi_rast, type = "inner", classes = TRUE, #make edges between classes as well as NA
#                              directions = 8, #search for edges in 8 directions
#                              asNA = TRUE) #non-edges returned as NA
# plot(boundaries_nfi)
# writeRaster(boundaries_nfi, "C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023/boundaries_open_closed_woods_NFI_2023.tif")
boundaries_nfi <- raster("C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023/boundaries_open_closed_woods_NFI_2023.tif")

plot(boundaries_nfi)

boundaries_nfi_sample <- raster::crop(boundaries_nfi, tiles)

# Plot the other geometries
plot(closed_habitats$geometry, col = "forestgreen")
plot(mixed_structure_habitats$geometry, col = "magenta", add = TRUE)

#plot boundaries - internal boundaries and edge boundaries
plot(boundaries_nfi_sample)

```

```{r}
#Open woodland types will have a high risk of impact from small deer
#Closed woodland types will have a lower risk of impact

#Add a column woodland_vulnerability to woods_only with following conditions
#Where open habitats have highest

woods_only <- woods_only %>%
  mutate(woodland_food_value = case_when(
    IFT_IOA %in% c("Assumed woodland", "Failed", "Coppice", 
                   "Coppice with standards", "Windblow", 
                   "Ground prep", 
                   "Shrub", "Felled", "Low density", "Young trees") ~ 3,
    IFT_IOA %in% c("Broadleaved", "Mixed mainly broadleaved") ~ 2,
    IFT_IOA %in% c("Conifer","Mixed mainly conifer") ~ 1,
    TRUE ~ NA_real_  # This handles other values (if needed, or you can leave it out)
  ))

woodland_food_value_raster <- fasterize::fasterize(woods_only, template_rast,
                                                   field = "woodland_food_value")
#plot(woodland_food_value_raster)

woodland_food_value_raster_test <- crop(woodland_food_value_raster, tiles)
```

```{r}
#PERCENTAGE COVER WOODLAND EDGE
#Edges now include both external woodland edges and interior woodland edges produced in boundaries_nfi above

#create circular buffers around every pixel of 400 metres
circle.buff = raster::focalWeight (boundaries_nfi_sample, d=400, type="circle",fillNA=T )#Create buffer
circle.buff[circle.buff > 0] <- 1   # replacing weights by 1
Focal400_EDGES= raster::focal(boundaries_nfi_sample, w=circle.buff, fun=sum, na.rm=T,pad=TRUE, padValue=NA)

#plot(Focal400_EDGES)
crs(Focal400_EDGES) <- bng

#Divide number of pixels by the total number of 25m2 pixels in a 400m buffer*100
Focal400_EDGES_PERC <- (Focal400_EDGES/804)*100
plot(Focal400_EDGES_PERC)
plot(boundaries_nfi_sample,add=TRUE)
```

```{r}
#WOODLAND CONNECTIVITY

#Woodland cover within 2000m
#400m was too small

#subset for woodland types that offer cover

connectivity_woods <- woods_only %>% filter(IFT_IOA %in% c("Broadleaved","Mixed mainly broadleaved","Conifer","Mixed mainly conifer","Shrub","Coppice","Coppice with standards","Other vegetation","Low density","Young trees"))

#filter for testing

connectivity_woods_test <- st_filter(connectivity_woods, tiles)

#merged connectivity woods
# Step 1: Get touching relationships
touching <- st_touches(connectivity_woods_test)

# Step 2: Build graph and identify groups
g <- graph_from_adj_list(touching)
groups <- components(g)$membership

# Step 3: Add group ID to the data
connectivity_woods_test$group_ID <- groups

# Step 4: Dissolve (union) polygons by group
merged_connect_woods <- connectivity_woods_test %>%
  group_by(group_ID) %>%
  summarise(geometry = st_union(geometry), .groups = "drop")

plot(merged_connect_woods$geometry)

#Rasterize

connectivity_woods_raster <- fasterize::fasterize(connectivity_woods, template_rast)

#crop for testing

connectivity_woods_raster_test <- crop(connectivity_woods_raster, tiles)

#d = 2000m radius
circle.buff = raster::focalWeight(connectivity_woods_raster_test, d=2000, type="circle",fillNA=T)#Create buffer
circle.buff[circle.buff > 0] <- 1   # replacing weights by 1
Focal2000_WOOD= raster::focal(x=connectivity_woods_raster_test, w=circle.buff, fun=sum, na.rm=T, pad=TRUE, padValue=NA)

plot(Focal2000_WOOD)
crs(Focal2000_WOOD) <- bng

#Divide number of pixels by the total number of 25m2 pixels in a buffer*100 = percentage woodland
Focal2000_WOOD_PERC <- (Focal2000_WOOD/20106)*100
plot(Focal2000_WOOD_PERC)

#Get average woodland cover within 1000m for each merged woodland polygon
#Accounts for patch size, but also woods around each patch.
mean_wood_map_poly_vals  <- raster::extract(Focal2000_WOOD_PERC, merged_connect_woods, fun=mean, na.rm=TRUE, df=TRUE)

#left_join GB_merged_polys
mean_wood_map_poly_vals <- mean_wood_map_poly_vals %>% rename(group_ID = ID)

mean_wood_perc_polys <- left_join(merged_connect_woods, mean_wood_map_poly_vals, by = c("group_ID"))
mean_wood_perc_polys <- st_as_sf(mean_wood_perc_polys)

woods_area_2000m_tif <- fasterize::fasterize(sf = mean_wood_perc_polys, 
                                            raster = connectivity_woods_raster_test,
                                            field = "layer",
                                            fun = "sum",
                                            background = NA)
crs(woods_area_2000m_tif) <- bng
plot(woods_area_2000m_tif)

# writeRaster(woods_area_2000m_tif, "C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023/large_deer/mean_percentage_focal_area_woods_extracted_to_polys_2000m.tif",
#             overwrite=TRUE)
```

```{r}
#LINEAR FEATURE CONNECTIVITY

#Read in linear feature raster
#Created in ArcGIS
#Original dataset: CEH linear features (2016)
#The dataset has been rasterized, snapped to gblcm2023_25m.tif
#Then masked to the original GB LF vector dataset to remove weird background values
#Maintained full GB extent so as to not miss off hedgerows on the Scottish border
lf <- raster("C:/Users/ik929086/Documents/iDeer/data/derived-data/WLF_GB_raster_LCM_matched_masked.tif")
crs(lf) <- bng

#crop for testing

lf_test <- crop(lf, tiles)

#focal statistics, moving window
#Count pixels that contain linear features up to 400m away from each woodland pixel

#if na.rm = F, edges become cropped.

circle.buff = raster::focalWeight(lf_test, d=2000, type="circle",fillNA=T )#Create buffer
circle.buff[circle.buff > 0] <- 1   # replacing weights by 1
Focal2000_lf= raster::focal(x=lf_test, w=circle.buff, fun=sum, na.rm=T, pad=TRUE, padValue=NA)

plot(Focal2000_lf)

#Divide number of pixels by the total number of 25m2 pixels in a 400m buffer*100 = percentage lf
Focal2000_LF_PERC <- (Focal2000_lf/20106)*100
plot(Focal2000_LF_PERC)

#Get average woodland cover within 1000m for each merged woodland polygon
#Accounts for patch size, but also woods around each patch.
mean_lf_map_poly_vals  <- raster::extract(Focal2000_LF_PERC, merged_connect_woods, fun=mean, na.rm=TRUE, df=TRUE)

#left_join GB_merged_polys
mean_lf_map_poly_vals <- mean_lf_map_poly_vals %>% rename(group_ID = ID)

mean_lf_perc_polys <- left_join(merged_connect_woods, mean_lf_map_poly_vals, by = c("group_ID"))
mean_lf_perc_polys <- st_as_sf(mean_lf_perc_polys)

lf_area_2000m_tif <- fasterize::fasterize(sf = mean_lf_perc_polys, 
                                            raster = connectivity_woods_raster_test,
                                            field = "layer",
                                            fun = "sum",
                                            background = NA)
crs(lf_area_2000m_tif) <- bng
plot(lf_area_2000m_tif)
```

```{r}
#function to extract pixel values from raster layers
source("C:/Users/ik929086/Documents/iDeer/code/functions/extract_raster_pixels_func_10km_chunks.R")

```

```{r}
#Conditional probability tables:

#Connectivity
small_connectivity_cpt_df <- read.csv("C:/Users/ik929086/Documents/iDeer/output/CPTs/Small_Deer_Connectivity_Index_CPT_post_interviews.csv")

#Attraction index
small_attraction_cpt_df <- read.csv("C:/Users/ik929086/Documents/iDeer/data/CPTs/Smalldeer_Attraction_Index_Woodland_edge_cover_400m_Amy.csv")
#Thermoregulation
#small_thermoreg_cpt_df <- read.csv("C:/Users/ik929086/Documents/iDeer/data/CPTs/Smalldeer_Thermoregulation_Index_Max_Summed_DAMS_400m_Amy.csv")

#small deer damage risk
small_risk_cpt_df <- read.csv("C:/Users/ik929086/Documents/iDeer/output/CPTs/Small_Deer_Damage_Risk_CPT_post_interviews.csv")

#woodland food value index

small_wood_food_value_cpt_df <- read.csv("C:/Users/ik929086/Documents/iDeer/data/CPTs/Smalldeer_Woodland_food_value_Index.csv")
```

```{r}
#Create a dataframe containing all extracted raster values within user's landscape

template_rast_tiles <- crop(template_rast, tiles)

#EXTRACT LENGTH OF WOODLAND EDGE

edgepix <- extract_raster(map = Focal400_EDGES_PERC,
                          lcm = template_rast_tiles, #UK lcm
                         tiles = tiles) #ew10k

#saveRDS(edgepix, "C:/Users/ik929086/Documents/iDeer/output/edgepix_400m_df_EW.RDS")
#read
#edgepix <- readRDS("C:/Users/ik929086/Documents/iDeer/output/edgepix_400m_df_EW.RDS")

#EXTRACT WOODLAND FOOD QUALITY

foodpix <- extract_raster(map = woodland_food_value_raster_test,
                          lcm = template_rast_tiles,
                          tiles = tiles)

#EXTRACT CONNECTIVITY
woodpix <- extract_raster(map = Focal2000_WOOD_PERC,
                          lcm = template_rast_tiles,
                         tiles = tiles)
#saveRDS(woodpix, "C:/Users/ik929086/Documents/iDeer/output/woodpix_wood_area_400m_df_EW.RDS")
#read
#woodpix <- readRDS("C:/Users/ik929086/Documents/iDeer/output/woodpix_wood_area_400m_df_EW.RDS")

#EXTRACT LF DENSITY WITHIN 400M

LFpix <- extract_raster(map = Focal2000_LF_PERC,
                        lcm = template_rast_tiles,
                        tiles = tiles)

#saveRDS(LFpix, "C:/Users/ik929086/Documents/iDeer/output/LFpix_area_400m_df_EW.RDS")
#read
#LFpix <- readRDS("C:/Users/ik929086/Documents/iDeer/output/LFpix_area_400m_df_EW.RDS")

#left_join the datasets together #---------------

df <- left_join(edgepix, woodpix, by = c("x","y")) %>%
left_join(LFpix, by = c("x","y")) %>%
left_join(foodpix, by = c("x","y"))

#make any NAs zeros apart from the food value raster
#These rasters have the correct woodland pixels

df.no.nas <- df %>%
  mutate(across(c(Focal400_EDGES_PERC, Focal2000_LF_PERC, Focal2000_WOOD_PERC), 
                ~ tidyr::replace_na(., 0)))


#Remove the NAs

df.no.nas <- na.omit(df.no.nas)

df.no.nas.full <- df.no.nas

#save

#saveRDS(df.no.nas, "C:/Users/ik929086/Documents/iDeer/output/small_deer_full_df_no_nas.RDS")
#saveRDS(df.no.nas, "C:/Users/ik929086/Documents/iDeer/output/small_deer_full_df_no_nas_extractr.RDS")


#read
#df.no.nas <- readRDS("C:/Users/ik929086/Documents/iDeer/output/small_deer_full_df_no_nas.RDS")


# # #FOR TESTING: TAKE SUBSET
# df.no.nas.full <- df.no.nas
#  df.no.nas <- df.no.nas %>%
#     slice(1:100000) %>%
#     st_as_sf(coords = c("x","y"))
# # save test df
# #saveRDS(df.no.nas, "C:/Users/ik929086/Documents/iDeer/output/small_deer_full_df_no_nas_TEST.RDS")
# #read test df
# #df.no.nas <- readRDS("C:/Users/ik929086/Documents/iDeer/output/small_deer_full_df_no_nas_TEST.RDS")
```

```{r}
#Find optimal break points using quantiles

#k = number of breaks = 3
#USED WHOLE DATASET TO PRODUCE THESE BREAKS (UK)

#Edge density

edge_Tert = quantile(df.no.nas.full$Focal400_EDGES_PERC, c(0:3/3))
hist(df.no.nas.full$Focal400_EDGES_PERC)
abline(v = 20, col = "red")
abline(v = 35, col = "red")

#Linear features
LF_tert <- quantile(df.no.nas.full$Focal2000_LF_PERC, c(0:3/3))
hist(df.no.nas.full$Focal2000_LF_PERC)
abline(v = 3.5, col = "red")
abline(v = 5.5, col = "red")

#Summed DAMS
#MANUALLY ASSIGN TO ENSURE THEY ARE NOT TOO CLOSE TOGETHER
# dams_400m_tert <- quantile(df.no.nas.full$Focal400_MAX_SUMMED_DAMS, c(0:3/3))
# hist(df.no.nas.full$Focal400_MAX_SUMMED_DAMS)
# abline(v = 0.40, col = "red")
# abline(v = 0.55, col = "red")
# #USE 0.40 and 0.55

#Connectivity
connect_tert <- quantile(df.no.nas.full$Focal2000_WOOD_PERC, c(0:3/3))
hist(df.no.nas.full$Focal2000_WOOD_PERC)
abline(v = 20, col = "red")
abline(v = 40, col = "red")

#Woodland food value
#Low = 1
#Medium = 2
#High = 3

# #Alternative forage
# alt_forage_tert <- quantile(df.no.nas.full$Woodland_food_value, c(0:3/3))
# hist(df.no.nas.full$Woodland_food_value)
# abline(v = 30, col = "red")
# abline(v = 60, col = "red")

```

```{r}
#Reclassify continuous data into pre-specified Low,Medium,High categories
#Inspect terciles for each variable
#Categorise into LOW/MED/HIGH

df_cat <- df.no.nas.full

df_cat <- df_cat %>% rename(Woodland_food_value = woodland_food_value_raster_test)

#keep numeric columns ####

#Linear features
# Replace numeric values with cat labels
df_cat$Focal2000_LF_PERC <- ifelse(df_cat$Focal2000_LF_PERC<=3.5, "Low",
                ifelse(df_cat$Focal2000_LF_PERC> 3.5 & df_cat$Focal2000_LF_PERC <= 5.5, "Medium",
                       ifelse(df_cat$Focal2000_LF_PERC> 5.5, "High", NA)))

 #Woodland connectivity
df_cat$Focal2000_WOOD_PERC <- ifelse(
  df_cat$Focal2000_WOOD_PERC <= 20, "Low",
  ifelse(df_cat$Focal2000_WOOD_PERC > 20 & df_cat$Focal2000_WOOD_PERC <= 40, "Medium",
    ifelse(df_cat$Focal2000_WOOD_PERC > 40, "High", NA)))
  

#Edge density
df_cat$Focal400_EDGES_PERC <- ifelse(df_cat$Focal400_EDGES_PERC <= 20, "Low",
                                            ifelse(df_cat$Focal400_EDGES_PERC >20 & df_cat$Focal400_EDGES_PERC <=35, "Medium",
                                                   ifelse(df_cat$Focal400_EDGES_PERC > 35, "High", NA)))

# Woodland forage quality
df_cat$Woodland_food_value <- ifelse(df_cat$Woodland_food_value == 1, "Low",
           ifelse(df_cat$Woodland_food_value==2, "Medium",
           ifelse(df_cat$Woodland_food_value ==3 , "High", NA)))


df_cat$Focal2000_WOOD_PERC <- factor(df_cat$Focal2000_WOOD_PERC, levels= c("Low","Medium","High"))
df_cat$Focal2000_LF_PERC <- factor(df_cat$Focal2000_LF_PERC, levels = c("Low","Medium","High"))
df_cat$Focal400_EDGES_PERC <- factor(df_cat$Focal400_EDGES_PERC, levels = c("Low","Medium","High"))
df_cat$Woodland_food_value <- factor(df_cat$Woodland_food_value, levels = c("Low","Medium","High"))

unique(df_cat$Woodland_food_value)
unique(df_cat$Focal400_EDGES_PERC)
unique(df_cat$Focal2000_WOOD_PERC)
unique(df_cat$Focal2000_LF_PERC)
```

```{r}
#CPTS for measured nodes

#woodland edge area within 400m
edge_cpt <-matrix(c(0.333333,0.333333,0.333333),ncol = 3,dimnames = list(NULL, c("Low", "Medium","High")))
#woodland value
wood_value_cpt <- matrix(c(0.333333,0.333333,0.333333),ncol = 3,dimnames = list(NULL, c("Low", "Medium","High")))
#linear feature area within 2000m
lf_cpt <-matrix(c(0.333333,0.333333,0.333333),ncol = 3,dimnames = list(NULL, c("Low", "Medium","High")))
#woodland connectivity within 2000m
wood_connect_cpt <- matrix(c(0.333333,0.333333,0.333333),ncol = 3,dimnames = list(NULL, c("Low", "Medium","High")))

```

```{r}
#CPT for Connectivity Index ---------------#

small_connectivity_cpt_df <- small_connectivity_cpt_df %>%
  dplyr::select(-c("X","total_score"))

# Define the dimensions
connect_index_levels <- c("Low", "Medium", "High")
wood_connectivity_400m_levels <- unique(small_connectivity_cpt_df$Woodland_cover_400m)
summed_LF_400m_levels <- unique(small_connectivity_cpt_df$LF_cover_400m)

# Initialize the array with dimensions and names
connectivity_index_cpt <- array(
  NA,  # Placeholder value
  dim = c(length(connect_index_levels), 
          length(wood_connectivity_400m_levels), 
          length(summed_LF_400m_levels)),
  dimnames = list(
    connect_index = connect_index_levels,
    Woodland_cover_400m = wood_connectivity_400m_levels,
    LF_cover_400m = summed_LF_400m_levels)
)


# Populate the array with values from the DataFrame
for (i in 1:nrow(small_connectivity_cpt_df)) {
  # Get the indices for each dimension
  connect_idx <- which(dimnames(connectivity_index_cpt)$Woodland_cover_400m == small_connectivity_cpt_df$Woodland_cover_400m[i])
  lf_idx <- which(dimnames(connectivity_index_cpt)$LF_cover_400m == small_connectivity_cpt_df$LF_cover_400m[i])
  
  # Assign values for each connectivity index level
  connectivity_index_cpt["Low", connect_idx, lf_idx] <- small_connectivity_cpt_df$Low[i]
  connectivity_index_cpt["Medium", connect_idx, lf_idx] <- small_connectivity_cpt_df$Medium[i]
  connectivity_index_cpt["High", connect_idx, lf_idx] <- small_connectivity_cpt_df$High[i]
}
#connectivity_index_cpt <- connectivity_index_cpt / 100
connectivity_index_cpt
```

```{r}
#CPT for Attraction index ------------------------------------------------####
attraction_cpt_df <- small_attraction_cpt_df %>%
  dplyr::select(-c("X","Total"))

head(attraction_cpt_df)

# Define the dimensions
attraction_index_levels <- c("Low", "Medium","High")
wood_edge_area_levels <- unique(attraction_cpt_df$Woodland_edge_cover_400m)

# Initialize the array with dimensions and names
attraction_index_cpt <- array(
  NA,  # Placeholder value
  dim = c(length(attraction_index_levels), 
          length(wood_edge_area_levels)),
  dimnames = list(
    attraction_index = attraction_index_levels,
    Woodland_edge_cover_400m = wood_edge_area_levels
  )
)

# Populate the array with values from the DataFrame
for (i in 1:nrow(attraction_cpt_df)) {
  # Get the indices for each dimension
  edge_idx <- which(dimnames(attraction_index_cpt)$Woodland_edge_cover_400m == attraction_cpt_df$Woodland_edge_cover_400m[i])
  
  # Assign values for each forage pressure index level
  attraction_index_cpt["Low", edge_idx] <- attraction_cpt_df$Low[i]
  attraction_index_cpt["Medium", edge_idx] <- attraction_cpt_df$Medium[i]
  attraction_index_cpt["High",edge_idx] <- attraction_cpt_df$High[i]
}
#attraction_index_cpt <- attraction_index_cpt / 100
attraction_index_cpt 
```

```{r}
#CPT for woodland food value index ------------------------------------------------####
small_wood_food_value_cpt_df <- small_wood_food_value_cpt_df %>%
dplyr::select(-c("X","Total","Expertise","Confidence"))  

head(small_wood_food_value_cpt_df)

# Define the dimensions
wood_value_index_levels <- c("Low", "Medium","High")
wood_food_value_levels <- unique(small_wood_food_value_cpt_df$Woodland_food_value)

# Initialize the array with dimensions and names
wood_value_index_cpt <- array(
  NA,  # Placeholder value
  dim = c(length(wood_value_index_levels), 
          length(wood_food_value_levels)),
  dimnames = list(
    wood_value_index = wood_value_index_levels,
    Woodland_food_value =wood_food_value_levels
  )
)

# Populate the array with values from the DataFrame
for (i in 1:nrow(small_wood_food_value_cpt_df)) {
  # Get the indices for each dimension
  wood_val_idx <- which(dimnames(wood_value_index_cpt)$Woodland_food_value == small_wood_food_value_cpt_df$Woodland_food_value[i])
  
  # Assign values for each forage pressure index level
  wood_value_index_cpt["Low", wood_val_idx] <- small_wood_food_value_cpt_df$Low[i]
  wood_value_index_cpt["Medium", wood_val_idx] <- small_wood_food_value_cpt_df$Medium[i]
  wood_value_index_cpt["High",wood_val_idx] <- small_wood_food_value_cpt_df$High[i]
}
#wood_value_index_cpt <- wood_value_index_cpt / 100
wood_value_index_cpt 
```

```{r}
#Final CPT: deer damage risk -----------------------------------####

small_risk_cpt_df<- small_risk_cpt_df %>%
  dplyr::select(-c("X","total_score")) %>%
  dplyr::rename(attraction_index=Attraction_Index,
         connect_index=Connectivity_Index,
         wood_value_index=Woodland_Food_Value_Index)

# Replace '.' with '_' in column names
colnames(small_risk_cpt_df) <- gsub("\\..", "_", colnames(small_risk_cpt_df))

head(small_risk_cpt_df)

# Define the dimensions
small_risk_index_levels <- c("Low", "Low_Medium" ,"Medium", "Medium_High" , "High")
connectivity_index_levels <- unique(small_risk_cpt_df$connect_index)
attraction_index_levels <- unique(small_risk_cpt_df$attraction_index)
wood_value_index_levels <- unique(small_risk_cpt_df$wood_value_index)


# Initialize the array with dimensions and names
small_risk_index_cpt <- array(
  NA,  # Placeholder value
  dim = c(length(small_risk_index_levels), 
          length(connectivity_index_levels), 
          length(attraction_index_levels), 
          length(wood_value_index_levels )),
  dimnames = list(
    small_risk_index = small_risk_index_levels,
    connect_index = connectivity_index_levels,
    attraction_index = attraction_index_levels,
    wood_value_index = wood_value_index_levels
  )
)

# Populate the array with values from the DataFrame
for (i in 1:nrow(small_risk_cpt_df)) {
  # Get the indices for each dimension
  connect_idx <- match(small_risk_cpt_df$connect_index[i], dimnames(small_risk_index_cpt)$connect_index)
  fpi_idx <- match(small_risk_cpt_df$attraction_index[i], dimnames(small_risk_index_cpt)$attraction_index)
  wood_value_idx <- match(small_risk_cpt_df$wood_value_index[i], dimnames(small_risk_index_cpt)$wood_value_index)

  # Assign values
  small_risk_index_cpt["Low", connect_idx, fpi_idx, wood_value_idx] <- small_risk_cpt_df$Low[i]
  small_risk_index_cpt["Low_Medium", connect_idx, fpi_idx, wood_value_idx] <- small_risk_cpt_df$Low_Medium[i]
  small_risk_index_cpt["Medium", connect_idx, fpi_idx, wood_value_idx] <- small_risk_cpt_df$Medium[i]
  small_risk_index_cpt["Medium_High", connect_idx, fpi_idx, wood_value_idx] <- small_risk_cpt_df$Medium_High[i]
  small_risk_index_cpt["High", connect_idx, fpi_idx, wood_value_idx] <- small_risk_cpt_df$High[i]
}
#small_risk_index_cpt <- small_risk_index_cpt / 100
small_risk_index_cpt
```

```{r}
#Create BBN structure#------------------------------------

# Step 1: Explicitly define the nodes in the network
nodes <- c(
  "Woodland_cover_400m",
  "LF_cover_400m",
  "Woodland_edge_cover_400m",
  "Woodland_food_value",
  "attraction_index",
  "wood_value_index",
  "connect_index",
  "small_risk_index"
)

#empty graph
library(bnlearn)
e = empty.graph(nodes)

arc.set = matrix(c("Woodland_cover_400m", "connect_index",
                   "LF_cover_400m", "connect_index", 
                   "Woodland_edge_cover_400m","attraction_index",
                   "Woodland_food_value","wood_value_index",
                   "wood_value_index","small_risk_index",
                   "connect_index","small_risk_index",
                   "attraction_index","small_risk_index"),
                 ncol = 2, byrow = TRUE,
                 dimnames = list(NULL, c("from", "to")))

arcs(e) <- arc.set

model_string <- modelstring(e) 

net<-model2network(model_string) 
# You dont need to repeat the names of the nodes with parents (child nodes) 

# Custom fitting network (matching up the nodes to their CPTs)
dfit = custom.fit(net, dist = list(Woodland_cover_400m = wood_connect_cpt, 
                                   LF_cover_400m = lf_cpt,
                                   Woodland_food_value= wood_value_cpt,
                                   Woodland_edge_cover_400m = edge_cpt,
                                   connect_index = connectivity_index_cpt,
                                   wood_value_index = wood_value_index_cpt,
                                   attraction_index =attraction_index_cpt,
                                   small_risk_index=small_risk_index_cpt))

#Plot BN structure ####
graphviz.plot(net)

#Check parameters ####
dfit
```

```{r}
#Predict latent indices for BBN (wood_value Index, Connectivity Index and Foraging pressure index) ####--------------------------------

predict_dat <- df_cat %>% st_drop_geometry() #drop geometry
  #dplyr::select(-c("x","y"))

#Ensure variable names match those in BBN
predict_dat<-predict_dat%>%dplyr::rename(
  Woodland_edge_cover_400m=Focal400_EDGES_PERC,
  LF_cover_400m=Focal2000_LF_PERC,
  Woodland_food_value=Woodland_food_value,
  Woodland_cover_400m=Focal2000_WOOD_PERC)

#Make empty columns for the latent (unobserved) variables

predict_dat$attraction_index <- NA
predict_dat$connect_index <- NA
predict_dat$wood_value_index <- NA
predict_dat$small_risk <- NA

#Ensure all columns are factors, not characters
predict_dat <- predict_dat %>% mutate_all(as.factor)

#Ensure factor levels are in correct order
levels(predict_dat$Woodland_cover_400m)<-c("Low", "Medium", "High")
levels(predict_dat$Woodland_food_value)<-c("Low", "Medium","High")
levels(predict_dat$LF_cover_400m)<-c("Low", "Medium", "High")
levels(predict_dat$Woodland_edge_cover_400m)<-c("Low", "Medium", "High")
levels(predict_dat$attraction_index)<-c("Low", "Medium", "High")
levels(predict_dat$connect_index)<-c("Low", "Medium", "High")
levels(predict_dat$wood_value_index)<-c("Low", "Medium", "High")
levels(predict_dat$small_risk)<-c("Low","Low_Medium","Medium","Medium_High","High")

#Ensure predict_data is a data.frame
predict_dat <- as.data.frame(predict_dat)

#PREDICTIONS TAKE A LONG TIME, ABOUT 3 MINUTES PER LINE
#Predict values for latent variables
pred_wood_value = predict(object=dfit,node="wood_value_index",data=predict_dat, method = "parents")
pred_fpi = predict(dfit,node="attraction_index",data=predict_dat, method = "parents")
pred_connect = predict(dfit,node="connect_index",data=predict_dat, method = "parents")

#fill the columns
predict_dat$wood_value_index <- pred_wood_value
predict_dat$attraction_index <- pred_fpi
predict_dat$connect_index <- pred_connect

#Predict damage
pred_damage = predict(dfit,node = "small_risk_index",data = predict_dat,method = "parents")
predict_dat$small_risk <- pred_damage

#Add damage risk back into spatial dataset

df_cat$pred_damage <- pred_damage
df_cat$pred_wood_value <- pred_wood_value
df_cat$pred_attraction_index <- pred_fpi
df_cat$pred_connect <- pred_connect
```

```{r}
#Make risk raster

#sf object
df_sf <- st_as_sf(df_cat, coords = c("x", "y"), crs = st_crs(bng))


#df_sf <- readRDS("C:/Users/ik929086/Documents/iDeer/output/small_deer_full_df_cat_point_geometry.RDS")

# Convert the RasterLayer to a stars object
 stars_template <- stars::st_as_stars(template_rast_tiles)

#Make small deer predict_dat rasters to check layers
#Define the color palette
index_palette <- c("0" = NA, "1" = "green", "2" = "orange", "3" = "red")
#
#Forage pressure index
forage_vals <- c("Low"=1,"Medium"=2,"High"=3)
df_sf$forage_vals <- forage_vals[df_sf$pred_attraction_index]
df_sf_selected <- df_sf%>%dplyr::select(geometry, forage_vals)
#forage_r <- stars::st_rasterize(sf = df_sf_selected, template = stars_template)
forage_r <- stars::st_rasterize(sf = df_sf_selected)
#stars::write_stars(forage_r, "C:/Users/ik929086/Documents/iDeer/output/small_deer_forage_pressure_index_rast_test.tif",overwrite=TRUE)
plot(forage_r, col = index_palette)

#Connectivity index
connect_vals <- c("Low"=1,"Medium"=2,"High"=3)
df_sf$connect_vals <- connect_vals[df_sf$pred_connect]
df_sf_selected <- df_sf%>%dplyr::select(geometry, connect_vals)
#forage_r <- stars::st_rasterize(sf = df_sf_selected, template = stars_template)
connect_r <- stars::st_rasterize(sf = df_sf_selected)
#stars::write_stars(connect_r, "C:/Users/ik929086/Documents/iDeer/output/small_deer_connectivity_index_rast_test.tif",overwrite=TRUE)
plot(connect_r, col = index_palette)

#Wood value index
wood_value_vals <- c("Low"=1,"Medium"=2,"High"=3)
df_sf$wood_value_vals <- wood_value_vals[df_sf$pred_wood_value]
df_sf_selected <- df_sf%>%dplyr::select(geometry, wood_value_vals)
#forage_r <- stars::st_rasterize(sf = df_sf_selected, template = stars_template)
wood_value_r <- stars::st_rasterize(sf = df_sf_selected)
#stars::write_stars(connect_r, "C:/Users/ik929086/Documents/iDeer/output/small_deer_connectivity_index_rast_test.tif",overwrite=TRUE)
plot(wood_value_r, col = index_palette)

#stars::write_stars(thermoreg_r, "C:/Users/ik929086/Documents/iDeer/output/small_deer_forage_pressure_index_rast_test.tif",overwrite=TRUE)

#  # Define the value mapping for pred_damage
risk_palette <- c("0"="transparent","1" = "green", "2" = "yellow", "3" = "orange", "4" = "red", "5" = "brown")

 damage_values <- c("Low" = 1, "Low_Medium" = 2, "Medium" = 3, "Medium_High" = 4, "High" = 5)
 df_sf$value <- damage_values[df_sf$pred_damage]
 
 #Convert to raster
 # Select the geometry and value column
 df_sf_selected <- df_sf %>% dplyr::select(geometry, value)
 #make a stars template
 # Use the template raster for extent, resolution, and CRS
 r <- stars::st_rasterize(sf = df_sf_selected)
 plot(r, col = risk_palette)
```
