---
title: "current_deer_impact_risk_EW_large_deer"
format: html
editor: visual
---

This code will produce a current deer impact risk map for the whole of England and Wales, using the latest spatial layers. This is for the "large deer" model (fallow, red, sika)

```{r}
#Load packages

library(plyr); library(dplyr)
library(ggplot2)
library(sf)
library(raster)
library(terra)
library(here)
library(progress)
library(bnlearn)
library(RColorBrewer)
library(rasterVis)
library(ggmap)
library(gRain)
library(BAMMtools)
library(purrr)

bng <- 27700

```

```{r}

#Load datasets needed to produce the large deer risk raster ####

#GB land cover map
lcm <- raster("C:/Users/ik929086/Documents/iDeer/data/raw-data/lcm-2023/gblcm2023_25m.tif")

#England-Wales 10k tiles
ew10k <- st_read(here("data/derived-data/10k_tiles_EW.shp"))

#nearest urban/suburban
urb_suburb <- raster("C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023/large_deer/nearest_urban_suburban_raster_2023_EW_projected.tif")

#woodland edges within 1km
edges_1000m <- raster("C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023/large_deer/sum_woodland_edge_area_1000m_2023_large_deer_GB.tif")

#summed dams within 1km
dams_1000m <- raster("C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023/large_deer/sum_dams_1000_non_wood_2023_GB_projected.tif")

#arable land within 1km
arable_1000m <- raster("C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023/large_deer/sum_arable_1000_2023.tif")
arable_1000m <- arable_1000m * 25 #forgot to do this when making original raster
                                  #necessary to know true arable area (multiplied by pixel size)

#summed quality perennial + woodland within 1km
perennial_wood_1000m <- raster("C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023/large_deer/sum_perennial_woodland_quality_1000m_large_deer_GB_2023.tif")

#Woodland connectivity within 1km
wood_connect_1000m <- raster("C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023/large_deer/woodland_connectivity_2023_1000m_EW.tif")


```

```{r}

#Load custom functions ####

#function to extract pixel values from raster layers
source(here("code/functions/extract_raster_pixels_func_10km_chunks.R"))

#Conditional probability tables ####

#Disturbance Index
large_disturbance_cpt_df <- read.csv("C:/Users/ik929086/Documents/iDeer/data/CPTs/Largedeer_Disturbance_Index_Distance_urban_Amy.csv")

#Foraging pressure index
#large_fpi_cpt_df <- read.csv("C:/Users/ik929086/Documents/iDeer/data/CPTs/Largedeer_Foraging_presure_index_Woodland_edge_1000m.Summed_quality_alt_forage_within_1000m.Arable_area_1000m_Amy_EDITED.csv")
#large_fpi_cpt_df <- read.csv("C:/Users/ik929086/Documents/iDeer/data/CPTs/large_deer_foraging_pressure_TEST.csv")

#Foraging pressure index
#arable areas and woodland edges lumped together
#same CPs as in the small deer FPI table
large_fpi_cpt_df <- read.csv("C:/Users/ik929086/Documents/iDeer/data/CPTs/Largedeer_Foraging_pressure_Index_Woodland_edge_arable_1000m.Summed_quality_alt_forage_1000m_Amy_FREESTYLE.csv")

#Thermoregulation Index
large_thermoreg_cpt_df <- read.csv("C:/Users/ik929086/Documents/iDeer/data/CPTs/Largedeer_Thermoregulation_Index_Summed_exposure_1000m_Amy.csv") 

#Connectivity Index
large_connectivity_cpt_df <- read.csv("C:/Users/ik929086/Documents/iDeer/data/CPTs/Largedeer_Connectivity_Index_Connectivity_1000m_Amy_EDITED.csv")

#Large deer impact risk
large_risk_cpt_df <- read.csv("C:/Users/ik929086/Documents/iDeer/data/CPTs/Largedeer_Deer_Damage_Risk_Disturbance_Index.Thermoregulation_Index.Foraging_presure_index.Connectivity_Index_Amy.csv") 



```

```{r}
#Add woodland edge within 1000m and arable within 1000m together

wood_edge_arable_1000m <- mosaic(arable_1000m, edges_1000m, fun = sum)

writeRaster(wood_edge_arable_1000m, "C:/Users/ik929086/Documents/iDeer/output/wood_edge_arable_1000m_EW.tif",overwrite=TRUE)

#read
wood_edge_arable_1000m <- raster("C:/Users/ik929086/Documents/iDeer/output/wood_edge_arable_1000m_EW.tif")
```

```{r}
#Create a dataframe containing all extracted raster values within user's landscape

#EXTRACT LENGTH OF WOODLAND EDGE

#edgelen <- extract_raster(map = edges_1000m,
#                          lcm = lcm,
#                          tiles = ew10k)


#saveRDS(edgelen, "C:/Users/ik929086/Documents/iDeer/output/edgelen_1000m_df_EW.RDS")

#read
#edgelen <- readRDS("C:/Users/ik929086/Documents/iDeer/output/edgelen_1000m_df_EW.RDS")

#EXTRACT WOOD EDGE / ARABLE AREA

#wood_edge_arable_pix <- extract_raster(map = wood_edge_arable_1000m,
                              #lcm = lcm,
                              #tiles = ew10k)

#saveRDS(wood_edge_arable_pix, "C:/Users/ik929086/Documents/iDeer/output/edge_arable_pix_1000m_df_EW.RDS")

#read
wood_edge_arable_pix <- readRDS("C:/Users/ik929086/Documents/iDeer/output/edge_arable_pix_1000m_df_EW.RDS")


#EXTRACT CONNECTIVITY

#connectpix <- extract_raster(map = wood_connect_1000m,
#                             lcm = lcm,
#                             tiles = ew10k)

#saveRDS(connectpix, "C:/Users/ik929086/Documents/iDeer/output/connectpix_1000m_df_EW.RDS")

#read
connectpix <- readRDS("C:/Users/ik929086/Documents/iDeer/output/connectpix_1000m_df_EW.RDS")



#EXTRACT summed DAMS
#damspix <- extract_raster(map = dams_1000m,
#                          lcm = lcm,
#                          tiles = ew10k)

#saveRDS(damspix, "C:/Users/ik929086/Documents/iDeer/output/dams_1000m_df_EW.RDS")

#read
damspix <- readRDS("C:/Users/ik929086/Documents/iDeer/output/dams_1000m_df_EW.RDS")

#EXTRACT nearest urban

#urbanpix <- extract_raster(map = urb_suburb,
#                          lcm = lcm,
#                          tiles = ew10k)

#saveRDS(urbanpix, "C:/Users/ik929086/Documents/iDeer/output/nearest_urban_suburban_df_EW.RDS")

#read
urbanpix <- readRDS("C:/Users/ik929086/Documents/iDeer/output/nearest_urban_suburban_df_EW.RDS")


#EXTRACT arable land within 1000m

#arablepix <- extract_raster(map = arable_1000m,
#                          lcm = lcm,
#                          tiles = ew10k)

#saveRDS(arablepix, "C:/Users/ik929086/Documents/iDeer/output/arablepix_1000m_df_EW.RDS")

#read
# arablepix <- readRDS("C:/Users/ik929086/Documents/iDeer/output/arablepix_1000m_df_EW.RDS")


#EXTRACT PERENNIAL/WOODLAND FORAGE QUALITY

#foragepix <- extract_raster(map = perennial_wood_1000m,
#                            lcm = lcm,
#                           tiles = ew10k)

#saveRDS(foragepix, "C:/Users/ik929086/Documents/iDeer/output/foragepix_1000m_df_EW.RDS")

#read
foragepix <- readRDS("C:/Users/ik929086/Documents/iDeer/output/foragepix_1000m_df_EW.RDS")

#left_join the datasets together #---------------

# df <- left_join(edgelen, connectpix, by = c("x","y")) %>%
#   left_join(arablepix, by = c("x","y")) %>%
#   left_join(damspix, by = c("x","y")) %>%
#   left_join(foragepix, by = c("x","y")) %>%
#   left_join(urbanpix, by = c("x","y"))

df <- left_join(wood_edge_arable_pix, connectpix, by = c("x","y")) %>%
  left_join(damspix, by = c("x","y")) %>%
  left_join(foragepix, by = c("x","y")) %>%
  left_join(urbanpix, by = c("x","y"))
               
#Remove the NAs

df.no.nas <- na.omit(df)

#save

#saveRDS(df.no.nas, "C:/Users/ik929086/Documents/iDeer/output/large_deer_full_df_no_nas.RDS")

saveRDS(df.no.nas, "C:/Users/ik929086/Documents/iDeer/output/large_deer_full_df_no_nas_arable_edges_combo.RDS")

#read

#df.no.nas <- readRDS("C:/Users/ik929086/Documents/iDeer/output/large_deer_full_df_no_nas.RDS")

#FOR TESTING: TAKE SUBSET
#read
# df.no.nas.full <- readRDS("C:/Users/ik929086/Documents/iDeer/output/large_deer_full_df_no_nas.RDS")
#  df.no.nas.full <- readRDS("C:/Users/ik929086/Documents/iDeer/output/large_deer_full_df_no_nas_arable_edges_combo.RDS")
#  df.no.nas <- df.no.nas.full %>%
#    slice(1:100000) %>%
#    st_as_sf(coords = c("x","y"))
# saveRDS(df.no.nas, "C:/Users/ik929086/Documents/iDeer/output/large_deer_full_df_no_nas_arable_edges_combo_TEST.RDS")
#read test df
df.no.nas <- readRDS("C:/Users/ik929086/Documents/iDeer/output/large_deer_full_df_no_nas_TEST.RDS")
```

```{r}

#calculate the optimum breakpoints using Jenks natural breaks optimization.
#to convert variables into categorical

#k = number of breaks = 3
#need to introduce subsets - dataset too large

#Edge density - USE TERCILES
#subset 5% - around 1 million data points
#edge_1000m_breaks <- BAMMtools::getJenksBreaks(df.no.nas$edges_1000m, k = 3, subset = 100)
#1800 9150 19700
# Find tertiles
# edge_Tert = quantile(df.no.nas$edges_1000m, c(0:3/3))
# hist(df.no.nas$edges_1000m)
# abline(v = 7525, col = "red")
# abline(v = 11600, col = "red")
# abline(v = 30525, col = "red")

#Woodland edge / arable area

edge_arable_tert = quantile(df.no.nas.full$wood_edge_arable_1000m, c(0:3/3))
hist(df.no.nas.full$wood_edge_arable_1000m)
abline(v = 13750, col = "red")
abline(v = 32850, col = "red")

#Nearest urban/suburban
#Predetermined using literature - don't need to use JenksBreaks
hist(df.no.nas$urb_suburb)
abline(v = 100, col = "red")
abline(v = 250, col = "red")

#urb_suburb_breaks <- BAMMtools::getJenksBreaks(df.no.nas$urb_suburb, k = 3, subset = 100)

#Summed DAMS
dams_tert <- quantile(df.no.nas$dams_1000m, c(0:3/3))
hist(df.no.nas$dams_1000m)
abline(v = 38400, col = "red")
abline(v = 52296, col = "red")
abline(v = 103771, col = "red")

dams_1000m_breaks <- BAMMtools::getJenksBreaks(df.no.nas$dams_1000m, k = 3, subset = 100)
#[1]  3138.249 40021.195 84997.758 (LOW/MED/MED-HIGH/HIGH)

#Connectivity
connect_tert <- quantile(df.no.nas$wood_connect_1000m, c(0:3/3))
hist(df.no.nas$wood_connect_1000m, ylim = c(0,100000))
abline(v = 8.33e+04, col = "red")
abline(v = 5.27e+05, col = "red")
abline(v = 6.15e+08, col = "red")

#connect_1km_breaks <- BAMMtools::getJenksBreaks(df.no.nas$wood_connect_1000m, k = 3, subset = 100)
#[1] 1.057911e+03 3.973864e+07 1.188407e+08 (LOW/MED/MED-HIGH/HIGH)

#Alternative forage (perennial and woodland)
peren_wood_tert <- quantile(df.no.nas$perennial_wood_1000m, c(0:3/3))
hist(df.no.nas$perennial_wood_1000m)
abline(v = 21540, col = "red")
abline(v = 29785, col = "red")
abline(v = 50250, col = "red")

#forage_1000m_breaks <- BAMMtools::getJenksBreaks(df.no.nas$perennial_wood_1000m, k= 3, subset = 100)
#[1]  3615 24854 48810 (LOW/MED/MED-HIGH/HIGH)

# #Arable - naturally has 2 breaks
# arable_tert <- quantile(df.no.nas$arable_1000m, c(0:3/3))
# hist(df.no.nas$arable_1000m)
# abline(v = 1350, col = "red")
# abline(v = 22025, col = "red")
# abline(v = 125350, col = "red")
# 
# arable_1000m_breaks <- BAMMtools::getJenksBreaks(df.no.nas$arable_1000m, k = 3, subset = 100)
#[1] 0  38175 107700 (LOW/MED/HIGH)
#NEW VALUES AFTER FIXING LEFT_JOIN: 0 25725 111075
```

```{r}

#Reclassify continuous data into pre-specified Low,Medium,High categories using breaks from JenksBreaks

df_cat <- df.no.nas 

# #Edges within 1000m 
# #LOW/MED/HIGH
# df_cat$edges_1000m <- ifelse(df_cat$edges_1000m  <= 7525, "Low",
#           ifelse(df_cat$edges_1000m  > 7525 & df_cat$edges_1000m  <=11600, "Medium",
#                  #ifelse(df_cat$edges_1000m  > 11600 & df_cat$edges_1000m <=, "Medium_High",
#           ifelse(df_cat$edges_1000m >11600, "High", NA)))#)

#Wood edges / arable
df_cat$wood_edge_arable_1000m <- ifelse(df_cat$wood_edge_arable_1000m  <= 13750, "Low",
          ifelse(df_cat$wood_edge_arable_1000m  > 13750 & df_cat$wood_edge_arable_1000m  <=32850, "Medium",
          ifelse(df_cat$wood_edge_arable_1000m >32850, "High", NA)))#)

#Connectivity within 1000m 
#LOW/MED/HIGH
#Woodland connectivity
 df_cat$wood_connect_1000m <- ifelse(
  df_cat$wood_connect_1000m <= 8.33e+04, "Low",
  ifelse(df_cat$wood_connect_1000m > 8.33e+04 & df_cat$wood_connect_1000m <= 5.27e+05, "Medium",
         #ifelse(df_cat$wood_connect_1000m > 3.973864e+07 & df_cat$wood_connect_1000m <=1.188407e+08, "Medium_High",
    ifelse(df_cat$wood_connect_1000m > 5.27e+05, "High", NA)))#)
  

#Arable within 1000m
#LOW/MED/HIGH
# df_cat$arable_1000m <- ifelse(df_cat$arable_1000m <= 1350, "Low",
#           ifelse(df_cat$arable_1000m > 1350 & df_cat$arable_1000m <=22025, "Medium",
#           ifelse(df_cat$arable_1000m >22025, "High", NA)))

#Perennial/wood summed quality within 1000m
#LOW/MED/HIGH

df_cat$perennial_wood_1000m <- ifelse(df_cat$perennial_wood_1000m <= 21540, "Low",
          ifelse(df_cat$perennial_wood_1000m > 21540 & df_cat$perennial_wood_1000m <=29785, "Medium",
          #ifelse(df_cat$perennial_wood_1000m > 24854 & df_cat$perennial_wood_1000m <=48810, "Medium_High",
          ifelse(df_cat$perennial_wood_1000m >29785, "High", NA)))#)

#Summed DAMS within 1000m
#LOW/MED/HIGH

#DAMS
df_cat$dams_1000m <- ifelse(df_cat$dams_1000m <= 38400, "Low",
                      ifelse(df_cat$dams_1000m > 38400  & df_cat$dams_1000m <=52296, "Medium",
                      #ifelse(df_cat$dams_1000m > 40021.195 & df_cat$dams_1000m <=84997.758 , "Medium_High",
                      ifelse(df_cat$dams_1000m > 52296, "High", NA)))#)

#Nearest urban/suburban area
#Predetermined - don't need to use JenksBreaks
#Near/Medium/Far
df_cat$urb_suburb <- ifelse(df_cat$urb_suburb  <= 100, "Near",
                      ifelse(df_cat$urb_suburb> 100 & df_cat$urb_suburb  <=250, "Medium",
                      ifelse(df_cat$urb_suburb  > 250, "Far", NA)))

#ensure factor levels in correct order 
df_cat$dams_1000m <- factor(df_cat$dams_1000m, levels = c("Low","Medium","High"))
df_cat$wood_connect_1000m <- factor(df_cat$wood_connect_1000m, levels= c("Low","Medium","High"))
#df_cat$arable_1000m <- factor(df_cat$arable_1000m, levels = c("Low","Medium","High"))
#df_cat$edges_1000m <- factor(df_cat$edges_1000m, levels = c("Low","Medium","High"))
df_cat$wood_edge_arable_1000m <- factor(df_cat$wood_edge_arable_1000m, levels = c("Low","Medium","High"))
df_cat$urb_suburb <- factor(df_cat$urb_suburb, levels = c("Near","Medium","Far"))
df_cat$perennial_wood_1000m <- factor(df_cat$perennial_wood_1000m, levels = c("Low","Medium","High"))

unique(df_cat$urb_suburb)
unique(df_cat$dams_1000m)
unique(df_cat$perennial_wood_1000m)
#unique(df_cat$arable_1000m)
unique(df_cat$wood_connect_1000m)
#unique(df_cat$edges_1000m)
unique(df_cat$wood_edge_arable_1000m)


#save df_cat

#saveRDS(df_cat, "C:/Users/ik929086/Documents/iDeer/output/large_deer_full_df_cat.RDS")

#rm(df.no.nas)
```

#Set up conditional probability tables for BBN

```{r}
#CPTS for measured nodes

#read dataset
#df_cat <- readRDS("C:/Users/ik929086/Documents/iDeer/output/large_deer_full_df_cat.RDS")

#nearest urban/suburban
urban_cpt <-matrix(c(0.333333,0.333333,0.333333),ncol = 3,dimnames = list(NULL, c("Near","Medium","Far")))
#alternative forage quality within 1000m
#includes woodland and perennial 
alt_forage_cpt <- matrix(c(0.333333,0.333333,0.333333),ncol = 3,dimnames = list(NULL, c("Low", "Medium","High")))
#woodland edge area within 1000m
edge_cpt <- matrix(c(0.333333,0.333333,0.333333),ncol = 3,dimnames = list(NULL, c("Low", "Medium","High")))
#dams within 1000m
dams_cpt<-matrix(c(0.333333,0.333333,0.333333),ncol = 3,dimnames = list(NULL, c("Low", "Medium","High")))
#woodland connectivity within 1000m
wood_connect_cpt <- matrix(c(0.333333,0.333333,0.333333),ncol = 3,dimnames = list(NULL, c("Low", "Medium","High")))
#arable area within 1000m
arable_cpt <- matrix(c(0.333333,0.333333,0.333333),ncol = 3,dimnames = list(NULL, c("Low", "Medium","High")))
```

```{r}
#CPT for Connectivity Index ---------------#

large_connectivity_cpt_df <- large_connectivity_cpt_df %>%
  dplyr::select(-c("X","Expertise","Confidence","Total"))
  
# Define the dimensions
connect_index_levels <- c("Low", "Medium", "High")
wood_connectivity_1000m_levels <- unique(large_connectivity_cpt_df$Connectivity_1000m)

# Initialize the array with dimensions and names
connectivity_index_cpt <- array(
  NA,  # Placeholder value
  dim = c(length(connect_index_levels), 
          length(wood_connectivity_1000m_levels)), 
  dimnames = list(
    connect_index = connect_index_levels,
    Woodland_connectivity_1000m = wood_connectivity_1000m_levels)
  )


# Populate the array with values from the DataFrame
for (i in 1:nrow(large_connectivity_cpt_df)) {
  # Get the indices for each dimension
  connect_idx <- which(dimnames(connectivity_index_cpt)$Woodland_connectivity_1000m == large_connectivity_cpt_df$Connectivity_1000m[i])


  # Assign values for each connectivity index level
  connectivity_index_cpt["Low", connect_idx] <- large_connectivity_cpt_df$Low[i]
  connectivity_index_cpt["Medium", connect_idx] <- large_connectivity_cpt_df$Medium[i]
  connectivity_index_cpt["High", connect_idx] <- large_connectivity_cpt_df$High[i]
}
connectivity_index_cpt <- connectivity_index_cpt / 100
```

```{r}
# #CPT for Foraging pressure index ---------------#
# 
# fpi_cpt_df <- large_fpi_cpt_df %>%
#   #dplyr::select(-c("X","Expertise","Confidence","Total"))
#   dplyr::select(-c("Total"))
# 
#   
# head(fpi_cpt_df)
# 
# # Define the dimensions
# forage_pressure_index_levels <- c("Low", "Medium", "High")
# alt_forage_qual_levels <- unique(fpi_cpt_df$Summed_quality_alt_forage_within_1000m)
# wood_edge_area_levels <- unique(fpi_cpt_df$Woodland_edge_1000m)
# arable_area_levels <- unique(fpi_cpt_df$Arable_area_1000m)
# edge_levels <- unique(fpi_cpt_df$edges_1000m)
# 
# # Initialize the array with dimensions and names
# forage_pressure_index_cpt <- array(
#   NA,  # Placeholder value
#   dim = c(length(forage_pressure_index_levels), 
#           length(alt_forage_qual_levels), 
#           length(wood_edge_area_levels),
#           length(arable_area_levels)),
#   dimnames = list(
#     forage_pressure_index = forage_pressure_index_levels,
#     alt_forage_qual_1000m = alt_forage_qual_levels,
#     edges_1000m = wood_edge_area_levels,
#     arable_1000m = arable_area_levels
#   )
# )
# 
# # Populate the array with values from the DataFrame
# for (i in 1:nrow(fpi_cpt_df)) {
#   # Get the indices for each dimension
#   edge_idx <- which(dimnames(forage_pressure_index_cpt)$edges_1000m == fpi_cpt_df$Woodland_edge_1000[i])
#   qual_idx <- which(dimnames(forage_pressure_index_cpt)$alt_forage_qual_1000m == fpi_cpt_df$Summed_quality_alt_forage_within_1000m[i])
#   arable_idx <- which(dimnames(forage_pressure_index_cpt)$arable_1000m == fpi_cpt_df$Arable_area_1000m[i])
# 
#   
#   # Assign values for each forage pressure index level
#   forage_pressure_index_cpt["Low", qual_idx, edge_idx, arable_idx] <- fpi_cpt_df$Low[i]
#   forage_pressure_index_cpt["Medium", qual_idx, edge_idx, arable_idx] <- fpi_cpt_df$Medium[i]
#   forage_pressure_index_cpt["High", qual_idx, edge_idx, arable_idx] <- fpi_cpt_df$High[i]
# }
# forage_pressure_index_cpt <- forage_pressure_index_cpt / 100
# forage_pressure_index_cpt
```

```{r}
#CPT for Foraging pressure index ---------------#

fpi_cpt_df <- large_fpi_cpt_df %>%
  dplyr::select(-c("X","Expertise","Confidence","Total"))

head(fpi_cpt_df)

# Define the dimensions
forage_pressure_index_levels <- c("Low", "Medium", "High")
alt_forage_qual_levels <- unique(fpi_cpt_df$Summed_quality_alt_forage_1000m)
wood_edge_arable_area_levels <- unique(fpi_cpt_df$Woodland_edge_arable_1000m)

# Initialize the array with dimensions and names
forage_pressure_index_cpt <- array(
  NA,  # Placeholder value
  dim = c(length(forage_pressure_index_levels), 
          length(alt_forage_qual_levels), 
          length(wood_edge_arable_area_levels)),
  dimnames = list(
    forage_pressure_index = forage_pressure_index_levels,
    alt_forage_qual_1000m = alt_forage_qual_levels,
    wood_edge_arable_1000m = wood_edge_arable_area_levels
  )
)

# Populate the array with values from the DataFrame
for (i in 1:nrow(fpi_cpt_df)) {
  # Get the indices for each dimension
  wood_edge_arable_idx <- which(dimnames(forage_pressure_index_cpt)$wood_edge_arable_1000m == fpi_cpt_df$Woodland_edge_arable_1000m[i])
  qual_idx <- which(dimnames(forage_pressure_index_cpt)$alt_forage_qual_1000m == fpi_cpt_df$Summed_quality_alt_forage_1000m[i])

  
  # Assign values for each forage pressure index level
  forage_pressure_index_cpt["Low", qual_idx, wood_edge_arable_idx] <- fpi_cpt_df$Low[i]
  forage_pressure_index_cpt["Medium", qual_idx, wood_edge_arable_idx] <- fpi_cpt_df$Medium[i]
  forage_pressure_index_cpt["High", qual_idx, wood_edge_arable_idx] <- fpi_cpt_df$High[i]
}
forage_pressure_index_cpt <- forage_pressure_index_cpt / 100
forage_pressure_index_cpt
```

```{r}
#CPT for thermoregulation index --------------------------------####

thermoreg_cpt_df<- large_thermoreg_cpt_df %>%
  dplyr::select(-c("X","Expertise","Confidence","Total"))

# Define the dimensions
thermoreg_index_levels <- c("Low", "Medium", "High")
sum_dams_1000m_levels <- unique(thermoreg_cpt_df$Summed_exposure_1000m)

# Initialize the array with dimensions and names
thermoreg_index_cpt <- array(
  NA,  # Placeholder value
  dim = c(length(thermoreg_index_levels), 
          length(sum_dams_1000m_levels)),
  dimnames = list(
    thermoreg_index = thermoreg_index_levels,
    sum_dams_1000m = sum_dams_1000m_levels
  )
)

# Populate the array with values from the DataFrame
for (i in 1:nrow(thermoreg_cpt_df)) {
  # Get the indices for each dimension
  dams_idx <- which(dimnames(thermoreg_index_cpt)$sum_dams_1000m == thermoreg_cpt_df$Summed_exposure_1000m[i])

  # Assign values for each forage pressure index level
  thermoreg_index_cpt["Low", dams_idx] <- thermoreg_cpt_df$Low[i]
  thermoreg_index_cpt["Medium", dams_idx] <- thermoreg_cpt_df$Medium[i]
  thermoreg_index_cpt["High", dams_idx] <- thermoreg_cpt_df$High[i]
}
thermoreg_index_cpt <- thermoreg_index_cpt / 100
thermoreg_index_cpt
```

```{r}
#CPT for disturbance index --------------------------------####

disturbance_cpt_df<- large_disturbance_cpt_df %>%
  dplyr::select(-c("X","Expertise","Confidence","Total"))

# Define the dimensions
disturbance_index_levels <- c("Low", "Medium", "High")
distance_to_urban_levels <- unique(large_disturbance_cpt_df$Distance_to_urban)

# Initialize the array with dimensions and names
disturbance_index_cpt <- array(
  NA,  # Placeholder value
  dim = c(length(disturbance_index_levels), 
          length(distance_to_urban_levels)),
  dimnames = list(
    disturb_index = disturbance_index_levels,
    dist_to_urban = distance_to_urban_levels
  )
)

# Populate the array with values from the DataFrame
for (i in 1:nrow(disturbance_cpt_df)) {
  # Get the indices for each dimension
  disturb_idx <- which(dimnames(disturbance_index_cpt)$dist_to_urban == disturbance_cpt_df$Distance_to_urban[i])

  # Assign values for each forage pressure index level
  disturbance_index_cpt["Low", disturb_idx] <- disturbance_cpt_df$Low[i]
  disturbance_index_cpt["Medium", disturb_idx] <- disturbance_cpt_df$Medium[i]
  disturbance_index_cpt["High", disturb_idx] <- disturbance_cpt_df$High[i]
}
disturbance_index_cpt <- disturbance_index_cpt / 100
disturbance_index_cpt
```

```{r}
#Final CPT: deer damage risk -----------------------------------####

large_risk_cpt_df<- large_risk_cpt_df %>%
  dplyr::select(-c("Expertise","Confidence","Total")) %>%
  rename(forage_pressure_index=Foraging_presure_index,
         connect_index=Connectivity_Index,
         thermoreg_index=Thermoregulation_Index,
         disturb_index=Disturbance_Index)

# Replace '..' with '_' in column names
colnames(large_risk_cpt_df) <- gsub("\\.\\.", "_", colnames(large_risk_cpt_df))
  
head(large_risk_cpt_df)

# Define the dimensions
large_risk_index_levels <- c("Low", "Low_Medium" ,"Medium", "Medium_High" , "High")
connectivity_index_levels <- unique(large_risk_cpt_df$connect_index)
forage_pressure_index_levels <- unique(large_risk_cpt_df$forage_pressure_index)
thermoreg_index_levels <- unique(large_risk_cpt_df$thermoreg_index)
disturb_index_levels <- unique(large_risk_cpt_df$disturb_index)

# Initialize the array with dimensions and names
large_risk_index_cpt <- array(
  NA,  # Placeholder value
  dim = c(length(large_risk_index_levels), 
          length(connectivity_index_levels), 
          length(forage_pressure_index_levels), 
          length(thermoreg_index_levels),
          length(disturb_index_levels)),
  dimnames = list(
    large_risk_index = large_risk_index_levels,
    connect_index = connectivity_index_levels,
    forage_pressure_index = forage_pressure_index_levels,
    thermoreg_index = thermoreg_index_levels,
    disturb_index = disturb_index_levels
  )
)

# Populate the array with values from the DataFrame
for (i in 1:nrow(large_risk_cpt_df)) {
  # Get the indices for each dimension
  connect_idx <- which(dimnames(large_risk_index_cpt)$connect_index == large_risk_cpt_df$connect_index[i])
  fpi_idx <- which(dimnames(large_risk_index_cpt)$forage_pressure_index == large_risk_cpt_df$forage_pressure_index[i])
  thermoreg_idx <- which(dimnames(large_risk_index_cpt)$thermoreg_index == large_risk_cpt_df$thermoreg_index[i])
  disturb_idx <- which(dimnames(large_risk_index_cpt)$disturb_index ==
large_risk_cpt_df$disturb_index[i])
  
  # Assign values for each forage pressure index level
  large_risk_index_cpt["Low", connect_idx, fpi_idx, thermoreg_idx, disturb_idx] <- large_risk_cpt_df$Low[i]
  large_risk_index_cpt["Low_Medium", connect_idx, fpi_idx, thermoreg_idx, disturb_idx] <- large_risk_cpt_df$Low_Medium[i]
  large_risk_index_cpt["Medium", connect_idx, fpi_idx, thermoreg_idx, disturb_idx] <- large_risk_cpt_df$Medium[i]
  large_risk_index_cpt["Medium_High", connect_idx, fpi_idx, thermoreg_idx, disturb_idx] <- large_risk_cpt_df$Medium_High[i]
  large_risk_index_cpt["High", connect_idx, fpi_idx, thermoreg_idx, disturb_idx] <- large_risk_cpt_df$High[i]
}
large_risk_index_cpt <- large_risk_index_cpt / 100
large_risk_index_cpt 
```

```{r}
#Create BBN structure#------------------------------------

# Step 1: Explicitly define the nodes in the network
nodes <- c(
  "Woodland_connectivity_1000m",
  "dist_to_urban",
  "alt_forage_qual_1000m",
  "edges_1000m",
  "sum_dams_1000m",
  "forage_pressure_index",
  "thermoreg_index",
  "connect_index",
  "arable_1000m",
  "disturb_index",
  "large_risk_index"
)

#empty graph
library(bnlearn)
e = empty.graph(nodes)

arc.set = matrix(c("Woodland_connectivity_1000m", "connect_index",
                   "dist_to_urban", "disturb_index", 
                   "alt_forage_qual_1000m", "forage_pressure_index",
                   "arable_1000m", "forage_pressure_index",
                   "edges_1000m","forage_pressure_index",
                   "sum_dams_1000m","thermoreg_index",
                   "thermoreg_index","large_risk_index",
                   "connect_index","large_risk_index",
                   "forage_pressure_index","large_risk_index",
                   "disturb_index", "large_risk_index"),
                 ncol = 2, byrow = TRUE,
                 dimnames = list(NULL, c("from", "to")))

arcs(e) <- arc.set

model_string <- modelstring(e) 

net<-model2network(model_string) 
# You dont need to repeat the names of the nodes with parents (child nodes) 

# Custom fitting network (matching up the nodes to their CPTs)
dfit = custom.fit(net, dist = list(Woodland_connectivity_1000m = wood_connect_cpt, 
                                   dist_to_urban = urban_cpt,
                                   alt_forage_qual_1000m = alt_forage_cpt,
                                   edges_1000m = edge_cpt,
                                   arable_1000m = arable_cpt,
                                   sum_dams_1000m = dams_cpt,
                                   connect_index = connectivity_index_cpt,
                                   thermoreg_index = thermoreg_index_cpt,
                                   disturb_index = disturbance_index_cpt,
                                   forage_pressure_index =forage_pressure_index_cpt,
                                   large_risk_index=large_risk_index_cpt))

#Plot BN structure ####
graphviz.plot(net)

#Check parameters ####
dfit
```

```{r}
predict_dat <- df_cat %>%st_drop_geometry() #%>% #drop geometry
  #mutate(across(where(is.character), toupper)) %>% #convert characters to upper case
  #dplyr::select(-c("x","y"))

#Ensure variable names match those in BBN
predict_dat<-predict_dat%>%rename(
  edges_1000m=edges_1000m,
  arable_1000m=arable_1000m,
  dist_to_urban=urb_suburb,
  alt_forage_qual_1000m=perennial_wood_1000m,
  sum_dams_1000m=dams_1000m,
  Woodland_connectivity_1000m=wood_connect_1000m)

#Make empty columns for the latent (unobserved) variables

predict_dat$forage_pressure_index <- NA
predict_dat$connect_index <- NA
predict_dat$thermoreg_index <- NA
predict_dat$disturb_index <- NA
predict_dat$large_risk <- NA

head(predict_dat)

#Ensure all columns are factors, not characters
predict_dat <- predict_dat %>% mutate_all(as.factor)

#Ensure factor levels are in correct order
levels(predict_dat$Woodland_connectivity_1000m)<-c("Low", "Medium", "High")
levels(predict_dat$alt_forage_qual_1000m)<-c("Low", "Medium", "High")
levels(predict_dat$dist_to_urban) <- c("Near","Medium","Far")
predict_dat$arable_1000m <- factor(predict_dat$arable_1000m, 
                                   levels = c("Low", "Medium", "High"))
levels(predict_dat$sum_dams_1000m)<-c("Low", "Medium", "High")
levels(predict_dat$edges_1000m)<-c("Low", "Medium", "High")
levels(predict_dat$forage_pressure_index)<-c("Low", "Medium", "High")
levels(predict_dat$connect_index)<-c("Low", "Medium", "High")
levels(predict_dat$thermoreg_index)<-c("Low", "Medium", "High")
levels(predict_dat$disturb_index)<-c("Low", "Medium", "High")
levels(predict_dat$large_risk)<-c("Low", "Medium", "Medium_High", "High")

all_nodes <- names(dfit)

#check levels match in dfit and predict_dat
data_check <- sapply(all_nodes, function(node) { identical(levels(predict_dat[[node]]), names(dfit[[node]]$prob)) })
print(data_check)
#For any variables where match is FALSE,
#Update factor levels in `predict_dat` to match `dfit`
# Identify mismatched nodes
mismatched_nodes <- names(data_check[data_check == FALSE])
for (node in mismatched_nodes) {
correct_levels <- names(dfit[[node]]$prob)
predict_dat[[node]] <- factor(predict_dat[[node]], levels = correct_levels)
}

#Ensure predict_data is a data.frame
predict_dat <- as.data.frame(predict_dat)

#Ensure factor levels are in correct order
levels(predict_dat$Woodland_connectivity_1000m)<-c("Low", "Medium", "High")
levels(predict_dat$alt_forage_qual_1000m)<-c("Low", "Medium", "High")
levels(predict_dat$dist_to_urban) <- c("Near","Medium","Far")
levels(predict_dat$arable_1000m)<-c("Low", "Medium", "High")
predict_dat$arable_1000m <- factor(predict_dat$arable_1000m, levels = c("Low", "Medium", "High"))
levels(predict_dat$sum_dams_1000m)<-c("Low", "Medium", "High")
levels(predict_dat$edges_1000m)<-c("Low", "Medium", "High")
levels(predict_dat$forage_pressure_index)<-c("Low", "Medium", "High")
levels(predict_dat$connect_index)<-c("Low", "Medium", "High")
levels(predict_dat$thermoreg_index)<-c("Low", "Medium", "High")
levels(predict_dat$disturb_index)<-c("Low", "Medium", "High")
levels(predict_dat$large_risk)<-c("Low","Low_Medium", "Medium", "Medium_High", "High")

#PREDICTIONS TAKE A LONG TIME, ABOUT 3 MINUTES PER LINE
#Predict values for latent variables
pred_thermoreg = predict(object=dfit,node="thermoreg_index",data=predict_dat, method = "parents")
pred_fpi = predict(dfit,node="forage_pressure_index",data=predict_dat, method = "parents")
pred_connect = predict(dfit,node="connect_index",data=predict_dat, method = "parents")
pred_disturb =predict(dfit, node="disturb_index",data=predict_dat, method = "parents")

#fill the columns
predict_dat$thermoreg_index <- pred_thermoreg
predict_dat$forage_pressure_index <- pred_fpi
predict_dat$connect_index <- pred_connect
predict_dat$disturb_index <- pred_disturb

#Predict damage
pred_damage = predict(dfit,node = "large_risk_index",data = predict_dat,method = "parents")
predict_dat$large_risk <- pred_damage

# scatter plot of forage pressure index and alt forage quality
predict_dat_sample <- predict_dat[sample(nrow(predict_dat), 10000), ]
ggplot(predict_dat_sample, aes(x = alt_forage_qual_1000m, y = forage_pressure_index)) +
  geom_jitter(width = 0.2, height = 0.2, size = 3, color = "blue") +
  labs(x = "Alt forage Q", y = "Index") +
  theme_minimal()
#edges
ggplot(predict_dat_sample, aes(x = edges_1000m, y = forage_pressure_index)) +
  geom_jitter(width = 0.2, height = 0.2, size = 3, color = "blue") +
  labs(x = "Edges", y = "Index") +
  theme_minimal()
#arable
ggplot(predict_dat_sample, aes(x = arable_1000m, y = forage_pressure_index)) +
  geom_jitter(width = 0.2, height = 0.2, size = 3, color = "blue") +
  labs(x = "Arable", y = "Index") +
  theme_minimal()

#Add damage risk back into spatial dataset

df_cat$pred_damage <- pred_damage
df_cat$pred_thermoreg <- pred_thermoreg
df_cat$pred_forage_pressure_index <- pred_fpi
df_cat$pred_connect <- pred_connect
df_cat$pred_disturb <- pred_disturb


```

```{r}

#Make risk raster #------------------------

#par(mfrow = c(1, 1))

 # Make sf object
 df_sf <- st_as_sf(df_cat, coords = c("x", "y"), crs = st_crs(bng))
 #df_sf <- st_transform(df_sf, crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
 #df_sf <- st_transform(df_sf, crs = bng)

 #save sf object
 #saveRDS(df_sf, "C:/Users/ik929086/Documents/iDeer/output/large_deer_full_df_cat_point_geometry.RDS")
 
#Make large deer predict_dat rasters to check layers
# Define the color palette
index_palette <- c("0" = NA, "1" = "green", "2" = "orange", "3" = "red")

#Forage pressure index
forage_vals <- c("Low"=1,"Medium"=2,"High"=3)
df_sf$forage_vals <- forage_vals[df_sf$pred_forage_pressure_index]
df_sf_selected <- df_sf%>%dplyr::select(geometry, forage_vals)
#forage_r <- stars::st_rasterize(sf = df_sf_selected, template = stars_template)
forage_r <- stars::st_rasterize(sf = df_sf_selected)
#stars::write_stars(forage_r, "C:/Users/ik929086/Documents/iDeer/output/large_deer_forage_pressure_index_rast_test.tif",overwrite=TRUE)
plot(forage_r, col = index_palette)

#Connectivity index
connect_vals <- c("Low"=1,"Medium"=2,"High"=3)
df_sf$connect_vals <- connect_vals[df_sf$pred_connect]
df_sf_selected <- df_sf%>%dplyr::select(geometry, connect_vals)
#forage_r <- stars::st_rasterize(sf = df_sf_selected, template = stars_template)
connect_r <- stars::st_rasterize(sf = df_sf_selected)
#stars::write_stars(connect_r, "C:/Users/ik929086/Documents/iDeer/output/large_deer_connectivity_index_rast_test.tif",overwrite=TRUE)
plot(connect_r, col = index_palette)

#Thermoreg index
thermoreg_vals <- c("Low"=1,"Medium"=2,"High"=3)
df_sf$thermoreg_vals <- thermoreg_vals[df_sf$pred_thermoreg]
df_sf_selected <- df_sf%>%dplyr::select(geometry, thermoreg_vals)
#forage_r <- stars::st_rasterize(sf = df_sf_selected, template = stars_template)
thermoreg_r <- stars::st_rasterize(sf = df_sf_selected)
#stars::write_stars(connect_r, "C:/Users/ik929086/Documents/iDeer/output/large_deer_connectivity_index_rast_test.tif",overwrite=TRUE)
plot(thermoreg_r, col = index_palette)
#stars::write_stars(thermoreg_r, "C:/Users/ik929086/Documents/iDeer/output/large_deer_forage_pressure_index_rast_test.tif",overwrite=TRUE)

#Disturbance index
disturbance_vals <- c("Low"=1,"Medium"=2,"High"=3)
df_sf$disturbance_vals <- disturbance_vals[df_sf$pred_disturb]
df_sf_selected <- df_sf%>%dplyr::select(geometry, disturbance_vals)
disturbance_r <- stars::st_rasterize(sf = df_sf_selected)
plot(disturbance_r, col = index_palette)

 # Define the value mapping for pred_damage
 damage_values <- c("LOW" = 1, "LOW-MED" = 2, "MED" = 3, "MED-HIGH" = 4, "HIGH" = 5)
 df_sf$value <- damage_values[df_sf$pred_damage]

 #Convert to raster
 # Select the geometry and value column
 df_sf_selected <- df_sf %>% dplyr::select(geometry, value)
 #make a stars template
 # Convert the RasterLayer to a stars object
 stars_template <- stars::st_as_stars(lcm)
 # Use the template raster for extent, resolution, and CRS
 #r <- stars::st_rasterize(sf = df_sf_selected, template = stars_template)
 r <- stars::st_rasterize(sf = df_sf_selected)

stars::write_stars(r, "C:/Users/ik929086/Documents/iDeer/output/large_deer_risk_raster_test.tif",overwrite=TRUE)

#r_rast <- raster("C:/Users/ik929086/Documents/iDeer/output/large_deer_risk_raster.tif")
  
 #r_rast <- terra::rast(r)
 
 #Finally, crop the raster to the England-Wales shapefile
 
 #EW <- st_read("C:/Users/ik929086/Documents/iDeer/data/raw-data/GB shapefile/England_Wales_combined.shp")
 
 r_rast_EW <- crop(r_rast, EW)
 r_rast_EW <- mask(r_rast_EW, EW)
 
 r_rast_EW <- replace(r_rast_EW,  r_rast_EW==0, NA)
 
#writeRaster(r_rast_EW, "C:/Users/ik929086/Documents/iDeer/output/large_deer_risk_raster_EW.tif",overwrite=TRUE)
```
