---
title: "current_deer_impact_risk_EW"
format: html
editor: visual
---

This code will produce a current deer impact risk map for the whole of England and Wales, using the latest spatial layers

```{r}
#Load packages

library(plyr)
library(ggplot2)
library(dplyr)
library(sf)
library(raster)
library(terra)
library(here)
library(progress)
library(bnlearn)
library(RColorBrewer)
library(rasterVis)
library(ggmap)
library(gRain)

bng <- 27700

```

```{r}

#Load latest spatial layers, made in update_spatial_layers.R with associated functions

#All these layers have been calculated using a combined NFI/CEHLCM raster made using the 2022 maps.

#Load linear feature density at 200m scale
lf <- raster(here("data/derived-data/2015-spatial-layers/linear_features/lf_200_mosaic_all_tiles_corrected.tif"))
crs(lf) <- bng

#Load MAX DAMS calculated at 200m scale
dams <- raster(here("data/derived-data/2015-spatial-layers/Max_DAMS/focal.dams.1000.max.non_wood_EW.tif"))

#Woodland edge/core land cover raster (2022)
edge_core_rast <- raster::raster(here("output/EW_datasets_2022/edge_core_raster_2022_all_tiles_EW.tif"))
crs(edge_core_rast) <- bng

  
#This layer does NOT include woodland edge type
nfi_lcm_map <- raster(here("data/derived-data/nfi_lcm_2022_overlaid.tif"))
crs(nfi_lcm_map) <- bng

#Binary woodland raster
NFI_LCM_woods_only <- raster(here("output/NFILCM_2022_binary_woodland_all_tiles_EW.tif"))
crs(NFI_LCM_woods_only) <- bng

#Read in woodland polygon dataset
#Combined NFI 2022 and LCM 2022 woodlands
#These polygons will be used to calculate the connectivity, they are unified
#All touching polygons have been unified
#hab_patches_all <- st_read(here("outputs/NFI_LCM_2022_polys_made_in_R.shp"))

#Read in woodland polygons from ArcGIS pro:
wood_polys <- st_read(here("data/derived-data/NFILCM_2022_GB_polys_arcgis.shp"))
st_crs(woodland_polys) <- bng

hab_patches_all <- wood_polys %>%
  dplyr::select(-c(SHAPE_Leng, SHAPE_Area)) %>%
  mutate(patch_ID = dplyr::row_number(),
         Shape_Area = st_area(geometry))%>%
  mutate(Shape_Area = as.numeric(Shape_Area))

#Incoming connectivity raster
connectivity <- raster(here("output/EW_datasets_2022/small_deer/woodland_connectivity_200m_2022_GB.tif"))


```

```{r}
#Load custom functions ####

#function to extract pixel values from raster layers
source(here("code/functions/extract_raster_pixels_func.R"))
```

```{r}
#----------------------- EXTRACT NUTRITIONAL LANDSCAPE QUALITY VALUES ####

#LAND COVER EXTRACTION AT 200m AROUND WOODLAND PIXELS ####

forage.q.vals <- read.csv(here("data/raw-data/Expert_Qnaire/Forage_Q_medians_large_small_deer.csv"))

land.cover.classes <- read.csv(here("data/raw-data/Expert_Qnaire/Expert_derived_quality_ranks_edge_types_with_water_no_mixed_woods.csv"))

land.cover.classes <- land.cover.classes %>%
  dplyr::select(c(Land.cover, class))

#Filter for small deer only

forage.q.vals <- forage.q.vals %>% filter(species_group %in% c("small"))

forage.q.vals <- left_join(forage.q.vals, land.cover.classes, by = "Land.cover")
  
  #Reclassify land cover map using forage quality scores
  
  #make is-becomes matrix
  reclass_vals <- 
  forage.q.vals%>%dplyr::select(Median,class) %>%
    rename(becomes = Median,
           is = class) %>%
    relocate(is) %>%
    filter(!is.na(is))
  
  reclass_vals
  
  #Reclassify
  map_reclass <- raster::reclassify(edge_core_rast, reclass_vals)
  
  #Mask map so background is set to NAs
  
  map_reclass_cropped <- crop(map_reclass, GB)
  map_reclass_masked <- mask(map_reclass_cropped, GB, inverse = T)
  
  #create circular buffers around every pixel of 200 metres
  circle.buff = raster::focalWeight (map_reclass, d=200, type="circle",fillNA=T )#Create buffer
  circle.buff[circle.buff > 0] <- 1   # replacing weights by 1
  Focal200= raster::focal(map_reclass, w=circle.buff, fun=mean, na.rm=T,pad=TRUE, padValue=NA,)#do focal
  
  plot(Focal200)
  crs(Focal200) <- bng
  
 #Extract surrounding landscape quality values into a dataframe ####

 lcpix <- extract_pixel_vals(map_reclass = map_reclass,
                             woodland_polys = woodland_polys,
                             raster = Focal1000,
                             landscape = landscape
                             )

  
```

```{r}
#----------------------Make sf points of all woodland pixels ####

#Get woodland pixels as sf points

chunked.wood <- crop(woods_binary, map_ext)
chunked.wood[chunked.wood == 0] <- NA #make zeros NAs
chunked.wood.points <- rasterToPoints(chunked.wood, spatial = TRUE) #Raster to point
chunked.wood.points <- st_as_sf(chunked.wood.points, crs = bng)
chunked.wood.points <- sf::st_transform(chunked.wood.points, crs = bng)
```

```{r}
#-------EXTRACT LINEAR FEATURE DENSITY WITHIN 200m RASTER

#
lfpix <- extract_pixel_vals(map_reclass = map_reclass,
                               woodland_polys = woodland_polys,
                               raster = lf_raster,
                               landscape = landscape)

#Plot
ggplot(lfpix) +
  geom_tile(aes(x = x, y = y, fill = class)) +
  scale_fill_viridis_c(option = "plasma") +  # Apply a continuous viridis color scale
  theme_minimal() +
  guides(fill = guide_colorbar(barwidth = 1, barheight = 10)) +  # Customize the colorbar appearance
  labs(title = "Linear feature length within 1km",
       fill = "") 
```

```{r}
#--------EXTRACT SUMMED DAMS WITHIN 200m RASTER
damspix <- extract_pixel_vals(map_reclass = map_reclass,
                            woodland_polys = woodland_polys,
                            raster = Focal1000_dams,
                            landscape = landscape)

ggplot(damspix) +
  geom_tile(aes(x = x, y = y, fill = class)) +
  scale_fill_viridis_c(option = "plasma") +  # Apply a continuous viridis color scale
  theme_minimal() +
  guides(fill = guide_colorbar(barwidth = 1, barheight = 10)) +  # Customize the colorbar appearance
  labs(title = "Maximum DAMS within 1km",
       fill = "") 
```

```{r}
#--------COMBINE THE SPATIAL DATASETS INTO ONE

#Rename class columns to all be unique for left_join
damspix <- damspix %>% rename(max_dams = class)
lfpix <- lfpix %>% rename(lf_density_1km = class)
lcpix <- lcpix %>% rename(lc_q = class)
woodpix <- woodpix %>% rename(wood_q = class)

#left_join the datasets by pixel_ID and coordinates
df <- left_join(lcpix, woodpix, by = c("pixel_ID","x","y"))
df <- left_join(df,damspix,by = c("pixel_ID","x","y"))
df <- left_join(df,road_pix,by=c("pixel_ID","x","y"))
df <- left_join(df,lfpix,by=c("pixel_ID","x","y"))
df <- left_join(df,urbanpix,by=c("pixel_ID","x","y"))
df <- left_join(df,connect_df,by=c("pixel_ID","x","y"))
```

```{r}
#-------Reclassify continuous data into pre-specified LOW,MED,HIGH categories

```

```{r}
#-------Set up conditional probability tables for BBN
```

```{r}
#----Create BBN structure ####
```

```{r}
#------Predict values for 4 indices using BBN
#Indices: Disturbance Index, Thermoregulation Index, Nutritional landscape Index, Nutritional woodland index

```

```{r}
#------Predict values for deer damage risk, add to final dataframe
```

```{r}
#---------Draw maps
```

`{#--------Add predicted damage data to an interactive leaflet map ####}`
