---
title: "DAMS_2015_open_habitat_raster_Becks"
author: "Amy Gresham"
date: "2024-01-29"
output: html_document
---

```{r}
library(raster)
library(sf)
library(dplyr)
library(tidyr)
library(fasterize)
library(terra)
library(here)

here()

bng = 27700 #coordinate system EPSG code (British National Grid = epsg:27700)
```


```{r}
#Read in CEH lcm
lcm2015.rast <- raster::raster(here(file.path = "data/raw-data/lcm2015gb25m.tif"))
lcm2015.rast <- setMinMax(lcm2015.rast)
crs(lcm2015.rast) <- bng

#Import DAMS raster as exposure metric (layer from Becks) 50m res
#DAMS <- raster::raster(here(file.path = input_dir,"DAMS","dams.tif"))
DAMS_resam <- raster::raster(here(file.path = "data/raw-data/DAMS/DAMS_resample25.tif"))
crs(DAMS) <- bng
```

```{r}
#Use land cover map as reference, resample DAMS to 25m resolution

#DAMS_resam <- raster::resample(DAMS, lcm2015.rast, method = "bilinear") # error: Error in x$.self$finalize() : attempt to apply non-function

#Replace all NA's in DAMS layer with 0
#DAMS_resam_no_na <- DAMS_resam

#DAMS_resam_no_na[is.na(DAMS_resam_no_na)] = 0

#Reclass LCM so all habitats we want are 1 and everything else is 0
#0 = woodlands
#Urban areas included in "open habitats"

reclass <- data.frame(is = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,
                             18,19,20,21), becomes = c(0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1))

lcm_mask <- reclassify(lcm2015.rast, reclass)

#Multiply DAMs and binary LCM together - any habitats we don't want will be set to 0 DAMS

DAMS_open_raster <- DAMS_resam*lcm_mask
writeRaster(DAMS_open_raster, here("data/derived-data/2015-spatial-layers/DAMS_OPEN_raster.tif"),overwrite=TRUE)
```

#focal statistics, moving window
```{r}

DAMS_open_raster <- raster(here("data/derived-data/2015-spatial-layers/DAMS_OPEN_raster.tif"))
crs(DAMS_open_raster) <- bng

#uk10k <- sf::st_read("C:/Users/ij926050/Dropbox/BEAST_R/Inputs/LUES_GIS/10km_grid/10km_grid/gbng/10km_grid_region.shp")
#uk10k%>%slice_sample() -> uk10k.s
#DAMS_open_raster.crop <- crop(DAMS_open_raster, uk10k.s)

#circle.buff = raster::focalWeight (DAMS_open_raster.crop, d=250, type="circle", fillNA=F)#Create buffer
#Focal250= raster::focal(DAMS_open_raster.crop, w=circle.buff, fun=sum, na.rm=T,  "focal.dams.250.crop.tif",overwrite=TRUE)#do focal window analysis with weights matrix
circle.buff = raster::focalWeight (DAMS_open_raster, d=500, type="circle",fillNA=T )#Create buffer
circle.buff[circle.buff > 0] <- 1   # replacing weights by 1
Focal500= raster::focal(DAMS_open_raster, w=circle.buff, fun=max, na.rm=F, "focal.dams.500.max.tif", overwrite=T)#do focal window analysis with weights matrix

circle.buff = raster::focalWeight (DAMS_open_raster, d=1000, type="circle",fillNA=T )#Create buffer
circle.buff[circle.buff > 0] <- 1   # replacing weights by 1
Focal1000= raster::focal(DAMS_open_raster, w=circle.buff, fun=max, na.rm=F, "focal.dams.1000.max.non_wood.tif", overwrite=T)#do focal window analysis with weights matrix

circle.buff = raster::focalWeight (DAMS_open_raster, d=250, type="circle",fillNA=T )#Create buffer
circle.buff[circle.buff > 0] <- 1   # replacing weights by 1
Focal250= raster::focal(DAMS_open_raster, w=circle.buff, fun=max, na.rm=F,"focal.dams.250.max.tif", overwrite=T)#do focal window analysis with weights matrix


```

```{r}
x=raster::raster(here("data/derived-data/2015-spatial-layers/Max_DAMS/focal.dams.1000.max.non_wood.tif"))

#Load NFI/LCM2015 master map
map <- raster(here("data/derived-data/2015-spatial-layers/edge_core_raster_all_tiles_EW.tif"))

#Load 10k England-Wales tiles
uk10ew <- st_read(here("data/derived-data/10k_tiles_EW.shp"))

plot(x)
y=projectRaster(x,crs=bng)

#This maps the max dams score of all habitats except woodland.
#project to lcm 
dams <- projectRaster(x,map)
#crop and mask to 10k_tiles_EW
dams <- crop(dams, uk10ew)
dams <- mask(dams, uk10ew)

#save layer

writeRaster(dams,here("data/derived-data/2015-spatial-layers/Max_DAMS/focal.dams.1000.max.non_wood_EW.tif"))

```

