---
title: "Expert_Qnaire_connectivity"
author: "Amy Gresham"
date: "2023-11-20"
output: html_document
---

```{r}
library("dplyr")
library("reshape2")
library("tidyr")
library("ggplot2")
library("scales")
library("here")

here()
```


```{r}
#Read in data

data <- read.csv(here("data/raw-data/Expert_Qnaire/2023_11_22_results.csv"), header = TRUE)
#View(data)

#Question blocks:

#1. Q1 - Q18 Factors affecting connectivity

#2. Q19 Topographic slope

#3. Q19

#4. Q20 - 32 Forage quality

#Remove rows 2 & 3
data <- data[-c(1,2),] 

#Replace blanks with NA

data <- data %>% mutate_all(~na_if(., ""))

#Subset questions into blocks

Block1 <- data %>%
  dplyr::select(starts_with(c("Respondent","Q1_","Q2_","Q3_","Q4_","Q5_","Q6_","Q7","Q8","Q9_","Q10_","Q11_","Q12_","Q13_","Q14_","Q15_","Q16","Q17_")))

Block2 <- data %>%
  dplyr::select(starts_with(c("Respondent","Q18")))

Block3 <- data %>%
  dplyr::select(starts_with(c("Q19")))

Block4 <- data %>%
  dplyr::select(starts_with(c("Respondent","Q20_","Q21_","Q22_","Q23_","Q24_","Q25_","Q26_","Q27_","Q28_","Q29_","Q30_","Q31_","Q32_")))


#Change from wide to long

Block1_long <- data.frame(tidyr::gather(Block1 ,Question, Answer, Q1_1:Q17_6))
Block2_long <- data.frame(tidyr::gather(Block2,Question, Answer, Q18_1:Q18_6))
Block3_long <- data.frame(tidyr::gather(Block3,Question, Answer, Q19))
Block4_long <- data.frame(tidyr::gather(Block4, Question, Answer, Q20_1:Q32_6))

#Separate Question column into Question.number and Answer.number

Block1_long <- Block1_long %>%
  separate(Question, c("Question.number","Answer.number"),"_")

Block2_long <- Block2_long %>%
  separate(Question, c("Question.number","Answer.number"),"_")

Block3_long <- Block3_long %>%
  separate(Question, c("Question.number"),"_")

Block4_long <- Block4_long %>%
  separate(Question, c("Question.number","Answer.number"),"_")

#Put deer species into new column based on answer numbers

Block1_long <- Block1_long %>%
  mutate(Deer.species = case_when(
    endsWith(Answer.number, "1") ~ "Roe",
    endsWith(Answer.number, "2") ~ "Red",
    endsWith(Answer.number, "3") ~ "Fallow",
    endsWith(Answer.number, "4") ~ "Sika",
    endsWith(Answer.number, "5") ~ "Muntjac",
    endsWith(Answer.number, "6") ~ "CWD"
  ))

Block1_long$Deer.species <- factor(Block1_long$Deer.species, levels = c("CWD","Muntjac","Roe","Fallow","Red","Sika"))

Block2_long <- Block2_long %>%
  mutate(Deer.species = case_when(
    endsWith(Answer.number, "1") ~ "Roe",
    endsWith(Answer.number, "2") ~ "Red",
    endsWith(Answer.number, "3") ~ "CWD",
    endsWith(Answer.number, "4") ~ "Fallow",
    endsWith(Answer.number, "5") ~ "Muntjac",
    endsWith(Answer.number, "6") ~ "Sika"
  ))

Block2_long$Deer.species <- factor(Block2_long$Deer.species, levels = c( "CWD","Muntjac","Roe","Fallow","Red","Sika"))

Block4_long <- Block4_long %>%
  mutate(Deer.species = case_when(
    endsWith(Answer.number, "1") ~ "Roe",
    endsWith(Answer.number, "2") ~ "Red",
    endsWith(Answer.number, "3") ~ "Fallow",
    endsWith(Answer.number, "4") ~ "Sika",
    endsWith(Answer.number, "5") ~ "Muntjac",
    endsWith(Answer.number, "6") ~ "CWD"
  ))

Block4_long$Deer.species <- factor(Block4_long$Deer.species, levels = c( "CWD","Muntjac","Roe","Fallow","Red","Sika"))

#Put land cover type into new column based on question number

#question numbers block 1:
# [1] "Q1"   "Q2"   "Q3"   "Q4"   "Q5"   "Q8"   "Q8B"  "Q9"   "Q10"  "Q11"  "Q12"  "Q13"  "Q15"  "Q16"  "Q16B" "Q17"  "Q18" 

Block1_long <- Block1_long %>%
  mutate(Land.cover = case_when( 
     Question.number=="Q1" ~ "Broadleaved woodland",
     Question.number=="Q2" ~ "Coniferous woodland",
     Question.number=="Q3" ~ "Arable land",
     Question.number=="Q4" ~ "Improved grassland",
     Question.number=="Q5" ~ "Semi-natural grassland",
     Question.number=="Q8" ~ "Fenland",
     Question.number=="Q8B" ~ "Heathland",
     Question.number=="Q9" ~ "Peatland bog",
     Question.number=="Q10" ~ "Rivers or canals",
     Question.number=="Q11" ~ "Freshwater lakes",
     Question.number=="Q12" ~ "Saltmarsh",
     Question.number=="Q13" ~ "Urban areas",
     Question.number=="Q14"~ "Suburban areas",
     Question.number=="Q15"~"Dual carriageway",
     Question.number=="Q16" ~ "A roads",
     Question.number=="Q16B" ~ "B roads",
     Question.number=="Q17" ~ "Minor roads"
  ))

Block2_long <- Block2_long %>%
  mutate(Land.cover = case_when( 
     Question.number=="Q18" ~ "Woody linear features"
  ))

#question numbers block 3:

#"Q20" "Q21" "Q22" "Q23" "Q24" "Q25" "Q26" "Q27" "Q28" "Q29" "Q30" "Q31" "Q32"

Block4_long <- Block4_long %>%
  mutate(Land.cover = case_when( 
     Question.number=="Q20" ~ "Broadleaved woodland",
     Question.number=="Q21" ~ "Coniferous woodland",
     Question.number=="Q22" ~ "Arable land",
     Question.number=="Q23" ~ "Improved grassland",
     Question.number=="Q24" ~ "Neutral grassland",
     Question.number=="Q25" ~ "Acid grassland",
     Question.number=="Q26" ~ "Calcareous grassland",
     Question.number=="Q27" ~ "Fenland",
     Question.number=="Q28" ~ "Peatland bog",
     Question.number=="Q29" ~ "Heathland",
     Question.number=="Q30" ~ "Saltmarsh",
     Question.number=="Q31" ~ "Urban areas",
     Question.number=="Q32" ~ "Suburban areas"
  ))

#Replace NA with DON'T KNOW

#Block1_long <- Block1_long %>%
 # mutate_all(~ if_else(is.na(.), "Don't Know", .))

#Block3_long <- Block3_long %>%
  #mutate_all(~ if_else(is.na(.), "Don't Know", .))

#Summarise answer counts by deer species and land cover

Block1_summary <- Block1_long %>%
  group_by(Deer.species, Land.cover,Respondent) %>%
  count(Answer)

Block2_summary <- Block2_long %>%
  group_by(Deer.species, Land.cover,Respondent) %>%
  count(Answer)

Block4_summary <- Block4_long %>%
  group_by(Deer.species, Land.cover, Respondent) %>%
  count(Answer)

#Order answers

Block1_summary$Answer<-as.numeric(Block1_summary$Answer)
Block2_summary$Answer<-as.numeric(Block2_summary$Answer)
Block4_summary$Answer<-as.numeric(Block4_summary$Answer)

#Filter out outlying respondent

#Block1_summary <- Block1_summary%>%filter(!Contributor == "Outlier")
#Block3_summary <- Block3_summary%>%filter(!Contributor == "Outlier")

```

```{r}

#Generate colour palette

# Load required library
library(RColorBrewer)
# Define the number of colors in your palette
num_colors <- 21  # You can adjust this to the desired number of colors
# Generate a palette from dark blue to dark red
my_palette <- colorRampPalette(c("red", "yellow"))(num_colors)
#change the zero value to black (value 11)
my_palette[11] <- "white"

#Block 1 plot ####
#How easily can the six UK deer species move across/through these land cover types?
ggplot(Block1_summary, aes(x = Deer.species, y = n, fill = Answer)) + 
  geom_col()+
  scale_fill_gradientn(colors = my_palette)+
  facet_wrap(~Land.cover)+
  theme_bw()+
  ggtitle("Connectivity")+
  theme(panel.grid.minor = element_blank())+
  theme(panel.grid.major = element_blank())+
  theme(axis.text.x = element_text(angle=90, hjust=1))+
  theme(legend.text=element_text(size=10))+
  ylab("Count")+
  xlab("Deer species")+
  scale_y_continuous(limits = c(0, 10), breaks = seq(0, 10, 1))



```

```{r}
#Block 4 plot ####
#What is the forage quality of these land cover types?
ggplot(Block4_summary, aes(x = Deer.species, y = n, fill = Answer)) + 
  geom_bar(stat = "identity", position = "stack") +  # Use geom_bar with stat="identity" for stacked bar chart
  scale_fill_gradientn(colors = my_palette) +
  facet_wrap(~Land.cover) +
  ggtitle("Forage quality") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1),
        legend.text = element_text(size = 10)) +
  ylab("Count") +
  xlab("Deer species") +
  scale_y_continuous(limits = c(0, 10), breaks = seq(0, 10, 1))

```

