---
title: "extraction_DIA"
format: html
editor: visual

Purpose: to extract spatial information from our 2015 spatial layers for the DIA woodland polygons

THE DIA DATA ARE GDPR SENSITIVE AND ARE UNDER A DATA SHARING AGREEMENT. THEY MUST NOT BE SHARED WITH THIRD PARTIES WITHOUT APPROVAL FROM DJ.
---

```{r}
#Load packages

library(sf)
library(dplyr)
library(ggplot2)
library(here)
library(terra)

here()
```

```{r}

#Read in cleaned DIA data

dia <- st_read(here("./data/clean-data/DIA_high_density_2012-2018.shp"))
dia <- st_as_sf(dia)

```

# DAMS extraction

```{r}

#These are focal statistics rasters for three buffer sizes, 250, 500 and 1000

#DO WE WANT TO CHANGE THE BUFFER SIZES??

dams_file_path <- here("data/derived-data/2015-spatial-layers/Max_DAMS")
dams_file_path

rasterlist <- list.files(path = dams_file_path, pattern='.tif',
                       all.files=TRUE, full.names=TRUE)


rasterNames=sub('.*/', '', rasterlist)#remove file pathways from list
rasterNames=sub('*.tif', '', rasterNames)#remove extension from list

all_rasters <- terra::rast(rasterlist)#Create SpatRaster from list


names(all_rasters) = rasterNames#rename the rasters in the raster stack by the raster file names

DAMs_ectract <- terra::extract(all_rasters, vect(dia), fun = mean, na.rm=TRUE)  # returns a DF
DAMS_extract<- cbind(dia, DAMs_ectract)
write.csv(st_drop_geometry(DAMS_extract), here("data/DIA-2015-spatial-extracted/DAMS_NFI_extract.csv")) # save (maybe change the filepath?)

```

# Landscape metrics (donut)

```{r}

#Read in dataset

lc <- raster::raster(here("data/derived-data/2015-spatial-layers/edge_core_raster_all_tiles_EW.tif"))

plot(lc)

```

## 250 metre buffer

```{r}
POLY=as(dia, "Spatial")
veg = lc

polyFragStats <- function(POLY, veg) {
  # Create a buffer around the polygon
  buffer_poly <- buffer(POLY, width = 250, dissolve = TRUE)
  
  # Cut out the original polygon from the buffer
  buffer_area <- erase(buffer_poly, POLY)
  
  # Crop land cover map by the buffer area
  fcrop <- crop(veg, buffer_area)
  
  # Mask the cropped land cover map
  fmask <- mask(fcrop, buffer_area)
  
  # Extract class statistics
  res <- raster::extract(fmask, buffer_area, method = "simple")
  
  # Convert the results to a data frame and calculate statistics
  res <- as.data.frame(table(res))
  res$ID <- POLY$ID
  
  res <- res %>%
    mutate(total_pix = as.numeric(sum(Freq)),
           class = res) %>%
    dplyr::select(ID, class, Freq, total_pix) %>%
    mutate(perc_cov = Freq * 100 / total_pix, buff_area = area(buffer_area))
  
  return(res)
}


respoly <- ldply(1:length(POLY), function(i) {  # for each point
  out <- polyFragStats(POLY[i,],  veg=veg) # compute fragstats metrics 
  out$buffer_size <- "b250"
  return(out)
})  

respoly

write.csv(respoly, here("data/DIA-2015-spatial-extracted/landscapemetrics_250.csv"))
```

## 500 metre buffer

```{r}

POLY=as(dia, "Spatial")
veg = lc

polyFragStats <- function(POLY, veg) {
  # Create a buffer around the polygon
  buffer_poly <- buffer(POLY, width = 500, dissolve = TRUE)
  
  # Cut out the original polygon from the buffer
  buffer_area <- erase(buffer_poly, POLY)
  
  # Crop land cover map by the buffer area
  fcrop <- crop(veg, buffer_area)
  
  # Mask the cropped land cover map
  fmask <- mask(fcrop, buffer_area)
  
  # Extract class statistics
  res <- raster::extract(fmask, buffer_area, method = "simple")
  
  # Convert the results to a data frame and calculate statistics
  res <- as.data.frame(table(res))
  res$ID <- POLY$ID
  
  res <- res %>%
    mutate(total_pix = as.numeric(sum(Freq)),
           class = res) %>%
    dplyr::select(ID, class, Freq, total_pix) %>%
    mutate(perc_cov = Freq * 100 / total_pix, buff_area = area(buffer_area))
  
  return(res)
}


respoly <- ldply(1:length(POLY), function(i) {  # for each point
  out <- polyFragStats(POLY[i,],  veg=veg) # compute fragstats metrics 
  out$buffer_size <- "b500"
  return(out)
})  

respoly

write.csv(respoly, here("data/DIA-2015-spatial-extracted/landscapemetrics_500.csv"))
```

# 1000 metre buffer

```{r}

POLY=as(dia, "Spatial")
veg = lc

polyFragStats <- function(POLY, veg) {
  # Create a buffer around the polygon
  buffer_poly <- buffer(POLY, width = 1000, dissolve = TRUE)
  
  # Cut out the original polygon from the buffer
  buffer_area <- erase(buffer_poly, POLY)
  
  # Crop land cover map by the buffer area
  fcrop <- crop(veg, buffer_area)
  
  # Mask the cropped land cover map
  fmask <- mask(fcrop, buffer_area)
  
  # Extract class statistics
  res <- raster::extract(fmask, buffer_area, method = "simple")
  
  # Convert the results to a data frame and calculate statistics
  res <- as.data.frame(table(res))
  res$ID <- POLY$ID
  
  res <- res %>%
    mutate(total_pix = as.numeric(sum(Freq)),
           class = res) %>%
    dplyr::select(ID, class, Freq, total_pix) %>%
    mutate(perc_cov = Freq * 100 / total_pix, buff_area = area(buffer_area))
  
  return(res)
}


respoly <- ldply(1:length(POLY), function(i) {  # for each point
  out <- polyFragStats(POLY[i,],  veg=veg) # compute fragstats metrics 
  out$buffer_size <- "b1000"
  return(out)
})  

respoly

write.csv(respoly, here("data/DIA-2015-spatial-extracted/landscapemetrics_1000.csv"))
```

# Main road extraction

```{r}

```

# Urban / suburban extraction

```{r}

```

# Linear feature extraction

```{r}
#These woody linear features

wood_file_path <- here("data/derived-data/2015-spatial-layers/linear_features")

rasterlist <- list.files(path = wood_file_path, pattern='.tif',
                       all.files=TRUE, full.names=TRUE)

rasterNames=sub('.*/', '', rasterlist)#remove file pathways from list
rasterNames=sub('*.tif', '', rasterNames)#remove extension from list
rasterNames = substr(rasterNames,1,nchar(rasterNames)-11) # remove "mosaic"


all_rasters <- terra::rast(rasterlist)#Create SpatRaster from list


names(all_rasters) = rasterNames#rename the rasters in the raster stack by the raster file names


wood_extract <- terra::extract(all_rasters, vect(Sections_LocalData), fun = mean,  na.rm=TRUE)  # returns a DF
wood_extract<- cbind(Sections_LocalData, wood_extract)
write.csv(st_drop_geometry(wood_extract), here("data/DIA-2015-spatial-extracted/woody_NFI_extract.csv")) # save (maybe change the filepath?)
```
