---
title: "FC_DIA_DATA_cleaning"
format: html
editor: visual
---

This code chunk is for cleaning the raw Deer Impact Assessment data from the Forestry Commission. Data is from Alastair Ward, with permission to share from David Jam (FC).

THESE DATA ARE GDPR SENSITIVE AND ARE UNDER A DATA SHARING AGREEMENT. THEY MUST NOT BE SHARED WITH THIRD PARTIES WITHOUT APPROVAL FROM DJ.

```{r}

#Load packages

library(sf)
library(dplyr)
library(ggplot2)
library(here)

here()
```

```{r}

#Read in cleaned spreadsheet from Owain with combined deer impact data and Action Area information

df <- read.csv(here("./data/raw-data/DIA-data/DIA_wood_AA_data_combined.csv"))

#Read in spatial dataset containing woodland polygons that received DIA surveys

polys <- st_read(here("./data/raw-data/DIA-data/LCM2015GBwithinDIApolygoninfo.shp"))
```

```{r}
#Merge the two datasets by ID column

df_polys <- merge(df,polys, by = c("ID"))
df_polys <- st_as_sf(df_polys)

#Export to inspect in ArcGIS

write_sf(df_polys,here("./output/intermediate-outputs/DIA_data_polys_merged.shp"))

#Filter for woodlands only

df_polys <- subset(df_polys, bhab %in% c("Broadleaf woodland","Coniferous woodland"))

#Filter year for 2015 only - this will match with our 2015 spatial data
df_polys <- subset(df_polys, Year %in% c("2012","2013","2014","2015","2016","2017","2018"))

#Having inspected the polygons in ArcGIS, all polygons with the same ID belong to the same woodland. Each woodland is split up into different compartments, but each compartment has been allocated the same impact score and other info.

#Therefore, dissolve the polygons with the same ID into the same multipolygon object.

# Group and merge polygons by 'ID'
df_polys_merged <- df_polys %>%
  group_by(ID) %>%
  summarize(geometry = st_union(geometry))  # Merge polygons with the same ID

#Select columns 1-32 in original dataset (remove old geometries)
df_polys <- as.data.frame(df_polys)
df_polys <- df_polys %>% select(1:32)

#Remove Area.y (area of individual polygons) and FID_1 (polygon IDs)
df_polys <- df_polys %>%
  select(-c("Area.y", "FID_1"))

#Get unique rows
df_polys <- df_polys %>% distinct()

#Merge the new united geometries with the original data
df_joined <- merge(df_polys, df_polys_merged, by = c("ID"))

#Check for duplicates
df_joined <- df_joined %>% distinct()

#Some woodlands have been surveyed multiple times- select the most recent survey for each woodland

df_most_recent <- df_joined %>%
  group_by(ID) %>%
  filter(Year == max(Year)) %>%
  ungroup()

#Export to inspect in ArcGIS

write_sf(df_most_recent,here("./output/intermediate-outputs/DIA_data_st_union_polys.shp"))



```

```{r}

#Plot geometry 

ggplot(data=df_most_recent) +
  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  coord_sf() +  # Keep default sf coordinate system
  labs(title = "2013-2019") +
  theme_minimal()

#How many unique regions?
regions <- unique(df_most_recent$Region)
regions

#Plot regions ####

#London
#London <- subset(df_most_recent, Region %in% "London")
#ggplot(data=London) +
#  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
#  coord_sf() +  # Keep default sf coordinate system
#  labs(title = "London") +
#  theme_minimal()


#PA (Priority Area)

PAs <- unique(df_most_recent$PA)
PAs

#Plot the geometries of each PA
Cumbria <- subset(df_most_recent, PA %in% "Cumbria")
Suffolk <- subset(df_most_recent, PA %in% "Suffolk")
EM <- subset(df_most_recent, PA %in% "East Midlands")
WM <- subset(df_most_recent, PA %in% "West Midlands")
Oxford <- subset(df_most_recent, PA %in% "Oxford")

#Cumbria
ggplot(data=Cumbria) +
  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  coord_sf() +  # Keep default sf coordinate system
  labs(title = "Cumbria") +
  theme_minimal()

#Suffolk
ggplot(data=Suffolk) +
  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  coord_sf() +  # Keep default sf coordinate system
  labs(title = "Suffolk") +
  theme_minimal()

#East Midlands
ggplot(data=EM) +
  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  coord_sf() +  # Keep default sf coordinate system
  labs(title = "East Midlands") +
  theme_minimal()

#West Midlands
ggplot(data=WM) +
  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  coord_sf() +  # Keep default sf coordinate system
  labs(title = "West Midlands") +
  theme_minimal()

#Oxford
ggplot(data=Oxford) +
  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  coord_sf() +  # Keep default sf coordinate system
  labs(title = "Oxford") +
  theme_minimal()
```

```         
```

```{r}
hist(df_most_recent$Impact_sco)

#There are very few 2's and 4's in the dataset, probably due to surveyor bias.
#People less likely to score 2 and 4, a likert scale of 3 (low, med, high) is more intuitive
#Therefore, convert to 3-point likert scale
#0 = none,
#1 = low,
#2-3 = med, = 2
#4-5 = high = 3

# Replace all instances of 3 with 2 in the Impact_sco column
df_impact3 <- df_most_recent
df_impact3$Impact_sco[df_impact3$Impact_sco == 3] <- 2

# Replace all instances of 4 and 5 with 3 in the Impact_sco column
df_impact3$Impact_sco[df_impact3$Impact_sco == 4] <- 3
df_impact3$Impact_sco[df_impact3$Impact_sco == 5] <- 3

hist(df_impact3$Impact_sco)

#Export for inspection in ArcGIS

write_sf(df_impact3,here("./output/intermediate-outputs/DIA_data_impact3.shp"))

```

```{r}
#Exclude woodlands where deer densities are not high according to the JNCC dataset?
#Keep in mind the DIA dataset is biased because surveys were deliberately carried out in areas which had a deer problem.

#Read in JNCC deer density data ####

deer_density <- read.csv(here("./data/raw-data/DEER_JNCC/deer_density_sections_AMY.csv"))

deer_density <- deer_density %>% select(maxroe, maxred, maxsika, fallowmax, muntmax, MAXDEER, TILE_NAME)

#Read in uk10k map

uk10<- st_read(dsn = here("./data/raw-data/os_bng_grids.gpkg"), layer = "10km_grid")

#cbind tile geometry to deer density

uk10 <- uk10 %>% rename(TILE_NAME = tile_name)
deer_density <- merge(uk10, deer_density, by = "TILE_NAME")
deer_density <- deer_density %>% select(TILE_NAME, MAXDEER)

ggplot() +
  geom_sf(data = deer_density, aes(fill = MAXDEER)) 
hist(deer_density$MAXDEER)

#Filter for high density squares
high_density_tiles <- deer_density %>% filter(MAXDEER > 100)

ggplot() +
  geom_sf(data = high_density_tiles, aes(fill = NULL)) +
  geom_sf(data = df_impact3, aes(geometry = geometry, fill = Impact_sco))

hist(high_density_tiles$MAXDEER)

#Most of the woodlands fall within high-density deer areas as indicated by the JNCC data

#Filter out woodlands which do not fall within the high density tiles ####
#Ensure crs match
df_impact3 <- st_as_sf(df_impact3)
df_impact3 <- st_transform(df_impact3, crs=27700)
high_density_tiles <- st_transform(high_density_tiles, crs=27700)

#Find intersection between high density tiles and deer impact data
intersec <- st_intersects(df_impact3,high_density_tiles)

#Filter deer impact data to only include woodlands that occur in high density tiles
df_impacts_high_density <- df_impact3[apply(intersec, 1, any), ]

#How many woodlands left?
nrow(df_impacts_high_density)

ggplot() +
  geom_sf(data = high_density_tiles, aes(fill = NULL)) +
  geom_sf(data = df_impacts_high_density, aes(geometry = geometry, fill = Impact_sco))

hist(df_impacts_high_density$Impact_sco)

```
