---
title: "FC_DIA_DATA_cleaning"
format: html
editor: visual
---

This code chunk is for cleaning the raw Deer Impact Assessment data from the Forestry Commission. Data is from Alastair Ward, with permission to share from David Jam (FC).

THESE DATA ARE GDPR SENSITIVE AND ARE UNDER A DATA SHARING AGREEMENT. THEY MUST NOT BE SHARED WITH THIRD PARTIES WITHOUT APPROVAL FROM DJ.

```{r}

#Load packages

library(sf)
library(dplyr)
library(ggplot2)
library(here)

here()
```

```{r}

#Read in cleaned spreadsheet from Owain with combined deer impact data and Action Area information

df <- read.csv(here("./data/raw-data/DIA-data/DIA_wood_AA_data_combined.csv"))

df <- df %>% select(ID,Region,PA,AA,Month,Season,Year,Act_score,Impact_sco,Area,PercentBLW,location)

#Read in spatial dataset containing woodland polygons that received DIA surveys

polys <- st_read(here("./data/raw-data/DIA-data/LCM2015GBwithinDIApolygoninfo.shp"))

```

```{r}

#Having inspected the polygons in ArcGIS, all polygons with the same ID belong to the same woodland. Each woodland is split up into different compartments (FID_1), but each compartment has been allocated the same impact score and other info. The DIA surveys were done by walking a zig-zag transect through a whole site, source: Alastair Ward.

#Therefore, dissolve the polygons with the same ID into the same multipolygon object.

# Group and merge polygons by 'ID'
polys_merged <- polys %>%
  filter(ID > 0) %>% # Remove woodlands where ID = 0 as these are not in the DIA dataset
  subset(bhab %in% c("Broadleaf woodland","Coniferous woodland")) %>% #select woodlands only
  group_by(ID) %>%
  summarize(geometry = st_union(geometry))  # Merge polygons with the same ID

#Merge the DIA dataset with the polygons by site ID column

df_polys <- merge(df,polys_merged, by = c("ID"))
df_polys <- st_as_sf(df_polys)

#Export to inspect in ArcGIS

write_sf(df_polys,here("./output/intermediate-outputs/DIA_data_polys_merged.shp"))

#How does damage vary with year?

ggplot(df_polys, aes(x = Impact_sco)) +
  geom_histogram(binwidth = 1, fill = "steelblue", color = "black") +
  facet_wrap(~Year) +
  labs(x = "Impact Score", y = "Frequency", title = "Distribution of Impact Score by Survey Year") +
  theme_minimal()

#Is this a function of survey effort? 

hist(df_polys$Year) #Yes! 2015 is the most surveyed year.

#Filter year of survey to match with our 2015 spatial data
df_polys <- subset(df_polys, Year %in% c("2013","2014","2015","2016","2017","2018","2019"))

#Some woodlands have been surveyed multiple times- select the most recent survey for each woodland

df_most_recent <- df_polys %>%
  group_by(ID) %>%
  filter(Year == max(Year)) %>%
  ungroup()

#Export to inspect in ArcGIS
write_sf(df_most_recent,here("./output/intermediate-outputs/DIA_data_st_union_polys.shp"))



```

```{r}

#Plot geometry 

ggplot(data=df_most_recent) +
  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  coord_sf() +  # Keep default sf coordinate system
  labs(title = "2013-2019") +
  theme_minimal()

#How many unique regions?
regions <- unique(df_most_recent$Region)
regions

#Plot regions ####
#London <- subset(df_most_recent, Region %in% "London")
#ggplot(data=London) +
#  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
#  coord_sf() +  # Keep default sf coordinate system
#  labs(title = "London") +
#  theme_minimal()

#PA (Priority Area)

PAs <- unique(df_most_recent$PA)
PAs

#Plot the geometries of each PA
Cumbria <- subset(df_most_recent, PA %in% "Cumbria")
Suffolk <- subset(df_most_recent, PA %in% "Suffolk")
EM <- subset(df_most_recent, PA %in% "East Midlands")
WM <- subset(df_most_recent, PA %in% "West Midlands")
Oxford <- subset(df_most_recent, PA %in% "Oxford")
no_pa <- subset(df_most_recent, is.na(PA))

#Cumbria
ggplot(data=Cumbria) +
  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  coord_sf() +  # Keep default sf coordinate system
  labs(title = "Cumbria") +
  theme_minimal()

#Suffolk
ggplot(data=Suffolk) +
  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  coord_sf() +  # Keep default sf coordinate system
  labs(title = "Suffolk") +
  theme_minimal()

#East Midlands
ggplot(data=EM) +
  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  coord_sf() +  # Keep default sf coordinate system
  labs(title = "East Midlands") +
  theme_minimal()

#West Midlands
ggplot(data=WM) +
  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  coord_sf() +  # Keep default sf coordinate system
  labs(title = "West Midlands") +
  theme_minimal()

#Oxford
ggplot(data=Oxford) +
  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  coord_sf() +  # Keep default sf coordinate system
  labs(title = "Oxford") +
  theme_minimal()

#No PA

ggplot(data=no_pa) +
  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  coord_sf() +  # Keep default sf coordinate system
  labs(title = "Outside PAs") +
  theme_minimal()
```

```         
```

```{r}
hist(df_most_recent$Impact_sco)

#There are very few 2's and 4's in the dataset, probably due to surveyor bias.
#People less likely to score 2 and 4, a likert scale of 3 (low, med, high) is more intuitive
#Therefore, convert to 3-point likert scale
#0 = none,
#1 = low,
#2-3 = med, = 2
#4-5 = high = 3

# Replace all instances of 3 with 2 in the Impact_sco column
#df_impact3 <- df_most_recent
#df_impact3$Impact_sco[df_impact3$Impact_sco == 3] <- 2

# Replace all instances of 4 and 5 with 3 in the Impact_sco column
#df_impact3$Impact_sco[df_impact3$Impact_sco == 4] <- 3
#df_impact3$Impact_sco[df_impact3$Impact_sco == 5] <- 3

#hist(df_impact3$Impact_sco)

#Export for inspection in ArcGIS
#write_sf(df_impact3,here("./output/intermediate-outputs/DIA_data_impact3.shp"))

```

```{r}
#Export cleaned polygons

write_sf(df_impacts_high_density ,here("./data/clean-data/DIA_high_density_2013-2019.shp"))

```
