---
title: "FC_DIA_DATA_cleaning"
format: html
editor: visual
---

This code chunk is for cleaning the raw Deer Impact Assessment data from the Forestry Commission. Data is from Alastair Ward, with permission to share from David Jam (FC).

THESE DATA ARE GDPR SENSITIVE AND ARE UNDER A DATA SHARING AGREEMENT. THEY MUST NOT BE SHARED WITH THIRD PARTIES WITHOUT APPROVAL FROM DJ.

```{r}

#Load packages

library(sf)
library(dplyr)
library(ggplot2)
library(here)

here()
```

```{r}

#Read in cleaned spreadsheet from Owain with combined deer impact data and Action Area information

df <- read.csv(here("./data/raw-data/DIA-data/DIA_wood_AA_data_combined.csv"))

df <- df %>% select(ID,Region,PA,AA,Month,Season,Year,Act_score,Impact_sco,Area,PercentBLW,location)

#Read in spatial dataset containing woodland polygons that received DIA surveys

points <- st_read(here("./data/raw-data/DIA-data/DIAdataall.shp"))
```

```{r}

#Merging the point data

point_geom <- points %>% select("ID","geometry")

df_points <- merge(df, point_geom, by = "ID")

#How does damage vary with year?

ggplot(df_points, aes(x = Impact_sco)) +
  geom_histogram(binwidth = 1, fill = "steelblue", color = "black") +
  facet_wrap(~Year) +
  labs(x = "Impact Score", y = "Frequency", title = "Distribution of Impact Score by Survey Year") +
  theme_minimal()

#Is this a function of survey effort? 

hist(df_points$Year) #Yes! 2015 is the most surveyed year.

#Filter year of survey to match with our 2015 spatial data
df_points <- subset(df_points, Year > 2012)

#Some woodlands have been surveyed multiple times- select the most recent survey for each woodland

df_most_recent <- df_points %>%
  group_by(ID) %>%
  filter(Year == max(Year)) %>%
  ungroup()

df_most_recent <- df_most_recent %>% distinct()


```

```{r}

#Plot geometry 

#Replace all NAs in dataset with "None"

df_most_recent <- df_most_recent %>%
  mutate_at(vars(AA, PA), ~ ifelse(is.na(.), "None", .))

df_most_recent <- st_as_sf(df_most_recent)

#ggplot(data=df_most_recent) +
  #geom_sf(aes(geometry = geometry, fill = Impact_sco))   # Color by impact score

#How many unique regions?
regions <- unique(df_most_recent$Region)
regions

#Plot regions ####
#London <- subset(df_most_recent, Region %in% "London")
#ggplot(data=London) +
#  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
#  coord_sf() +  # Keep default sf coordinate system
#  labs(title = "London") +
#  theme_minimal()

#PA (Priority Area)

PAs <- unique(df_most_recent$PA)
PAs

#Plot the geometries of each PA
Cumbria <- subset(df_most_recent, PA %in% "Cumbria")
Suffolk <- subset(df_most_recent, PA %in% "Suffolk")
EM <- subset(df_most_recent, PA %in% "East Midlands")
WM <- subset(df_most_recent, PA %in% "West Midlands")
Oxford <- subset(df_most_recent, PA %in% "Oxford")
no_pa <- subset(df_most_recent, PA %in% "None")

#Cumbria
ggplot(data=Cumbria) +
  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  coord_sf() +  # Keep default sf coordinate system
  labs(title = "Cumbria") +
  theme_minimal()

#Suffolk
ggplot(data=Suffolk) +
  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  coord_sf() +  # Keep default sf coordinate system
  labs(title = "Suffolk") +
  theme_minimal()

#East Midlands
ggplot(data=EM) +
  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  coord_sf() +  # Keep default sf coordinate system
  labs(title = "East Midlands") +
  theme_minimal()

#West Midlands
ggplot(data=WM) +
  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  coord_sf() +  # Keep default sf coordinate system
  labs(title = "West Midlands") +
  theme_minimal()

#Oxford
ggplot(data=Oxford) +
  geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  coord_sf() +  # Keep default sf coordinate system
  labs(title = "Oxford") +
  theme_minimal()

#No PA

#ggplot(data=no_pa) +
  #geom_sf(aes(geometry = geometry, fill = Impact_sco)) +  # Color by impact score
  #coord_sf() +  # Keep default sf coordinate system
  #labs(title = "Outside PAs") +
  #theme_minimal()
```

```         
```

```{r}
hist(df_most_recent$Impact_sco)

#There are very few 2's and 4's in the dataset, probably due to surveyor bias.
#People less likely to score 2 and 4, a likert scale of 3 (low, med, high) is more intuitive
#Therefore, convert to 3-point likert scale
#0 = none,
#1 = low,
#2-3 = med, = 2
#4-5 = high = 3

# Replace all instances of 3 with 2 in the Impact_sco column
#df_impact3 <- df_most_recent
#df_impact3$Impact_sco[df_impact3$Impact_sco == 3] <- 2

# Replace all instances of 4 and 5 with 3 in the Impact_sco column
#df_impact3$Impact_sco[df_impact3$Impact_sco == 4] <- 3
#df_impact3$Impact_sco[df_impact3$Impact_sco == 5] <- 3

#hist(df_impact3$Impact_sco)

#Export for inspection in ArcGIS
#write_sf(df_impact3,here("./output/intermediate-outputs/DIA_data_impact3.shp"))

```

```{r}
#Export cleaned points

write_sf(df_most_recent ,here("./data/clean-data/DIA_points_2013_2019.shp"))

```
