---
title: "Hedge_density_per_10k_tile_EW"
author: "Amy Gresham"
date: "2024-02-01"
output: html_document

#Produce hedge density rasters for different buffer sizes around focal points
#Focal points inside NFI woodlands
#Should produce one raster for each buffer size (3 in total)
---

```{r}
library(sf)
library(here)
library(raster)
library(dplyr)
library(progress)

#Set project directory
project_dir <- here("iDeer_spatial_data")

# Set the output directory
output_dir <- here(project_dir, "outputs")
```

```{r}
#Import required spatial layers ####

bng <- 27700

# England and Wales 10k squares
ew10k <- sf::st_read(here("iDeer_spatial_data", "intermediate_outputs", "10k_tiles_EW.shp"))

# Import linear feature layer
#lf <- st_read("C:/Users/ik929086/Documents/iDeer_Local/iDeer_spatial_data/inputs/linear_features/GB_WLF_V1_0.gdb", layer = "GB_WLF_V1_0")
#lf <- mutate(lf, ID = row_number())

# CEH land cover map 2015 raster layer
lcm2015.rast <- raster::raster(here(project_dir,"inputs", "lcm-2015-tif", "lcm2015gb25m.tif"))
lcm2015.rast <- setMinMax(lcm2015.rast)

# Template raster with correct crs (bng), extent, and resolution (25m)
template_raster <- raster(ext = extent(lcm2015.rast), res = res(lcm2015.rast), crs = bng)

#nfi/ceh lcm overlaid raster - woodlands only
nfi.lcm.2015 <- raster(here(project_dir,"inputs", "nfi_lcm_2015_overlaid_woods_only.tif"))

#Read in nfi.lcm.overlaid shapefile version - made in ArcGIS
#Converted nfi.lcm.2015 to woodland binary raster than did raster to Polygon
#nfi.lcm.polys <- st_read(here(project_dir,"intermediate_outputs", "nfi_lcm_overlaid_shapefile_woods_export.shp"))

#Import modified linear feature layer
#Modification done in ArcGIS pro
#Used nfi.lcm.polys to erase overlapping linear feature geometry
#Result = linear features outside of woods

lf <- st_read(here(project_dir,"intermediate_outputs","linear_features_outside_woods.shp"))

```


```{r}
#LOOP TO PRODUCE LINEAR FEATURE LENGTH RASTERS AT 3 DIFFERENT BUFFER SIZES

# Test tiles
#tiles <- filter(ew10k, tile_name %in% c("SU78","SU79"))

#Filter the ew10k tiles up to where processing crashed
#Last run got up to tile 1628 for lf1000
#Therefore, restart process at tile 1628
#ew10k_1628_up <- ew10k[1628:1740, ]
```


```{r}
lf_250_list <- list()
lf_500_list <- list()
lf_1000_list <- list()


# Calculate length of linear features near woodland points for each buffer size
# Output a raster for each buffer size
buffer_sizes <- c(250, 500, 1000)

# Test tiles
tiles <- ew10k %>% slice(51:nrow(ew10k))
tiles <- tiles %>% slice(1390:nrow(tiles))

#tiles <- ew10k

# Create a progress bar
pb <- progress_bar$new(
  format = "[:bar] :percent Elapsed: :elapsed Time remaining: :eta",
  total = nrow(tiles)
)
suppressWarnings(
for (i in 1:length(tiles$tile_name)) {
  tile <- tiles[i,]
  tile.buff <- st_buffer(tile, (1200))
  chunked.wood <- crop(nfi.lcm.2015, tile)
  chunked.wood[chunked.wood == 0] <- NA #remove zeros
  chunked.wood.points <- rasterToPoints(chunked.wood, spatial = TRUE)
  chunked.wood.points <- st_as_sf(chunked.wood.points, crs = crs)
  chunked.wood.points <- sf::st_transform(chunked.wood.points, crs = bng)

  if (nrow(chunked.wood.points) > 0) {
    chunked.wood.points$uniqueforID <- paste("point", chunked.wood.points$geometry, sep = "_")
    chunked.wood.points$TILENAME <- tile$tile_name
    
    lf_outside_woodlands <- st_filter(lf, tile.buff)
    
    if (nrow(lf_outside_woodlands) > 0) {
      
      sections_lf <- chunked.wood.points
        sections_lf_all <- list()
      
      # make a raster_layer for each buffer size
      for (j in 1:length(buffer_sizes)) {
       
        LFclip <- st_intersection(lf_outside_woodlands, st_buffer(st_centroid(sections_lf), buffer_sizes[j]))
        
        if(nrow(LFclip)>0){
        
        LFclip <- LFclip %>% mutate(lf_len = st_length(geometry))
        sections_l <- LFclip %>% st_drop_geometry() %>%
          group_by(uniqueforID) %>%
          dplyr::summarise(LFLEN = sum(units::drop_units(lf_len)))
        sections_l <- merge(sections_l, sections_lf, by = "uniqueforID", all = TRUE)
        sections_l <- sections_l %>% dplyr::mutate(LFLEN = tidyr::replace_na(LFLEN, 0))
        sections_l$buffer_size <- buffer_sizes[j]
        sections_lf_all[[length(sections_lf_all) + 1]] <- data.frame(sections_l)
        
        chunked.wood.points.lf <- do.call(rbind, sections_lf_all)
        chunked.wood.points.lf <- st_as_sf(chunked.wood.points.lf, crs = bng)

        chunked.wood.points.2col <- chunked.wood.points.lf %>% dplyr::select(geometry, LFLEN)
        template_raster <- crop(lcm2015.rast, tile.buff)
        raster_layer<- raster::rasterize(chunked.wood.points.2col, template_raster, field = "LFLEN")
        raster_layer <- crop(raster_layer, tile)
        crs(raster_layer) <- bng
      
      
      # Save raster_layer to the corresponding list based on buffer size
        buff <- buffer_sizes[j]

        if (grepl("250", buff)) {
          lf_250_list[[i]] <- raster_layer
        } else if (grepl("500", buff)) {
          lf_500_list[[i]] <- raster_layer
        } else if (grepl("1000", buff)) {
          lf_1000_list[[i]] <- raster_layer
        }
        
        } else {
          # Assign NA values for each buffer size only if LFclip is empty for all buffer sizes
          lf_250_list[[i]] <- NA
          lf_500_list[[i]] <- NA
          lf_1000_list[[i]] <- NA
        }
        
      }  # end of buffer size loop
      
    } else {
      #Assign NA if nrow lf_outside_woodlands = 0
      lf_250_list[[i]] <- NA
      lf_500_list[[i]] <- NA
      lf_1000_list[[i]] <- NA
    }
    
  } else {
    #Assign NA if nrow chunked.wood.points = 0
    lf_250_list[[i]] <- NA
    lf_500_list[[i]] <- NA
    lf_1000_list[[i]] <- NA
  }
  
 pb$tick()  # Increment the progress bar
 
}
)
```


```{r}
# Save the lists
saveRDS(lf_250_list, file = here(output_dir, "lf_250_list_1439_1740_corrected.rds"))
saveRDS(lf_500_list, file = here(output_dir, "lf_500_list_1439_1740_corrected.rds"))
saveRDS(lf_1000_list, file = here(output_dir, "lf_1000_list_1439_1740_corrected.rds"))
```

#1.Make sure all items are BNG
#2.Convert NA list elements to null then remove
#3.Mosaic and save

```{r}
#LF 250 ####

#Read lists with the tiles from all the runs

#LF 250
lf_250_1_50 <- readRDS(here(output_dir, "R tile list backups", "lf_250_list_1_50_corrected.rds"))
lf_250_51_1619 <- readRDS(here(output_dir, "R tile list backups", "lf_250_list_51_1619_corrected.rds"))
lf_250_1439_1740 <- readRDS(here(output_dir, "R tile list backups", "lf_250_list_1439_1740_corrected.rds"))


#Add these lists together

lf_250_all_tiles <- c(lf_250_1_50, lf_250_51_1619, lf_250_1439_1740)

# Label elements that are not RasterLayers or are empty
valid_rasters_lf_250 <- lapply(lf_250_all_tiles,  function(raster_layer) {
  if (inherits(raster_layer, "RasterLayer") && any(!is.na(values(raster_layer)))) {
    return(raster_layer)
  } else {
    return(NULL)
  }
})

# Remove NULL elements from the list
valid_rasters_lf_250 <- Filter(function(x) !is.null(x), valid_rasters_lf_250)

# Function to check if two raster extents are equal
#are_extents_equal <- function(raster1, raster2) {
#  ext1 <- extent(raster1)
#  ext2 <- extent(raster2)
#  identical(ext1, ext2)
#}

# Remove rasters with the same extent
valid_rasters_lf_250_unique <- valid_rasters_lf_250[!duplicated(sapply(valid_rasters_lf_250, function(r) extent(r)))]

#Mosaic tiles
#Mosaic will average the overlapping pixel values
system.time({
lf_250_mosaic <- do.call(raster::mosaic, c(valid_rasters_lf_250, fun = mean))
})

crs(lf_250_mosaic) <- bng

#save mosaic

writeRaster(lf_250_mosaic, here(output_dir, "lf_250_mosaic_all_tiles_corrected.tif"), overwrite = TRUE)

```

```{r}
#LF 500 ####

#Add lists together

#LF 500
lf_500_1_50 <- readRDS(here(output_dir, "R tile list backups", "lf_500_list_1_50_corrected.rds"))
lf_500_51_1620 <- readRDS(here(output_dir, "R tile list backups", "lf_500_list_51_1620_corrected.rds"))
lf_500_1439_1740 <- readRDS(here(output_dir, "R tile list backups", "lf_500_list_1439_1740_corrected.rds"))

lf_500_all_tiles <- c(lf_500_1_50, lf_500_51_1620, lf_500_1439_1740)

# Label elements that are not RasterLayers or are empty
valid_rasters_lf_500 <- lapply(lf_500_all_tiles,  function(raster_layer) {
  if (inherits(raster_layer, "RasterLayer") && any(!is.na(values(raster_layer)))) {
    return(raster_layer)
  } else {
    return(NULL)
  }
})

# Remove NULL elements from the list
valid_rasters_lf_500 <- Filter(function(x) !is.null(x), valid_rasters_lf_500)

# Remove rasters with the same extent
valid_rasters_lf_500_unique <- valid_rasters_lf_500[!duplicated(sapply(valid_rasters_lf_500, function(r) extent(r)))]

#Mosaic tiles
#Mosaic will average the overlapping pixel values
system.time({
lf_500_mosaic <- do.call(raster::mosaic, c(valid_rasters_lf_500, fun = mean))
})

crs(lf_500_mosaic) <- bng

#save mosaic

writeRaster(lf_500_mosaic, here(output_dir, "lf_500_mosaic_all_tiles_corrected.tif"), overwrite = TRUE)
```

```{r}
#LF 1000 ####


#LF 1000
lf_1000_1_50 <- readRDS(here(output_dir, "R tile list backups", "lf_1000_list_1_50_corrected.rds"))
lf_1000_51_1620 <- readRDS(here(output_dir, "R tile list backups", "lf_1000_list_51_1620_corrected.rds"))
lf_1000_1439_1740 <- readRDS(here(output_dir, "R tile list backups", "lf_1000_list_1439_1740_corrected.rds"))


#Add these lists together

lf_1000_all_tiles <- c(lf_1000_1_50, lf_1000_51_1620, lf_1000_list_1439_1740)

# Label elements that are not RasterLayers or are empty
valid_rasters_lf_1000 <- lapply(lf_1000_all_tiles,  function(raster_layer) {
  if (inherits(raster_layer, "RasterLayer") && any(!is.na(values(raster_layer)))) {
    return(raster_layer)
  } else {
    return(NULL)
  }
})

# Remove NULL elements from the list
valid_rasters_lf_1000 <- Filter(function(x) !is.null(x), valid_rasters_lf_1000)

# Remove rasters with the same extent
valid_rasters_lf_1000_unique <- valid_rasters_lf_1000[!duplicated(sapply(valid_rasters_lf_1000, function(r) extent(r)))]


#Mosaic tiles
#Mosaic will average the overlapping pixel values
system.time({
lf_1000_mosaic <- do.call(raster::mosaic, c(valid_rasters_lf_1000, fun = mean))
})

crs(lf_1000_mosaic) <- bng

#save mosaic

writeRaster(lf_1000_mosaic, here(output_dir, "lf_1000_mosaic_all_tiles_corrected.tif"), overwrite = TRUE)
```

#END ####
```

