---
#title: "Connectivity_woodlands_nfi_lcm_2015"
#Purpose: create woodland connectivity map for whole of UK using nfi/lcm 2015 master map
#Based on incoming connectivity_deer_KW.R from Kevin Watts (FR)
---

```{r}
#Load packages

library(sf)
library(dplyr)
library(ggplot2)
library(here)
library(progress)

here()
```

```{r}
#TEST #### create test SHAPEFILES - you can read in shapefiles/rasters and use/covert as necessary ####
b1 <- st_buffer(st_point(c(1,1)), 1)
b2 <- st_buffer(st_point(c(7,5)), 0.5)
b3 <- st_buffer(st_point(c(9,1)), 0.35)
b4 <- st_buffer(st_point(c(3,3)), 0.4)
patches <- st_sfc(b1, b2, b3, b4) %>%  
  st_as_sf()

# load shapefile and wrangle to get area and unique id
hab_patches <- patches %>%
  st_simplify() %>%
  mutate(patch_ID = seq.int(nrow(.)), patch_area = st_area(.))

# plot patches
ggplot(data = hab_patches) +
  geom_sf(aes(fill = patch_area)) +
  geom_sf_label(aes(label = patch_ID)) +
  coord_sf()

#### SET CONNECTIVITY PARAMETERS ####
# connectivity parametetrs - % of dispersers reaching a set distance #
percentage_dispersers <- 0.05 ### 5%
dispersal_distance <- 3 ### 400m
dispersal_contribution <-
  -((log(1 / percentage_dispersers)) / dispersal_distance)

# Buffer distance represents the cut off - this stops the script measuring every pairwise combination
dispersal_cutoff <- 0.999 ### 99.9% cut off
buffer_cutoff <-
  round(log(1 / (1 - dispersal_cutoff)) / (log(1 / percentage_dispersers) /
                                             dispersal_distance), digits = 2)

# test & plot of dispersal contribution for sequence of distance up to buffer_cutoff
test <-
  data.frame(distance = (seq(0, buffer_cutoff, by = 0.5))) %>%
  mutate(contribution = (exp(dispersal_contribution * distance) * 100))

ggplot(data = test, aes(x = distance, y = contribution, group = 1)) +
  geom_line() +
  geom_point() +
  geom_vline(xintercept = buffer_cutoff, color = "red")

#### CALCULATE CONNECTIVITY ####

# loop through list #
for (i in 1:nrow(hab_patches)) {
  
  # id single patch to measure from
  focal_patch <- hab_patches[i,]
  
  # id patches to measure to
  # buffer from slected focal patch by bufferDistnace
  focal_patch_buffer <- st_buffer(focal_patch, buffer_cutoff)
  # select source patches within buffer distance of focal patch
  source_patch <- st_filter(hab_patches, focal_patch_buffer, .predicate = st_intersects)
  # calculate the distances from all the source patches to the focal patch
  patch_dist <- st_distance(focal_patch, source_patch)
  patch_dist <- as.vector(patch_dist)
  # create a data frame with all information in
  Conn_table_site <- data.frame(focal_patch = focal_patch$patch_ID, 
                                focal_patch_area = as.numeric(focal_patch$patch_area),
                                source_patch = source_patch$patch_ID, 
                                source_patch_area = as.numeric(source_patch$patch_area),
                                distance = patch_dist) %>% 
    mutate(incoming_connect = case_when(focal_patch == source_patch ~ NA_real_,
                                        TRUE ~ source_patch_area * exp(dispersal_contribution*distance)))
  # add all points together
  if(i == 1) {
    Connectivity_table = Conn_table_site
  } else {
    Connectivity_table = rbind(Connectivity_table, Conn_table_site)
  }
}      

# the 'incoming_connect' variable in the 'connectivity_table' shows the connectivity from the various
# 'source patches' to each 'focal patch' - yon can sum by 'focal patch'

```

```{r}
#Import polygon dataset

#This is the NFI and LCM 2015 woodlands joined together
#Converted to polygons from a raster, hence the pixelated edges

hab_patches_all <- st_read(here("data/derived-data/nfi_lcm_overlaid_shapefile_woods_export.shp"))

head(hab_patches_all)

hab_patches_all <- hab_patches_all %>%
  rename(patch_ID = Id) %>%
  rename(patch_area = Shape_Area)

#Crop these habitat patches to England and Wales only ####

ew_10k <- st_read(here("data/raw-data/10k_tiles_EW.shp"))

#crop hab_patches to England and Wales without clipping the edges of the woodlands

hab_patches <-st_filter(hab_patches_all, ew_10k, .predicate =st_intersects)

plot(st_geometry(hab_patches))
```

```{r}
#### SET CONNECTIVITY PARAMETERS ####
# connectivity parametetrs - % of dispersers reaching a set distance #
percentage_dispersers <- 0.05 ### 5%
dispersal_distance <- 414 #area of a 1km radius circle
dispersal_contribution <-
  -((log(1 / percentage_dispersers)) / dispersal_distance)

# Buffer distance represents the cut off - this stops the script measuring every pairwise combination
dispersal_cutoff <- 0.999 ### 99.9% cut off
buffer_cutoff <-
  round(log(1 / (1 - dispersal_cutoff)) / (log(1 / percentage_dispersers) /
                                             dispersal_distance), digits = 0)

# test & plot of dispersal contribution for sequence of distance up to buffer_cutoff
test <-
  data.frame(distance = (seq(0, buffer_cutoff, by = 0.5))) %>%
  mutate(contribution = (exp(dispersal_contribution * distance) * 100))

ggplot(data = test, aes(x = distance, y = contribution, group = 1)) +
  geom_line() +
  geom_point() +
  geom_vline(xintercept = buffer_cutoff, color = "red")

#See how buffer size looks
#We probably want a 1km buffer
#A 1km radius circle has an area of 3.14×10^6 m2 or 3.14 square kilometres
focal_patch_buffer <- st_buffer(hab_patches[92,], buffer_cutoff)
# Calculate the area
st_area(focal_patch_buffer$geometry) # square metres
#3147177 [m^2]
as.numeric(st_area(focal_patch_buffer$geometry)) / 1e6 # square kilometres
# 3.147177
plot(st_geometry(focal_patch_buffer))
plot(st_geometry(hab_patches[92,]),add=TRUE)


```

```{r}

#### CALCULATE CONNECTIVITY ####

#work out which patches have not been done yet

hab_patches_to_do <- anti_join(
  hab_patches,
  connectivity_all,
  by = c("patch_ID" = "focal_patch")  # Matching based on `patch_ID` in `hab_patches` and `focal_patch` in `connectivity_all`
)

num_patches <- nrow(hab_patches_to_do)

# Initialize progress bar
pb <- progress_bar$new(
  format = "[:bar] :current/:total (:percent) in :elapsed, eta: :eta",
  total = num_patches,
  clear = FALSE,   # Keep the progress bar on the screen
  width = 60
)

# loop through list #
for (i in 1:nrow(hab_patches_to_do)) {
  
   # Update progress bar
  pb$tick()  # This moves the progress bar
  
  # id single patch to measure from
  focal_patch <- hab_patches[i,]
  
  # id patches to measure to
  # buffer from slected focal patch by bufferDistnace
  focal_patch_buffer <- st_buffer(focal_patch, buffer_cutoff)
  # select source patches within buffer distance of focal patch
  source_patch <- st_filter(hab_patches, focal_patch_buffer, .predicate = st_intersects)
  
  # calculate the distances from all the source patches to the focal patch
  patch_dist <- st_distance(focal_patch, source_patch)
  patch_dist <- as.vector(patch_dist)
  # create a data frame with all information in
  Conn_table_site <- data.frame(focal_patch = focal_patch$patch_ID, 
                                focal_patch_area = as.numeric(focal_patch$patch_area),
                                source_patch = source_patch$patch_ID, 
                                source_patch_area = as.numeric(source_patch$patch_area),
                                distance = patch_dist) %>% 
    mutate(incoming_connect = case_when(focal_patch == source_patch ~ NA_real_,
                                        TRUE ~ source_patch_area * exp(dispersal_contribution*distance)))
  # add all points together
  if(i == 1) {
    Connectivity_table = Conn_table_site
  } else {
    Connectivity_table = rbind(Connectivity_table, Conn_table_site)
  }
}      

# the 'incoming_connect' variable in the 'connectivity_table' shows the connectivity from the various
# 'source patches' to each 'focal patch' - yon can sum by 'focal patch'
```

```{r}
#Save connectivity table

#saveRDS(Connectivity_table, here("output/intermediate-outputs/connectivity_nfi_lcm_2015_patches_3908_23055.rds"))
connectivity1 <- readRDS(here("output/intermediate-outputs/connectivity_nfi_lcm_2015_patches_1_1048.rds"))
connectivity2 <- readRDS(here("output/intermediate-outputs/connectivity_nfi_lcm_2015_patches_1049_2859.rds"))
connectivity3 <- readRDS(here("output/intermediate-outputs/connectivity_nfi_lcm_2015_patches_3908_23055.rds"))
#Merge tables

connectivity_all <- rbind(connectivity1, connectivity2, connectivity3)

#Add geometry in from hab_patches
connectivity_all <- dplyr::left_join(connectivity_all, hab_patches, by = c("focal_patch"="patch_ID"))

```

```{r}
#Plot incoming connectivity as a function of Euclidean distance ####

#Filter Connectivity table for NAs

#remove NA's from table
Connectivity_table_filt <- connectivity_all %>%
  filter(!is.na(incoming_connect))
Connectivity_table_filt <- Connectivity_table_filt %>% distinct()

#sum incoming connectivity by focal patch
incoming_connectivity_sum <- Connectivity_table_filt %>%
  dplyr::select(focal_patch, incoming_connect) %>%
  group_by(focal_patch) %>%
  dplyr::summarise(total_connect = sum(incoming_connect),
            n = n())

hist(incoming_connectivity_sum$total_connect)

#log transform the incoming connectivity
incoming_connectivity_sum$total_connect_log <- log(
  incoming_connectivity_sum$total_connect
)

hist(incoming_connectivity_sum$total_connect_log)

#Add geometry
incoming_connectivity_sum$geometry<-hab_patches$geometry[match(incoming_connectivity_sum$focal_patch, hab_patches$patch_ID)]

#Plot incoming connectivity

#give the details for how to save the figure - change the width and height to reflect the shape of your figure (long/tall/square…) – I try to keep at least either the width or the height between 3000-3400 – I keep res at 500
#jpeg("Figures/incoming_connectivity_SE27_nfi_point_dist.jpeg", width = 3400, height = 1200, units = "px", #res = 500)  

incoming_connectivity_sum <- st_as_sf(incoming_connectivity_sum)

ggplot(data = incoming_connectivity_sum$geometry) +
  geom_sf(aes(fill = (incoming_connectivity_sum$total_connect_log)), size = 0.2) +
  scale_fill_viridis_c(option = "inferno", name = "Log Incoming Connectivity")

#dev.off()
```
