## Make index rasters for England-Wales that can be used to produce maps for expert interviews

```{r}
#| label: Load packages

library(raster)
library(sf)
library(plyr); library(dplyr)
library(terra)
library(progress)
```

```{r}
#| label: Read in spatial layers

bng <- "EPSG:27700"

#GB land cover map
lcm <- raster("C:/Users/ik929086/Documents/iDeer/data/raw-data/lcm-2023/gblcm2023_25m.tif")

#Read in large deer predicted indices with point geometry
#df_sf <- readRDS("C:/Users/ik929086/Documents/iDeer/output/large_deer_full_df_cat_point_geometry_wood_edge_arable_combo.RDS")
df_sf <- readRDS(df_sf <- readRDS("C:/Users/ik929086/Documents/iDeer/output/intermediate-outputs/NFI_2023_large_deer_impact_risk_sf_V2.rds")
)

unique(df_sf$pred_thermoreg)
unique(df_sf$pred_attraction_index)
unique(df_sf$pred_connect)
unique(df_sf$pred_disturb)
```

```{r}
#| label: Make a STARS template for rasterizing indices
#Convert the RasterLayer to a stars object
stars_template <- stars::st_as_stars(lcm)
```

```{r}
#| label: Make England-Wales connectivity index raster

 # Define the value mapping for pred_connect
connect_values <- c("Low" = 1, "Medium" = 2, "High" = 3)
df_sf$pred_connect <- connect_values[df_sf$pred_connect]

# Select geometry and value column
connect_sf <- df_sf %>% dplyr::select(geometry, pred_connect)

 #make a stars template
 # Use the template raster for extent, resolution, and CRS
 connect_r <- stars::st_rasterize(sf = connect_sf, template = stars_template)
 #connect_rast <- terra::rast(connect_r)
 
# stars::write_stars(connect_r, "C:/Users/ik929086/Documents/BBN_CPT_elicitation/output/large_deer_predicted_connectivity_EW.tif",overwrite=TRUE)
 
 stars::write_stars(connect_r, "C:/Users/ik929086/Documents/BBN_CPT_elicitation/output/large_deer_predicted_connectivity_EW.tif",overwrite=TRUE)
```

```{r}
#| label: Make England-Wales raster for thermoreg index 

# Define the value mapping for pred_connect
 thermoreg_values <- c("Low" = 1, "Medium" = 2, "High" = 3)
 df_sf$pred_thermoreg <- thermoreg_values[df_sf$pred_thermoreg]

 #Convert to raster
 # Select the geometry and value column
 thermoreg_sf <- df_sf %>% dplyr::select(geometry, pred_thermoreg)
 
 # Use the template raster for extent, resolution, and CRS
thermoreg_r <- stars::st_rasterize(sf = thermoreg_sf, template = stars_template)
 #thermoreg_rast <- terra::rast(thermoreg_r)
 
 #Finally, crop the raster to the England-Wales shapefile
 #thermoreg_rast_EW <- crop(thermoreg_rast, EW)
 #thermoreg_rast_EW <- mask(thermoreg_rast_EW, EW)
 
 stars::write_stars(thermoreg_r, "C:/Users/ik929086/Documents/BBN_CPT_elicitation/output/large_deer_thermoreg_index_raster_wood_area_EW.tif",overwrite=TRUE)
```

```{r}
#| label: Make England-Wales raster for attraction index

# Define the value mapping for pred_connect
 attraction_index_values <- c("Low" = 1, "Medium" = 2, "High" = 3)
 df_sf$pred_attraction_index <- attraction_index_values[df_sf$pred_attraction_index]

 #Convert to raster
 # Select the geometry and value column
 attraction_index_sf <- df_sf %>% dplyr::select(geometry, pred_attraction_index)
 
 # Use the template raster for extent, resolution, and CRS
attraction_index_r <- stars::st_rasterize(sf = attraction_index_sf, template = stars_template)
#attraction_index_rast <- terra::rast(attraction_index_r)
 
 #Finally, crop the raster to the England-Wales shapefile
 #attraction_index_rast_EW <- crop(attraction_index_rast, EW)
 #attraction_index_rast_EW <- mask(attraction_index_rast_EW, EW)
 
 stars::write_stars(attraction_index_r, "C:/Users/ik929086/Documents/BBN_CPT_elicitation/output/large_deer_attraction_index_raster_EW.tif",overwrite=TRUE)
```

```{r}
#| label: Make England-Wales raster for disturbance index

# Define the value mapping for pred_connect
 disturb_values <- c("Low" = 1, "Medium" = 2, "High" = 3)
 df_sf$pred_disturb_vals <- disturb_values[df_sf$pred_disturb]

 #Convert to raster
 # Select the geometry and value column
 disturb_sf <- df_sf %>% dplyr::select(geometry, pred_disturb_vals)
 
 # Use the template raster for extent, resolution, and CRS
disturb_r <- stars::st_rasterize(sf = disturb_sf, template = stars_template)
#attraction_index_rast <- terra::rast(attraction_index_r)
 
 #Finally, crop the raster to the England-Wales shapefile
 #attraction_index_rast_EW <- crop(attraction_index_rast, EW)
 #attraction_index_rast_EW <- mask(attraction_index_rast_EW, EW)
 
 stars::write_stars(disturb_r, "C:/Users/ik929086/Documents/BBN_CPT_elicitation/output/large_deer_urban_distance_index_raster_EW.tif",overwrite=TRUE)
```
