```{r}
#Panel figure for iDeer risk maps ------------########

#Make alluvial plots using the conditional probability tables from the iDeer models

library(raster)
library(sf)
library(ggplot2)
library(ggalluvial)
library(knitr)
library(raster)
library(viridisLite)
library(leaflet)
library(stars)

```

```{r Load in CPTs}

#Large deer CPTs ####
#Attraction index
large_attraction_cpt_df <- read.csv("C:/Users/ik929086/OneDrive - University of Southampton/iDeer_Manuscripts/iDeer_Tool/Supplementary Info/Code/cpt-figures/Large_Deer_Attraction_Index_CPT.csv")
#Thermoregulation Index
large_thermoreg_cpt_df <- read.csv("C:/Users/ik929086/OneDrive - University of Southampton/iDeer_Manuscripts/iDeer_Tool/Supplementary Info/CPTs/Large_Deer_Thermoreg_Index_CPT_post_interviews.csv")
#woodland food value index
large_wood_food_value_cpt_df <- read.csv("C:/Users/ik929086/OneDrive - University of Southampton/iDeer_Manuscripts/iDeer_Tool/Supplementary Info/CPTs/Largedeer_Woodland_food_value_Index_two_levels.csv")
#Large deer impact risk
large_risk_cpt_df <- read.csv("C:/Users/ik929086/OneDrive - University of Southampton/iDeer_Manuscripts/iDeer_Tool/Supplementary Info/CPTs/Large_Deer_Damage_Risk_CPT_post_interviews.csv")

#Small deer CPTs ####
#Connectivity
small_connectivity_cpt_df <- read.csv("C:/Users/ik929086/OneDrive - University of Southampton/iDeer_Manuscripts/iDeer_Tool/Supplementary Info/CPTs/Small_Deer_Connectivity_Index_CPT_post_interviews.csv")
#Attraction index
small_attraction_cpt_df <- read.csv("C:/Users/ik929086/OneDrive - University of Southampton/iDeer_Manuscripts/iDeer_Tool/Supplementary Info/CPTs/Smalldeer_Attraction_Index_Woodland_edge_cover_400m_Amy.csv")
#small deer damage risk
small_risk_cpt_df_full <- read.csv("C:/Users/ik929086/OneDrive - University of Southampton/iDeer_Manuscripts/iDeer_Tool/Supplementary Info/CPTs/Small_Deer_Damage_Risk_CPT_post_interviews.csv")
#woodland food value index
small_wood_food_value_cpt_df <- read.csv("C:/Users/ik929086/OneDrive - University of Southampton/iDeer_Manuscripts/iDeer_Tool/Supplementary Info/CPTs/Smalldeer_Woodland_food_value_Index.csv")

```

```{r}
# Load knitr for neat table printing
library(knitr)

# Large deer CPT importance values ----
large_deer_themoreg <- c(MAX_DAMS_1000m = 1, woodland_shelter_value = 0.2)
large_deer_attraction <- c(Woodland_edge_cover_1000m = 0.1, 
                           Arable_cover_1000m = 1, 
                           Perennial_cover_1000m = 1)
large_deer_woodland_value <- c(Woodland_palatability = 1)
large_deer_impact_risk <- c(Woodland_Value_Index = 0.3, 
                            Attraction_Index = 1, 
                            Thermoregulation_Index = 0.2)

# Combine large deer variables and values into a data frame
large_deer_table <- data.frame(
  Variable = c(names(large_deer_themoreg),
               names(large_deer_attraction),
               names(large_deer_woodland_value),
               names(large_deer_impact_risk)),
  Importance_Value = c(large_deer_themoreg,
                       large_deer_attraction,
                       large_deer_woodland_value,
                       large_deer_impact_risk)
)

# Display Large deer table
kable(large_deer_table, caption = "Large Deer CPT Importance Values")

# Small deer CPT importance values ----
small_deer_connectivity <- c(Woodland_cover_400m = 1, LF_cover_400m = 0.6)
small_deer_attraction <- c(Woodland_edge_cover = 1)
small_deer_woodland_value <- c(Woodland_palatability = 1)
small_deer_impact_risk <- c(Connectivity_Index = 0.2, 
                            Attraction_Index = 0.5, 
                            Woodland_Food_Value_Index = 0.8)

# Combine small deer variables and values into a data frame
small_deer_table <- data.frame(
  Variable = c(names(small_deer_connectivity),
               names(small_deer_attraction),
               names(small_deer_woodland_value),
               names(small_deer_impact_risk)),
  Importance_Value = c(small_deer_connectivity,
                       small_deer_attraction,
                       small_deer_woodland_value,
                       small_deer_impact_risk)
)

# Display Small deer table
kable(small_deer_table, caption = "Small Deer CPT Importance Values")

```


```{r}
large_deer_alluvial <- data.frame(
  Variable = c("MAX_DAMS_1000m", "woodland_shelter_value",
               "Woodland_edge_cover_1000m", "Arable_cover_1000m", "Perennial_cover_1000m",
               "Woodland_palatability"),
  Index = c("Thermoregulation_Index", "Thermoregulation_Index",
            "Attraction_Index", "Attraction_Index", "Attraction_Index",
            "Woodland_Value_Index"),
  Importance_Value = c(1, 0.2, 0.1, 1, 1, 1)
)

large_deer_impact_risk <- c(
  Woodland_Value_Index = 0.3,
  Attraction_Index = 1,
  Thermoregulation_Index = 0.2
)

# Add Impact risk weight to each record via matching Index
large_deer_alluvial <- large_deer_alluvial %>%
  mutate(Impact_Risk = "Impact Risk",
         Impact_Importance = large_deer_impact_risk[Index])

# Calculate final flow value for each alluvium
large_deer_alluvial <- large_deer_alluvial %>%
  mutate(Flow_Value = Importance_Value * Impact_Importance)

# Check data
large_deer_alluvial


# Build proportional weighted alluvial plot
large_deer_alluvial_template <- ggplot(large_deer_alluvial,
       aes(axis1 = Variable, axis2 = Index, axis3 = Impact_Risk,
           y = Flow_Value)) +
  geom_alluvium(aes(fill = Index), width = 0.2, alpha = 0.6) +
  geom_stratum(width = 0.3, fill = "white", color = "black") +
  scale_x_discrete(limits = c("Variable", "Index", "Impact Risk"), expand = c(.05, .05)) +
  theme_minimal() +
  theme(
    #legend.position = "none",
    axis.title = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  ) +
  ggtitle("Large Deer CPT Alluvial Plot (weighted)") +
  ylab("Importance Value") +
  xlab("")

large_deer_alluvial_template

ggsave("C:/Users/ik929086/Documents/iDeer/output/plots/large_deer_alluvial_template.pdf", plot = large_deer_alluvial_template, width = 6, height = 4)



```

```{r}
library(ggplot2)
library(ggalluvial)
library(dplyr)

# Small deer variable to index mapping
small_deer_alluvial <- data.frame(
  Variable = c("Woodland_cover_400m", "LF_cover_400m",
               "Woodland_edge_cover", "Woodland_palatability"),
  Index = c("Connectivity_Index", "Connectivity_Index",
            "Attraction_Index", "Woodland_Value_Index"),
  Importance_Value = c(1, 0.6, 1, 1)
)

# Impact risk values for each index
small_deer_impact_risk <- c(Connectivity_Index = 0.2, 
                            Attraction_Index = 0.5, 
                            Woodland_Value_Index = 0.8)  # used consistent name

# Merge Impact Risk values into the data frame by matching on Index
small_deer_alluvial <- small_deer_alluvial %>%
  mutate(Impact_Risk = "Impact Risk",
         Impact_Importance = small_deer_impact_risk[Index])

# Final combined Importance Value (variable to index to impact risk flow)
small_deer_alluvial <- small_deer_alluvial %>%
  mutate(Flow_Value = Importance_Value * Impact_Importance)

# Inspect structure
small_deer_alluvial

# Build weighted alluvial plot
small_deer_alluvial_template <- ggplot(small_deer_alluvial,
       aes(axis1 = Variable, axis2 = Index, axis3 = Impact_Risk,
           y = Flow_Value)) +
  geom_alluvium(aes(fill = Index), width = 0.2, alpha = 0.6) +
  geom_stratum(width = 0.3, fill = "white", color = "black") +
  scale_x_discrete(limits = c("Variable", "Index", "Impact Risk"), expand = c(.05, .05)) +
  theme_minimal() +
  theme(
    #legend.position = "none",
    axis.title = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  ) +
  ggtitle("Small Deer CPT Alluvial Plot (weighted)") +
  ylab("Importance Value") +
  xlab("")

ggsave("C:/Users/ik929086/Documents/iDeer/output/plots/small_deer_alluvial_template.pdf", plot = small_deer_alluvial_template, width = 6, height = 4)


```

```{r}
#Save raster tiles to be used in the figure

#Read in rasters for variables
#large deer
max_dams <- raster("C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023/large_deer/polys_unmerged_max_summed_DAMS_raster_normalised.tif")
shelter_quality <- raster("C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023/large_deer/NFI_woodland_shelter_value_index_large_deer.tif")
arable_cover <- raster("C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023//large_deer/percentage_cover_arable_1000_2023.tif")
perennial_cover <- raster("C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023/large_deer/percentage_cover_perennial_1000m_2023.tif")
wood_value_large_deer <- raster("C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023/large_deer/NFI_woodland_food_value_index_large_deer_two_levels.tif")
wood_edges_1000m <- raster("C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023/large_deer/NFI_focal_woodland_edge_area_1000m_percentage_cover.tif")

#small deer
LF_cover <- raster("C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023/small_deer/NFI_mean_percentage_focal_area_lf_extracted_to_polys_400m.tif")
wood_value_small_deer <- raster("C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023/small_deer/NFI_woodland_food_value_index_small_deer_bng.tif")
wood_edges_400m <- raster("C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023/small_deer/NFI_focal_woodland_edge_area_400m_percentage_cover.tif")
wood_area_400m <- raster("C:/Users/ik929086/Documents/iDeer/output/GB_datasets_2023/small_deer/NFI_mean_percentage_focal_area_woods_extracted_to_polys_400m.tif")



#Make a 5x5km tile around point 50.477566, -4.847737 (Cornwall)
#crop all rasters to this tile
# Define the center point (longitude, latitude)
center_point <- SpatialPoints(matrix(c(-4.847737, 50.477566), ncol=2), 
                              proj4string=CRS("+proj=longlat +datum=WGS84"))

# Transform to same CRS as rasters (assuming all rasters have same CRS)
target_crs <- crs(max_dams)
center_point_proj <- spTransform(center_point, target_crs)

# Define a 5x5 km extent (2500 m in each direction from the center)
buffer_size <- 2500  # in meters
x_center <- coordinates(center_point_proj)[1]
y_center <- coordinates(center_point_proj)[2]

# Create extent object
tile_extent <- extent(x_center - buffer_size, x_center + buffer_size,
                      y_center - buffer_size, y_center + buffer_size)

# Crop all rasters to this extent
max_dams_crop <- crop(max_dams, tile_extent)
#make non-values in raster NAs
#non-values were assigned -0.02747456 in normalisation process
max_dams_crop[max_dams_crop <= -0.02747456] <- NA
shelter_quality_crop <- crop(shelter_quality, tile_extent)
arable_cover_crop <- crop(arable_cover, tile_extent)
perennial_cover_crop <- crop(perennial_cover, tile_extent)
wood_value_large_deer_crop <- crop(wood_value_large_deer, tile_extent)
wood_edges_1000m_crop <- crop(wood_edges_1000m, tile_extent)

LF_crop <- crop(LF_cover, tile_extent)
wood_edges_400m_crop <- crop(wood_edges_400m, tile_extent)
crs(wood_edges_400m_crop) <- 27700
wood_value_small_deer_crop <- crop(wood_value_small_deer, tile_extent)
wood_area_crop <- crop(wood_area_400m, tile_extent)
crs(wood_area_crop) <- 27700

# Optionally: stack them together for joint operations
large_deer_raster_stack <- stack(max_dams_crop, shelter_quality_crop, arable_cover_crop, 
                      perennial_cover_crop, wood_value_large_deer_crop, wood_edges_1000m_crop)

small_deer_raster_stack <- stack(LF_crop, wood_edges_400m_crop, wood_value_small_deer_crop, wood_area_crop)

# Plot to check
plot(large_deer_raster_stack)
plot(small_deer_raster_stack)

# Define custom colour palette
custom_palette <- colorRampPalette(c("#354A9A", "#6EA6CD", "#FEDA8B", "#F67E4B", "#A50026"))

# Define file paths for each raster plot
output_dir <- "C:/Users/ik929086/Documents/iDeer/output/plots/"

# List of rasters and corresponding filenames
raster_list <- list(
  max_dams_crop = max_dams_crop,
  shelter_quality_crop = shelter_quality_crop,
  arable_cover_crop = arable_cover_crop,
  perennial_cover_crop = perennial_cover_crop,
  wood_value_large_deer_crop = wood_value_large_deer_crop,
  wood_value_small_deer_crop = wood_value_small_deer_crop,
  wood_edges_400m_crop = wood_edges_400m_crop,
  wood_edges_1000m_crop = wood_edges_1000m_crop,
  wood_area_crop = wood_area_crop,
  LF_crop = LF_crop
)

# --- Define your custom colour palette ---

# Base colors
col_wood_value <- "#619cff"
col_attraction <- "#f8766d"
col_connectivity <- "#00ba38"
col_thermoreg <- "#00ba38"

# Function to darken base colors
darken_color <- function(col, amount = 0.2) {
  colorspace::darken(col, amount = amount)
}

# Pale yellow starting color for all palettes
yellow_start <- "#FFFF99"  # pale yellow

# Create palettes transitioning from yellow to the darkened base color
custom_palette_wood_value <- colorRampPalette(c(yellow_start, darken_color(col_wood_value)))
custom_palette_attraction <- colorRampPalette(c(yellow_start, darken_color(col_attraction)))
custom_palette_connectivity <- colorRampPalette(c(yellow_start, darken_color(col_connectivity)))
custom_palette_thermoreg <- colorRampPalette(c(yellow_start, darken_color(col_thermoreg)))

#create lookup table for maps
name_map <- c(
  "polys_unmerged_max_summed_DAMS_raster_normalised" = "MAX_DAMS_1000m",
  "NFI_woodland_shelter_value_index_large_deer" = "woodland_shelter_value",
  "NFI_focal_woodland_edge_area_1000m_percentage_cover"="Woodland_edge_cover_1000m" ,
 "percentage_cover_arable_1000_2023" = "Arable_cover_1000m",
 "percentage_cover_perennial_1000m_2023" = "Perennial_cover_1000m",
  "NFI_woodland_food_value_index_large_deer_two_levels" = "Woodland_palatability",
 "NFI_mean_percentage_focal_area_lf_extracted_to_polys_400m" = "LF_cover_400m",
 "NFI_focal_woodland_edge_area_400m_percentage_cover" =  "Woodland_edge_cover",
 "NFI_woodland_food_value_index_small_deer_bng" = "Woodland_palatability",
 "NFI_mean_percentage_focal_area_woods_extracted_to_polys_400m" = "Woodland_cover_400m" 
  )

save_stack_as_individual_pdfs <- function(raster_stack, prefix, var_to_index_df) {
  
  # Map index to palette functions
  palette_map <- list(
    "Thermoregulation_Index" = custom_palette_thermoreg,
    "Woodland_Value_Index" = custom_palette_wood_value,
    "Attraction_Index" = custom_palette_attraction,
    "Connectivity_Index" = custom_palette_connectivity
  )
  
  for (i in 1:nlayers(raster_stack)) {
    layer_name <- names(raster_stack)[i]
    pdf_filename <- paste0(prefix, "_", gsub(" ", "_", tolower(layer_name)), ".pdf")
    
    # Look up the index group for the layer_name
    mapped_name <- name_map[[layer_name]]
    index_group <- var_to_index_df$Index[match(mapped_name, var_to_index_df$Variable)]
    
    # Get the palette function from palette_map; fallback to grayscale palette if not found
    pal_fun <- palette_map[[index_group]]
    if (is.null(pal_fun)) {
      pal_fun <- colorRampPalette(c("white", "black"))
    }
    
    pdf(file.path(output_dir, pdf_filename), width = 7, height = 7)
    plot(raster_stack[[i]],
         main = layer_name,
         col = pal_fun(100),
         legend = TRUE)
    dev.off()
  }
}

# Save large deer cropped stack — individual PDFs
save_stack_as_individual_pdfs(large_deer_raster_stack, "large_deer", large_deer_alluvial)

# Save small deer cropped stack — individual PDFs
save_stack_as_individual_pdfs(small_deer_raster_stack, "small_deer", small_deer_alluvial)
```


```{r Function that saves plots with underlying basemap}

library(terra)    # for SpatRaster
library(ggplot2)
library(rosm)
library(sf)

 # Convert to Web Mercator (EPSG:3857)
crs_mercator <- "EPSG:3857"
raster_layer <- terra::rast(small_deer_raster_stack[[1]])
raster_mercator <- terra::project(raster_layer, crs_mercator)
# Get bounding box of the sf object
bbox_merc <- st_bbox(raster_mercator)
# Fetch OpenStreetMap tiles for the bounding box region
map_tiles <- get_tiles(bbox_merc, provider = "Esri.WorldTopoMap", zoom = 15)

save_stack_as_individual_pdfs <- function(raster_stack, prefix, var_to_index_df, bbox_merc, crs_mercator, output_dir) {
  
  # Map index to palette functions
  palette_map <- list(
    "Thermoregulation_Index" = custom_palette_thermoreg,
    "Woodland_Value_Index" = custom_palette_wood_value,
    "Attraction_Index" = custom_palette_attraction,
    "Connectivity_Index" = custom_palette_connectivity
  )
  
  # Fetch OSM tiles once
  map_tiles <- get_tiles(bbox_merc, provider = "Esri.WorldTopoMap", zoom = 15)
  
  for (i in 1:nlayers(raster_stack)) {
    layer_name <- names(raster_stack)[i]
    pdf_filename <- paste0(prefix, "_", gsub(" ", "_", tolower(layer_name)), ".pdf")
    
    mapped_name <- if (exists("name_map") && !is.null(name_map[[layer_name]])) name_map[[layer_name]] else layer_name
    index_group <- var_to_index_df$Index[match(mapped_name, var_to_index_df$Variable)]
    pal_fun <- palette_map[[index_group]]
    if (is.null(pal_fun)) pal_fun <- colorRampPalette(c("white", "black"))
    
    # Convert to SpatRaster and project
    raster_layer <- terra::rast(raster_stack[[i]])
    raster_layer_proj <- terra::project(raster_layer, crs_mercator)
    
    # Crop to bounding box of base map (bbox_merc)
    bbox_spat <- terra::ext(c(bbox_merc["xmin"], bbox_merc["xmax"], bbox_merc["ymin"], bbox_merc["ymax"]))
    raster_layer_proj_crop <- terra::crop(raster_layer_proj, bbox_spat)
    
    # For aes(fill=...), the name should correspond to the raster layer's layer name after projection
    # After terra::project, layer name might be lost or changed, so let's assign a generic name:
    names(raster_layer_proj_crop) <- "value"
    
    # Create extent polygon as sf for outlining
extent_sf <- st_as_sfc(st_bbox(raster_layer_proj_crop))
st_crs(extent_sf) <- crs(raster_layer_proj_crop)
    
    pdf(file.path(output_dir, pdf_filename), width = 7, height = 7)
    
     p <- ggplot() +
      geom_spatraster_rgb(data = map_tiles) +
      geom_spatraster(data = raster_layer_proj_crop, aes(fill = value)) +
      scale_fill_gradientn(colors = pal_fun(100), na.value = "transparent", name = layer_name) +
      geom_sf(data = extent_sf, fill = NA, color = "black", size = 0.3) +  # thin black outline
      coord_sf(crs = crs_mercator, 
               xlim = c(bbox_merc["xmin"], bbox_merc["xmax"]), 
               ylim = c(bbox_merc["ymin"], bbox_merc["ymax"])) +
      labs(title = layer_name, fill = layer_name) +
      theme_minimal()

    print(p)
    
    dev.off()
  }
}

save_stack_as_individual_pdfs(
  raster_stack = large_deer_raster_stack,
  prefix = "large_deer",
  var_to_index_df = large_deer_alluvial,
  bbox_merc = bbox_merc,
  crs_mercator = crs_mercator,
  output_dir = output_dir
)

save_stack_as_individual_pdfs(
  raster_stack = small_deer_raster_stack,
  prefix = "small_deer",
  var_to_index_df = small_deer_alluvial,
  bbox_merc = bbox_merc,
  crs_mercator = crs_mercator,
  output_dir = output_dir
)

```

```{r Save index tiles to be used in figure}

#large deer
thermoreg_index <- raster("C:/Users/ik929086/Documents/iDeer/output/Index_maps/large_deer_predicted_thermoreg_index_EW.tif")
wood_value_large_deer_index <- raster("C:/Users/ik929086/Documents/iDeer/output/Index_maps/large_deer_predicted_wood_palatability_EW.tif")
large_deer_attraction_index <- raster("C:/Users/ik929086/Documents/iDeer/output/Index_maps/large_deer_predicted_attraction_index_EW.tif")

#small deer
connectivity_index <- raster("C:/Users/ik929086/Documents/iDeer/output/Index_maps/small_deer_predicted_connectivity_EW.tif")
wood_value_small_deer_index <- raster("C:/Users/ik929086/Documents/iDeer/output/Index_maps/small_deer_predicted_wood_palatability_EW.tif")
small_deer_attraction_index <- raster("C:/Users/ik929086/Documents/iDeer/output/Index_maps/small_deer_attraction_index_EW.tif")

# --- Define the center point and tile extent ---

center_point <- SpatialPoints(matrix(c(-4.847737, 50.477566), ncol=2), 
                              proj4string=CRS("+proj=longlat +datum=WGS84"))

# Assuming all rasters have the same CRS as max_dams (modify if different)
target_crs <- crs(max_dams)
center_point_proj <- spTransform(center_point, target_crs)

buffer_size <- 2500  # 5km tile radius (meters)
x_center <- coordinates(center_point_proj)[1]
y_center <- coordinates(center_point_proj)[2]

tile_extent <- extent(x_center - buffer_size, x_center + buffer_size,
                      y_center - buffer_size, y_center + buffer_size)

# --- Crop rasters to extent ---

large_deer_indices_stack <- stack(
  crop(thermoreg_index, tile_extent),
  crop(wood_value_large_deer_index, tile_extent),
  crop(large_deer_attraction_index, tile_extent)
)
names(large_deer_indices_stack) <- c("Thermoregulation", "Wood Value", "Attraction")

small_deer_indices_stack <- stack(
  crop(connectivity_index, tile_extent),
  crop(wood_value_small_deer_index, tile_extent),
  crop(small_deer_attraction_index, tile_extent)
)
names(small_deer_indices_stack) <- c("Connectivity", "Wood Value", "Attraction")

replace_zeros_with_na <- function(r_stack) {
  for (i in 1:nlayers(r_stack)) {
    r <- r_stack[[i]]
    r[r == 0] <- NA
    r_stack[[i]] <- r
  }
  return(r_stack)
}

large_deer_indices_stack <- replace_zeros_with_na(large_deer_indices_stack)
small_deer_indices_stack <- replace_zeros_with_na(small_deer_indices_stack)

# --- Define your custom colour palette ---

# Function to darken colors (using scales::darken)
darken_color <- function(col, amount = 0.5) {
  colorspace::darken(col, amount = amount)
}

# Base colors
col_wood_value <- "#619cff"
col_attraction <- "#f8766d"
col_connectivity <- "#00ba38"
col_thermoreg <- "#00ba38"

# Custom palettes from base color to darker shade
custom_palette_wood_value <- colorRampPalette(c(col_wood_value, darken_color(col_wood_value)))
custom_palette_attraction <- colorRampPalette(c(col_attraction, darken_color(col_attraction)))
custom_palette_connectivity <- colorRampPalette(c(col_connectivity, darken_color(col_connectivity)))
custom_palette_thermoreg <- colorRampPalette(c(col_thermoreg, darken_color(col_thermoreg)))

# --- Function to save individual raster layers as PDFs with custom colors ---

output_dir <- "C:/Users/ik929086/Documents/iDeer/output/plots/"
if (!dir.exists(output_dir)) dir.create(output_dir)

save_stack_as_individual_pdfs <- function(r_stack, prefix) {
  
  # Define palette mapping by layer name patterns
  palette_map <- list(
    "Thermoregulation" = custom_palette_thermoreg,
    "Wood.Value" = custom_palette_wood_value,
    "Attraction" = custom_palette_attraction,
    "Connectivity" = custom_palette_connectivity
  )
  
   # Fetch OSM basemap tiles for the bbox area
  map_tiles <- get_tiles(bbox_merc, provider = "Esri.WorldTopoMap", zoom = 15)
  
  for (i in 1:nlayers(r_stack)) {
    layer_name <- names(r_stack)[i]
    pdf_filename <- paste0(prefix, "_", gsub(" ", "_", tolower(layer_name)), ".pdf")
    
    # Find palette function that matches layer name
    pal_fun <- NULL
    for (key in names(palette_map)) {
      if (grepl(key, layer_name, ignore.case = TRUE)) {
        pal_fun <- palette_map[[key]]
        break
      }
    }
    if (is.null(pal_fun)) {
      pal_fun <- colorRampPalette(c("white", "black"))  # fallback palette
    }
    
     # Convert to SpatRaster and project to Web Mercator
    raster_layer <- terra::rast(r_stack[[i]])
    raster_layer_proj <- terra::project(raster_layer, crs_mercator)
    
    # Crop to basemap bounding box
    bbox_spat <- terra::ext(c(bbox_merc["xmin"], bbox_merc["xmax"], bbox_merc["ymin"], bbox_merc["ymax"]))
    raster_layer_proj_crop <- terra::crop(raster_layer_proj, bbox_spat)
    names(raster_layer_proj_crop) <- "value"
    
       # Create extent polygon as sf for outlining
extent_sf <- st_as_sfc(st_bbox(raster_layer_proj_crop))
st_crs(extent_sf) <- crs(raster_layer_proj_crop)
    
    # Create and save plot
    pdf(file.path(output_dir, pdf_filename), width = 7, height = 7)
    
    p <- ggplot() +
      geom_spatraster_rgb(data = map_tiles) +
      geom_spatraster(data = raster_layer_proj_crop, aes(fill = value)) +
      scale_fill_gradientn(colors = pal_fun(100), na.value = "transparent", name = layer_name) +
      geom_sf(data = extent_sf, fill = NA, color = "black", size = 0.3) +
      coord_sf(crs = crs_mercator, 
               xlim = c(bbox_merc["xmin"], bbox_merc["xmax"]), 
               ylim = c(bbox_merc["ymin"], bbox_merc["ymax"])) +
      labs(title = layer_name, fill = layer_name) +
      theme_minimal()
    
    print(p)
    dev.off()
  }
}

# --- Save the cropped stacks as individual PDFs ---

save_stack_as_individual_pdfs(large_deer_indices_stack, "large_deer_index")
save_stack_as_individual_pdfs(small_deer_indices_stack, "small_deer_index")

```

```{r}
#Finally, plot and save the risk maps

small_deer_risk_raster <- raster("C:/Users/ik929086/OneDrive - University of Southampton/R_data_transfer/Deer impact EW risk maps/output/NFI_2023_small_deer_impact_risk_EW.tif")

large_deer_risk_raster <- raster("C:/Users/ik929086/OneDrive - University of Southampton/R_data_transfer/Deer impact EW risk maps/output/NFI_2023_large_deer_impact_risk_EW_V2.tif")

# --- Define the center point and tile extent ---

center_point <- SpatialPoints(matrix(c(-4.847737, 50.477566), ncol=2), 
                              proj4string=CRS("+proj=longlat +datum=WGS84"))

# Assuming all rasters have the same CRS as max_dams (modify if different)
target_crs <- crs(max_dams)
center_point_proj <- spTransform(center_point, target_crs)

buffer_size <- 2500  # 5km tile radius (meters)
x_center <- coordinates(center_point_proj)[1]
y_center <- coordinates(center_point_proj)[2]

tile_extent <- extent(x_center - buffer_size, x_center + buffer_size,
                      y_center - buffer_size, y_center + buffer_size)

#crop rasters

small_deer_risk_crop <- crop(small_deer_risk_raster, tile_extent)
small_deer_risk_crop[small_deer_risk_crop <= 0] <- NA

large_deer_risk_crop <- crop(large_deer_risk_raster, tile_extent)

# Plot small deer raster with magma palette
plot(small_deer_risk_crop, 
     col = plasma(100), 
     main = "Small Deer Risk")

# Plot large deer raster with viridis palette
plot(large_deer_risk_crop, 
     col = viridis(100), 
     main = "Large Deer Risk")
```


```{r}
#Plot sf objects

small_deer_risk_sf <- st_read("~/iDeer-tool/data/NFI_2023_small_deer_impact_risk_EW_extraction_V3.gpkg")
large_deer_risk_sf <- st_read("~/iDeer-tool/data/NFI_LCM_2023_large_deer_impact_risk_EW_extraction_V3.gpkg")

small_deer_risk_sf_crop <- st_crop(small_deer_risk_sf, tile_extent)
large_deer_risk_sf_crop <- st_crop(large_deer_risk_sf, tile_extent)

# Plot small deer risk with plasma palette
small_deer_plot <- ggplot() +
  geom_sf(data = small_deer_risk_sf_crop, aes(fill = mean_risk), colour = NA) +
  scale_fill_viridis_c(option = "plasma", na.value = "transparent") +
  theme_void() +
  ggtitle("Small Deer Impact Risk") +
  theme(plot.title = element_text(size = 14, face = "bold"))
small_deer_plot

# Save small deer risk PDF
ggsave("C:/Users/ik929086/Documents/iDeer/output/plots/small_deer_risk_map.pdf", plot = small_deer_plot, width = 6, height = 6)

# Plot large deer risk with viridis palette
large_deer_plot <- ggplot() +
  geom_sf(data = large_deer_risk_sf_crop, aes(fill = mean_risk), colour = NA) +
  scale_fill_viridis_c(option = "viridis", na.value = "transparent") +
  theme_void() +
  ggtitle("Large Deer Impact Risk") +
  theme(plot.title = element_text(size = 14, face = "bold"))

# Save large deer risk PDF
ggsave("C:/Users/ik929086/Documents/iDeer/output/plots/large_deer_risk_map.pdf", plot = large_deer_plot, width = 6, height = 6)

```

```{r}
#Use leaflet to line up with basemaps

library(sf)
library(rosm)
library(ggplot2)
library(dplyr)


 # Convert to Web Mercator (EPSG:3857)
crs_mercator <- "EPSG:3857"
small_sf_mercator <- st_transform(small_deer_risk_sf_crop, crs_mercator)

# Get bounding box of the sf object
bbox_merc <- st_bbox(small_sf_mercator)

# Fetch OpenStreetMap tiles for the bounding box region using rosm
# Define a bounding box extent for rosm
bbox_extent <- as.vector(bbox_merc)  # xmin, ymin, xmax, ymax

# Fetch OpenStreetMap tiles for the bounding box region
map_tiles <- get_tiles(bbox_merc, provider = "OpenStreetMap", zoom = 15)

ggplot() +
  geom_spatraster_rgb(data = map_tiles) +  # OSM tiles base layer
  
  geom_sf(data = small_sf_mercator, 
          aes(fill = mean_risk), 
          color = NA, alpha = 1) +     # polygons filled by mean_risk
  
  scale_fill_viridis_c(option = "plasma") +  # continuous plasma palette
  
  coord_sf(crs = crs_mercator) +
  
  theme_minimal() +
  labs(fill = "Mean Risk")

     
```

