---
title: "Nearest_urban_suburban_feature_per_10k_tile"
author: "Amy Gresham"
date: "2024-02-01"
output: html_document

#Calculate distance to nearest urban or suburban feature for NFI points ####

---

```{r}
library(sf)
library(raster)
library(fasterize)
library(dplyr)
library(here)
library(progress)

#Set project directory
project_dir <- here()

# Set the output directory
output_dir <- here(project_dir, "iDeer_spatial_data", "outputs")
```

```{r}
#Read in spatial layers ####

bng <- 27700

# England and Wales 10k squares
ew10k <- sf::st_read(here("iDeer_spatial_data", "intermediate_outputs", "10k_tiles_EW.shp"))

#nfi/ceh lcm overlaid raster - woodlands only
nfi.lcm.2015 <- raster(here(project_dir,"iDeer_spatial_data","inputs", "nfi_lcm_2015_overlaid_woods_only.tif"))

#original lcm2015 to be used as template raster
# CEH land cover map 2015 raster layer
lcm2015.rast <- raster::raster(here("iDeer_spatial_data", "inputs", "lcm-2015-tif", "lcm2015gb25m.tif"))
lcm2015.rast <- setMinMax(lcm2015.rast)

#make template raster
template_raster <- raster(ext = extent(lcm2015.rast), res = res(lcm2015.rast), crs = bng)

#CEH land cover map 2015 vector layer
lcm2015 <- sf::st_read(here("iDeer_spatial_data", "inputs", "lcm-2015-vector", "LCM2015_GB.gdb"), layer = "LCM2015GBvector")

```

```{r}
#Subset out urban and suburban land parcels from CEH land cover vector map
lcm2015$modal_class <- as.numeric(lcm2015$modal_class)
urban_parcels <- lcm2015 %>% filter(modal_class == 20)
suburban_parcels <- lcm2015 %>% filter(modal_class == 21) # 20 = urban, 21 = suburban
```

```{r}
# NEAREST URBAN FEATURE LOOP ####

#tiles <- ew10k %>% slice(51:nrow(ew10k))

tiles <- ew10k

# Create a progress bar
pb <- progress_bar$new(
  format = "[:bar] :percent Elapsed: :elapsed Time remaining: :eta",
  total = nrow(tiles)
)

# Make empty list to store raster tiles
nearest_urban_list <- list()

for (i in 1:length(tiles$tile_name)) { 
  tile <- tiles[i,]
  chunked.wood <- crop(nfi.lcm.2015, tile)
  chunked.wood[chunked.wood == 0] <- NA #make zeros NAs
  chunked.wood.points <- rasterToPoints(chunked.wood, spatial = TRUE) #Raster to point
  chunked.wood.points <- st_as_sf(chunked.wood.points, crs = bng)
  chunked.wood.points <- sf::st_transform(chunked.wood.points, crs = bng)
  
  if (nrow(chunked.wood.points) > 0) {
  # Find the minimum distance from each point to the nearest urban parcel
  nearest_distances <- st_nearest_feature(chunked.wood.points, urban_parcels, check_crs = TRUE)
  # Extract nearest distances
  nearest <- st_distance(chunked.wood.points, urban_parcels[nearest_distances,], by_element = TRUE)
  # Add to chunked.wood.points
  chunked.wood.points$nearest_urban <- nearest
  # Make template raster
  template_raster <- crop(lcm2015.rast, tile)
  # Rasterize these data
  urban_dist_raster <- rasterize(chunked.wood.points, template_raster, field = "nearest_urban")
  # Save to list
  nearest_urban_list[[i]] <- urban_dist_raster
  
  } else {
    nearest_urban_list[[i]] <- NA
   
  }
  
    pb$tick()  # Increment the progress bar

}

pb$close()  # Close the progress bar

print("Urban raster list complete")

# Save list
saveRDS(nearest_urban_list, file = here("iDeer_spatial_data","intermediate_outputs","nearest_urban_raster_list_nfi_lcm_tiles_51_1740_2015.rds"))
#print("Urban raster list saved")
```


```{r}
#Save nearest urban feature raster

#Read in lists

#urban_1_50 <- readRDS(here("iDeer_spatial_data","intermediate_outputs","nearest_urban_raster_list_nfi_lcm_merged_tiles_1_50_2015.rds"))
#urban_51_1740 <- readRDS(here("iDeer_spatial_data","intermediate_outputs","nearest_urban_raster_list_nfi_lcm_tiles_51_1740_2015.rds"))

#nearest_urban_list <- c(urban_1_50, urban_51_1740)

# Label elements that are not RasterLayers or are empty
valid_urban_rasters <- lapply(nearest_urban_list, function(raster_layer) {
  if (inherits(raster_layer, "RasterLayer") && any(!is.na(values(raster_layer)))) {
    return(raster_layer)
  } else {
    return(NULL)
  }
})

# Remove NULL elements from the list
valid_urban_rasters <- Filter(function(x) !is.null(x), valid_urban_rasters)

# Mosaic raster
urban_distance_mosaic <- do.call(mosaic, c(valid_urban_rasters, fun = mean))

#ensure crs is bng

crs(urban_distance_mosaic) <- bng

# Save raster
writeRaster(urban_distance_mosaic, here(output_dir, "Urban_suburban", "nearest_urban_raster_2015_all_tiles_corrected.tif"))
print("Urban raster mosaic complete and saved")
```

```{r}
# NEAREST SUBURBAN FEATURE LOOP ####

# Create a progress bar
pb <- progress_bar$new(
  format = "[:bar] :percent Elapsed: :elapsed Time remaining: :eta",
  total = nrow(ew10k)
)

tiles <- ew10k

nearest_suburban_list <- list()

for (i in 1:length(tiles$tile_name)) { 
  tile <- tiles[i,]
  chunked.wood <- crop(nfi.lcm.2015, tile)
  chunked.wood[chunked.wood == 0] <- NA #make zeros NAs
  chunked.wood.points <- rasterToPoints(chunked.wood, spatial = TRUE)
  chunked.wood.points <- st_as_sf(chunked.wood.points, crs = bng)
  chunked.wood.points <- sf::st_transform(chunked.wood.points, crs = bng)
    if (nrow(chunked.wood.points) > 0) {
  # Find the minimum distance from each point to the nearest urban parcel
  nearest_distances <- st_nearest_feature(chunked.wood.points, suburban_parcels, check_crs = TRUE)
  # Extract nearest distances
  nearest <- st_distance(chunked.wood.points, suburban_parcels[nearest_distances,], by_element = TRUE)
  # Add to chunked.wood.points
  chunked.wood.points$nearest_suburban <- nearest
  # Make template raster
  template_raster <- crop(lcm2015.rast, tile)
  # Rasterize these data
  suburban_dist_raster <- rasterize(chunked.wood.points, template_raster, field = "nearest_suburban")
  # Save to list
  nearest_suburban_list[[i]] <- suburban_dist_raster
  
  
} else {
    nearest_suburban_list[[i]] <- NA
}

  pb$tick()  # Increment the progress bar

}

pb$close()  # Close the progress bar

print("Suburban raster list complete")

# Save list
saveRDS(nearest_suburban_list, file = here(output_dir, "R tile list backups", "nearest_suburban_raster_list_nfi_lcm_merged_2015.rds"))
print("Suburban raster list saved")
```


```{r}

# Label elements that are not RasterLayers or are empty
valid_suburban_rasters <- lapply(nearest_suburban_list, function(raster_layer) {
  if (inherits(raster_layer, "RasterLayer") && any(!is.na(values(raster_layer)))) {
    return(raster_layer)
  } else {
    return(NULL)
  }
})

# Remove NULL elements from the list
valid_suburban_rasters <- Filter(function(x) !is.null(x), valid_suburban_rasters)


# Mosaic raster
suburban_distance_mosaic <- do.call(mosaic, c(valid_suburban_rasters, fun = mean))

#ensure crs is bng
crs(suburban_distance_mosaic) <- bng

# Save raster
writeRaster(suburban_distance_mosaic, here(output_dir, "Urban_suburban", "nearest_suburban_raster_2015_all_tiles_corrected.tif"))
#print("Suburban raster mosaic complete")

```
# END ####
