---
title: "nfi_lcm_edges_2015_per_10k_modal_neighbours_loop_fixed"
author: "Amy Gresham"
date: "2024-02-06"
output: html_document
---

```{r}
library(raster)
library(fasterize)
library(sf)
library(dplyr)
library(here)
library(progress)

#Set project directory
project_dir <- here::here("iDeer_spatial_data")

# Set the output directory
output_dir <- here(project_dir, "outputs")

#1. Write into loop for 10k tiles
#2. Randomly assign mixed edge pixels to one category
```


```{r}
#Import required datasets
bng <- 27700

#England and Wales 10k squares
ew10k <- sf::st_read("C:/Users/ik929086/Documents/iDeer_Local/iDeer_spatial_data/intermediate_outputs/10k_tiles_EW.shp")

#import pre-made raster where lcm and NFi are overlaid
#1 = BL woodland, 2 = conif woodland, 22 = mixed mainly BL, 23 = mixed mainly conif
#3 = arable, 4 = improved grassland, etc... see CEH lcm documentation for full list.
wood.raster <- raster("C:/Users/ik929086/Documents/iDeer_Local/iDeer_spatial_data/outputs/nfi_lcm_2015_overlaid.tif")
crs(wood.raster) <- bng
```


```{r}
#Apply a nearest neighbour approach to classify woodland edge pixels according to the most common adjacent land cover type ####

#Do the first 50 tiles to check it's all working
#tiles <- ew10k %>% slice(51:n())

tiles <- ew10k

set.seed(123)

#Create binary woodland raster
#woodland <- nonwood_woodedges == 1000
#Get cell indices for cells which contain woodland edges so we can see how many woodland edge pixels there are
#woodland_indices <- which(woodland[] == 1)

# Function to get the modal category of neighbors
get_mode <- function(x) {
  tbl <- table(x)
  modes <- as.numeric(names(tbl[tbl == max(tbl)]))
  return(modes)
}

#make list to store 10k tiles

tile_list <- list()

# Set up a progress bar
pb <- progress_bar$new(total = nrow(tiles), format = "[:bar] :percent :elapsed")

for (j in 1:length(tiles$tile_name)) { 
  #for (j in 1:length(ew10k$tile_name)) { 
  tile <- tiles[j,]
  #tile <- ew10k[j,]
  tile.buff <- st_buffer(tile, 100) #buffer tile by 100m - gives 4 pixel buffer
  wood.raster.buff <- crop(wood.raster,tile.buff)
  
  #Get nonwood habitats in tile buffer
  nonwood <- wood.raster.buff
  #filter out woodlands
  nonwood[nonwood < 3 | nonwood > 21] <- NA
  #Reclass nonwood land cover categories into groups using CEH LCM groupings:
  reclass_matrix <- matrix(c(4,5,6,5,7,5,8,5, # Grasslands = 5
                           9,6,10,6,11,6,12,6, #Mountain, heath, bog = 6
                           13,7,14,8, #Saltwater = 7, Freshwater = 8
                           15,9,16,9,17,9,18,9,19,9), ncol = 2, byrow = TRUE) #Coastal = 9
nonwood_reclass <- reclassify(nonwood, reclass_matrix)

#Get wood boundaries in tile buffer
# make binary edge raster. 1 if edge, 0 if not ####
#Filter for woodland only, make everything else NA
wood <- wood.raster.buff
wood[wood[] > 2 & wood[] < 22] = NA
boundaries = boundaries(wood, type='inner') # edge raster
#Make woodland boundaries = 1000
boundaries_wood <- boundaries*1000
# need to make NAs 0, otherwise when we add them, it wont work!
boundaries_wood[is.na(boundaries_wood[])] <- 0 
nonwood_reclass[is.na(nonwood_reclass[])] <- 0
#Mosaic nonwood with wood boundaries, using max function. So wood boundaries will always win (value = 1000)
nonwood_woodedges <- mosaic(boundaries_wood, nonwood_reclass, fun = max)

if (sum(nonwood_woodedges[] == 1000, na.rm = TRUE) > 0) { #if there are woodland boundary pixels
  
  #Get pixel indices for whole tile.buff
tile_buff_indices <- cellFromXY(nonwood_woodedges, xyFromCell(nonwood_woodedges, 1:ncell(nonwood_woodedges)))

# Get the coordinates of cells in the buffer
buff_coords <- xyFromCell(nonwood_woodedges, tile_buff_indices)

# Identify indices of cells that fall within the tile's bounding box
tile_indices <- which(buff_coords[, 1] >= st_bbox(tile)$xmin &
                       buff_coords[, 1] <= st_bbox(tile)$xmax &
                       buff_coords[, 2] >= st_bbox(tile)$ymin &
                       buff_coords[, 2] <= st_bbox(tile)$ymax)

#Get pixel indices for pixels that == 1000 within tile.buff
woodland_indices <- which(nonwood_woodedges[] == 1000)

#subset woodland_indices for those within tile boundary
woodland_indices_tile <- woodland_indices[woodland_indices %in% tile_indices]

#LOOP TO GET NEIGHBOURING PIXELS ####

# Initialize a dataframe to store results
result_df <- data.frame(index = numeric(0), mode_neighbors = character(0), stringsAsFactors = FALSE)

for (i in woodland_indices_tile) {
  neighbors <- adjacent(nonwood_woodedges, cells = i, directions = 8, pairs = FALSE)
  neighbors <- neighbors[nonwood_woodedges[neighbors] != 1000 & nonwood_woodedges[neighbors] != 0]  # Exclude cells with value 1000 and 0
  neighbor_values <- nonwood_woodedges[neighbors]
  
  #Get modal neighbour
 if (length(neighbor_values) > 0) {
  mode_result <- get_mode(neighbor_values)
} else {
  mode_result <- NA  
}
  # Append to the dataframe
  result_df <- rbind(result_df, data.frame(index = i, mode_neighbors = paste(mode_result, collapse = ",")))
}

#Where there is more than one mode, randomly assign one of the values to be the representative land cover type
single_modes <- result_df %>%
  mutate(single_modes = ifelse(grepl(",", mode_neighbors), 
                                 sapply(strsplit(mode_neighbors, ","), function(x) sample(x, 1)),
                                 as.character(mode_neighbors)))

single_modes$single_modes<-as.numeric(single_modes$single_modes)

#Assign names to each category
neighbor_class <- single_modes %>%
  mutate(neighbor_class = #ifelse(grepl(",", mode_neighbors), "Mixed", #if there is >1 mode, classify as a mixed edge
            ifelse(single_modes == 20, "Urban",
            ifelse(single_modes == 21, "Suburban",
            ifelse(single_modes == 3, "Arable",
            ifelse(single_modes == 5, "Grassland",
            ifelse(single_modes == 6, "Mountain_heath_bog",
            ifelse(single_modes == 7, "Saltwater",
            ifelse(single_modes == 8, "Freshwater",
            ifelse(single_modes == 9, "Coastal", NA)))))))))

#Assign raster values to each category to be added to lcm
neighbor_class <- neighbor_class %>%
  mutate(neighbor_value = case_when(
    neighbor_class == "Arable" ~ 0.3,
    neighbor_class == "Grassland" ~ 0.5,
    neighbor_class == "Mountain_heath_bog" ~ 0.6,
    neighbor_class == "Saltwater" ~ 0.7,
    neighbor_class == "Freshwater" ~ 0.8,
    neighbor_class == "Coastal" ~ 0.9,
    neighbor_class == "Urban" ~ 0.202,
    neighbor_class == "Suburban" ~ 0.201,
    #neighbor_class == "Mixed" ~ 0.444,
    TRUE ~ NA_real_  # For any other cases
  ))

#Convert this table into a raster
#First make template using original raster
neighbour_raster <- raster(ext = extent(nonwood_woodedges), res = res(nonwood_woodedges), crs = bng)

#Get values to assign to pixels
values_to_assign <- neighbor_class$neighbor_value

#Get pixel indices so we know which pixels will receive each value
pixel_indices <- neighbor_class$index

#Assign values to raster based on pixel indices
neighbour_raster[pixel_indices] <- values_to_assign

#crop to tile extent
neighbour_raster <- crop(neighbour_raster, tile)

#Assign correct crs
crs(neighbour_raster) <- bng

#save to raster list

tile_list[[j]] <- neighbour_raster

 } else {
    tile_list[[j]] <- NA
   
  }

  pb$tick()  # Increment the progress bar after each iteration
}

#Close progress bar

pb$terminate()

#save raster tile list

saveRDS(tile_list, "C:/Users/ik929086/Documents/iDeer_Local/iDeer_spatial_data/outputs/R tile list backups/edge_tile_list.rds")

tile_list <- readRDS("C:/Users/ik929086/Documents/iDeer_Local/iDeer_spatial_data/outputs/R tile list backups/edge_tile_list_test.rds")
```

```{r}

#edges_1_50 <- readRDS("C:/Users/ik929086/Documents/iDeer_Local/iDeer_spatial_data/outputs/R tile list backups/edge_tile_list_1_50.rds")
#edges_51_1740 <- readRDS("C:/Users/ik929086/Documents/iDeer_Local/iDeer_spatial_data/outputs/R tile list backups/edge_tile_list_51_1740.rds")
#edges_all_tiles <- c(edges_1_50, edges_51_1740)

edges_all_tiles <- tile_list

#Mosaic the tiles together
# Label elements that are not RasterLayers or are empty
valid_edge_rasters <- lapply(edges_all_tiles, function(raster_layer) {
  if (inherits(raster_layer, "RasterLayer") && any(!is.na(values(raster_layer)))) {
    return(raster_layer)
  } else {
    return(NULL)
  }
})

# Remove NULL elements from the list
valid_edge_rasters <- Filter(function(x) !is.null(x), valid_edge_rasters)

# Mosaic raster
edge_raster_mosaic <- do.call(mosaic, c(valid_edge_rasters, fun = mean))

#export to inspect
writeRaster(edge_raster_mosaic, here(output_dir, "edge_raster_mosaic_all_tiles.tif"),overwrite=TRUE)


```


```{r}

#edge_raster_mosaic <- raster(here(output_dir, "edge_raster_mosaic_all_tiles.tif"))

#Add these values to original lcm ####
#First ensure original lcm is reclassified with new aggregate categories:
lcm <- wood.raster

#Crop lcm to ew10k
lcm_EW <- crop(lcm, edge_raster_mosaic)
lcm_EW_mask <- mask(lcm_EW, ew10k)

#Get rid of the edges that do not correspond to woodlands
#make a woodland binary raster
woods.only <- lcm_EW_mask
woods.only[woods.only > 2 & woods.only < 22] <- NA
woods.only[woods.only == 0] <- NA

edge_raster_mosaic_woodland_edges_only <- mask(edge_raster_mosaic, woods.only)
#This should get rid of edges that do not overlap with woodlands

#Add rasters together
# need to make NAs 0, otherwise when we add them, it wont work!
edge_raster_mosaic_woodland_edges_only[is.na(edge_raster_mosaic_woodland_edges_only[])] <- 0 
lcm_EW_mask[is.na(lcm_EW_mask[])] <- 0

#Adding these two rasters together should preserve the lcm values that do not overlap with neighbour_raster
edge_core_raster <- lcm_EW_mask + edge_raster_mosaic_woodland_edges_only
unique(edge_core_raster)

# [1]  0.000  1.000  1.201  1.202  1.300  1.500  1.600  1.700  1.800  1.900  2.000  2.201  2.202  2.300  2.500
#[16]  2.600  2.700  2.800  2.900  3.000  4.000  5.000  6.000  7.000  8.000  9.000 10.000 11.000 12.000 13.000
#[31] 14.000 15.000 16.000 17.000 18.000 19.000 20.000 21.000 22.000 22.201 22.202 22.300 22.500 22.600 22.700
#[46] 22.800 22.900 23.000 23.201 23.202 23.300 23.500 23.600 23.700 23.800 23.900

#The result shows the type of land cover, and any decimals show the woodland edge type
#To recap the reclassified land cover categories:
#1 = BL woodland, 2 = conifer woodland, 3 = arable, 5 = grassland, 6 = mountain/bog/heath, 7 = saltwater, 8 = freshwater,
#9 = coastal, 20 = urban, 21 = suburban, 22 = mixed mainly BL, 23 = mixed mainly conif.

#To recap the edge types:
#0.5 = Grassland, 0.6 = Mountain/heath/bog, 0.7 = saltwater, 0.8 = Freshwater, 0.9 = coastal, 0.202 = urban, 0.201 = suburban,
#0.444 = Mixed edge (multiple modes)

#Export final raster
#plot(edge_raster_mosaic_lcm_projection)
#writeRaster(edge_raster_mosaic_lcm_projection, here(output_dir, "edge_raster_mosaic_EW.tif"),overwrite=TRUE)
writeRaster(edge_core_raster, here(output_dir, "edge_core_raster_all_tiles_EW.tif"),overwrite=TRUE)

```
