---
title: "Relative_forage_quality_per_lc"
author: "Amy Gresham"
date: "2024-02-13"
output: html_document
---

```{r}
#Create relative forage quality score ####
#Need relative quality compared to surrounding landscape
#Do this for the three buffer sizes (250, 500, 1000)

library(here)
library(dplyr)
library(sf)

project_dir <- here()
input_dir <- here("Nutritional_Landscape_Index","inputs")
output_dir <- here("Nutritional_Landscape_Index","outputs")

```
#Do not rank the lc and edge types, just give them an appropriate quality category between -10 to +10

```{r}

#Approach 1: Make all woodland edges 10 unless they are in urban and suburban areas

#Read in original expert mean forage Q scores

expert_scores <- read.csv(file.path(input_dir,"Expert_Q_forage_qual_summary_stats.csv"))

#Get means and land.cover types

land.cover <- expert_scores[, c(2, 4)]
#Rename col 2
land.cover <- land.cover %>%
  rename(Forage_Q = Median)

#Experts scored BL woodland as 8 and Conifer woodland as 4

#Assign woodland quality accordingly:

#BL forage quality = 8.0
#Mixed mainly BL = 6.0
#Mixed mainly conifer = 5.0
#Conifer woodland = 4.0

new_row <- data.frame(
  Land.cover = "Mixed_BL",
  Forage_Q = 6.0
)
  
land.cover <- rbind(land.cover, new_row)

new_row <- data.frame(
  Land.cover = "Mixed_conif",
  Forage_Q = 5.0
)

land.cover <- rbind(land.cover, new_row)

#Make sure Heather & heather grassland are represented separately, as they are separate categories in the map
#Give them the same forage Q score (heathland)

new_row <- data.frame(
  Land.cover = "Heather",
  Forage_Q = land.cover$Forage_Q[land.cover$Land.cover %in% c("Heathland")]
)
land.cover <- rbind(land.cover, new_row)

new_row <- data.frame(
  Land.cover = "Heather grassland",
  Forage_Q = land.cover$Forage_Q[land.cover$Land.cover %in% c("Heathland")]
)
land.cover <- rbind(land.cover, new_row)

land.cover.clean <- land.cover
```


```{r}
#Make new rows for woodland edge types #### 

#Approach 1: give them all a Forage_Q score of 10 ####
#This implies that edge type doesn't matter - non-forage settling stimulus is more important

land.cover <- land.cover.clean

#BL arable
new_row <- data.frame(
  Land.cover = "BL_Arable_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#BL grassland
new_row <- data.frame(
  Land.cover = "BL_Grassland_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#BL Heath/bog - using the heathland and bog forage scores but also includes inland rock on the map
new_row <- data.frame(
  Land.cover = "BL_mountain_heath_bog_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#BL coastal - using saltmarsh quality score but also includes sediment on the map
new_row <- data.frame(
  Land.cover = "BL_coastal_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#BL urban
new_row <- data.frame(
  Land.cover = "BL_urban_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#BL suburban
new_row <- data.frame(
  Land.cover = "BL_suburban_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#Mixed_BL arable
new_row <- data.frame(
  Land.cover = "Mixed_BL_Arable_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#Mixed_BL grassland
new_row <- data.frame(
  Land.cover = "Mixed_BL_Grassland_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#Mixed_BL Heath/bog - using the heathland and bog forage scores but also includes inland rock on the map
new_row <- data.frame(
  Land.cover = "Mixed_BL_mountain_heath_bog_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#Mixed_BL coastal - using saltmarsh quality score but also includes sediment on the map
new_row <- data.frame(
  Land.cover = "Mixed_BL_coastal_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#Mixed_BL urban
new_row <- data.frame(
  Land.cover = "Mixed_BL_urban_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#Mixed_BL suburban
new_row <- data.frame(
  Land.cover = "Mixed_BL_suburban_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#Mixed_conif arable edge
new_row <- data.frame(
  Land.cover = "Mixed_conif_Arable_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#Mixed_conif grassland
new_row <- data.frame(
  Land.cover = "Mixed_conif_Grassland_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#Mixed_conif Heath/bog - using the heathland and bog forage scores but also includes inland rock on the map
new_row <- data.frame(
  Land.cover = "Mixed_conif_mountain_heath_bog_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#Mixed_conif coastal - using saltmarsh quality score but also includes sediment on the map
new_row <- data.frame(
  Land.cover = "Mixed_conif_coastal_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#Mixed_conif urban
new_row <- data.frame(
  Land.cover = "Mixed_conif_urban_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#Mixed_conif suburban
new_row <- data.frame(
  Land.cover = "Mixed_conif_suburban_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

new_row <- data.frame(
  Land.cover = "Conif_Arable_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#Conif grassland
new_row <- data.frame(
  Land.cover = "Conif_Grassland_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#Conif Heath/bog - using the heathland and bog forage scores but also includes inland rock on the map
new_row <- data.frame(
  Land.cover = "Conif_mountain_heath_bog_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#Conif coastal - using saltmarsh quality score but also includes sediment on the map
new_row <- data.frame(
  Land.cover = "Conif_coastal_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#Conif urban
new_row <- data.frame(
  Land.cover = "Conif_urban_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#Conif suburban
new_row <- data.frame(
  Land.cover = "Conif_suburban_edge",
  Forage_Q = 10
)
land.cover <- rbind(land.cover, new_row)

#Add raster values to table ####

#These values come from the mosaicked edge/core raster, which is an amalgamation of the NFI woodland map and CEH lcm
#See nfi_lcm_edges_2015_per_10k_modal_neighbours_loop_fixed.Rmd for process on classifying pixel values

#1 = BL woodland, 2 = conifer woodland, 3 = arable, 4 = imrpoved grassland 5 = neutral grassland, 6 = calcareous grassland, 7 = acid grassland, 8 = Fen, marsh,swamp, 9 = heather, 10 = heather grassland, 11 = bog, 12 = inland rock, 13 = saltwater, 14 = freshwater, 15 = supra-littoral rock, 16 = supralittoral sediment, 17 = littoral rock, 18 = littoral sediment, 19 = saltmarsh, 20 = urban, 21 = suburban, 22 = mixed mainly BL, 23 = mixed mainly conif.

#To recap the edge types:
#0.3 = Arable, 0.5 = Grassland, 0.6 = Mountain/heath/bog, 0.7 = saltwater, 0.8 = Freshwater, 0.9 = coastal, 0.202 = urban, 0.201 = suburban


land.cover.values <- land.cover %>%
  mutate(class = case_when(
            Land.cover == "Broadleaved woodland"~ 1,
            Land.cover == "Coniferous woodland" ~ 2,
            Land.cover == "Arable land"~ 3,
            Land.cover == "Improved grassland"~ 4,
            Land.cover == "Neutral grassland"~ 5,
            Land.cover =="Calcareous grassland"~ 6,
            Land.cover =="Acid grassland"~ 7,
            Land.cover =="Fenland"~ 8,
            Land.cover =="Heather"~ 9,
            Land.cover =="Heather grassland"~ 10,
            Land.cover =="Peatland bog"~ 11,
            Land.cover =="Inland rock"~ 12,
            Land.cover =="Saltwater"~ 13,
            Land.cover =="Freshwater"~ 14,
            Land.cover =="Supra-littoral Rock"~ 15,
            Land.cover=="Supra-littoral Sediment"~16,
            Land.cover=="Littoral rock"~17,
            Land.cover=="Littoral sediment"~18,
            Land.cover=="Saltmarsh"~19,
            Land.cover=="Urban areas"~20,
            Land.cover=="Suburban areas"~21,
            Land.cover=="Mixed_BL"~22,
            Land.cover=="Mixed_conif"~23,
            Land.cover=="BL_Grassland_edge"~1.500, #BL edges
            Land.cover=="BL_Arable_edge"~1.300,
            Land.cover=="BL_coastal_edge"~1.900,
            Land.cover=="BL_mountain_heath_bog_edge"~1.600,
            Land.cover=="BL_suburban_edge"~1.201,
            Land.cover=="BL_urban_edge"~1.202,
            Land.cover=="Conif_Grassland_edge"~2.500, #Conif edges
            Land.cover=="Conif_Arable_edge"~2.300,
            Land.cover=="Conif_coastal_edge"~2.900,
            Land.cover=="Conif_mountain_heath_bog_edge"~2.600,
            Land.cover=="Conif_suburban_edge"~2.201,
            Land.cover=="Conif_urban_edge"~2.202,
            Land.cover=="Mixed_BL_Grassland_edge"~22.500, #Mixed BL edges
            Land.cover=="Mixed_BL_Arable_edge"~22.300,
            Land.cover=="Mixed_BL_coastal_edge"~22.900,
            Land.cover=="Mixed_BL_mountain_heath_bog_edge"~22.6,
            Land.cover=="Mixed_BL_suburban_edge"~22.201,
            Land.cover=="Mixed_BL_urban_edge"~22.202,
            Land.cover=="Mixed_conif_Grassland_edge"~23.500, #Mixed Conif edges
            Land.cover=="Mixed_conif_Arable_edge"~23.300,
            Land.cover=="Mixed_conif_coastal_edge"~23.900,
            Land.cover=="Mixed_conif_mountain_heath_bog_edge"~23.6,
            Land.cover=="Mixed_conif_suburban_edge"~23.201,
            Land.cover=="Mixed_conif_urban_edge"~23.202,
            TRUE ~ NA_real_  # For any other cases
  ))

#Remove heathland - accounted for by heather and heather grassland:
land.cover.values <- land.cover.values %>% filter(!Land.cover %in% c("Heathland"))

#save
write.csv(land.cover.values, file.path(output_dir, "Expert_derived_quality_ranks_edges_scored_10.csv"))
```


```{r}
#Approach 2: score them according to the edge type ####
#This implies that edge type is important - forest type and adjacent land use play a factor

land.cover <- land.cover.clean

#Get median of medians of all grassland types 

new_row <- data.frame(
  Land.cover = "Grassland",
  Forage_Q = median(land.cover$Forage_Q[land.cover$Land.cover %in% c("Calcareous_grassland", "Acid_grassland", "Neutral_grassland","Improved grassland","Fenland")])
)
land.cover <- rbind(land.cover, new_row)

#Get median of medians of Peatland big and Heathland

new_row <- data.frame(
  Land.cover = "Bog/Heathland",
  Forage_Q = median(land.cover$Forage_Q[land.cover$Land.cover %in% c("Peatland bog","Heathland")])
)
land.cover <- rbind(land.cover, new_row)

#----------------------

#BL arable
new_row <- data.frame(
  Land.cover = "BL_Arable_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Broadleaved woodland", "Arable land")])
)
land.cover <- rbind(land.cover, new_row)

#BL grassland
new_row <- data.frame(
  Land.cover = "BL_Grassland_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Broadleaved woodland","Grassland")])
)
land.cover <- rbind(land.cover, new_row)

#BL Heath/bog - using the heathland and bog forage scores but also includes inland rock on the map
new_row <- data.frame(
  Land.cover = "BL_mountain_heath_bog_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Broadleaved woodland", "Bog/Heathland")])
)
land.cover <- rbind(land.cover, new_row)

#BL coastal - using saltmarsh quality score but also includes sediment on the map
new_row <- data.frame(
  Land.cover = "BL_coastal_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Broadleaved woodland", "Saltmarsh")])
)
land.cover <- rbind(land.cover, new_row)

#BL urban
new_row <- data.frame(
  Land.cover = "BL_urban_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Broadleaved woodland", "Urban areas")])
)
land.cover <- rbind(land.cover, new_row)

#BL suburban
new_row <- data.frame(
  Land.cover = "BL_suburban_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Broadleaved woodland", "Suburban areas")])
)
land.cover <- rbind(land.cover, new_row)

#Mixed_BL arable
new_row <- data.frame(
  Land.cover = "Mixed_BL_Arable_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Mixed_BL", "Arable land")])
)
land.cover <- rbind(land.cover, new_row)

#Mixed_BL grassland
new_row <- data.frame(
  Land.cover = "Mixed_BL_Grassland_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Mixed_BL","Grassland")])
)
land.cover <- rbind(land.cover, new_row)

#Mixed_BL Heath/bog - using the heathland and bog forage scores but also includes inland rock on the map
new_row <- data.frame(
  Land.cover = "Mixed_BL_mountain_heath_bog_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Mixed_BL", "Bog/Heathland")])
)
land.cover <- rbind(land.cover, new_row)

#Mixed_BL coastal - using saltmarsh quality score but also includes sediment on the map
new_row <- data.frame(
  Land.cover = "Mixed_BL_coastal_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Mixed_BL", "Saltmarsh")])
)
land.cover <- rbind(land.cover, new_row)

#Mixed_BL urban
new_row <- data.frame(
  Land.cover = "Mixed_BL_urban_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Mixed_BL", "Urban areas")])
)
land.cover <- rbind(land.cover, new_row)

#Mixed_BL suburban
new_row <- data.frame(
  Land.cover = "Mixed_BL_suburban_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Mixed_BL", "Suburban areas")])
)
land.cover <- rbind(land.cover, new_row)

#Mixed_conif arable edge
new_row <- data.frame(
  Land.cover = "Mixed_conif_Arable_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Mixed_conif", "Arable land")])
)
land.cover <- rbind(land.cover, new_row)

#Mixed_conif grassland
new_row <- data.frame(
  Land.cover = "Mixed_conif_Grassland_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Mixed_conif","Grassland")])
)
land.cover <- rbind(land.cover, new_row)

#Mixed_conif Heath/bog - using the heathland and bog forage scores but also includes inland rock on the map
new_row <- data.frame(
  Land.cover = "Mixed_conif_mountain_heath_bog_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Mixed_conif", "Bog/Heathland")])
)
land.cover <- rbind(land.cover, new_row)

#Mixed_conif coastal - using saltmarsh quality score but also includes sediment on the map
new_row <- data.frame(
  Land.cover = "Mixed_conif_coastal_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Mixed_conif", "Saltmarsh")])
)
land.cover <- rbind(land.cover, new_row)

#Mixed_conif urban
new_row <- data.frame(
  Land.cover = "Mixed_conif_urban_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Mixed_conif", "Urban areas")])
)
land.cover <- rbind(land.cover, new_row)

#Mixed_conif suburban
new_row <- data.frame(
  Land.cover = "Mixed_conif_suburban_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Mixed_conif", "Suburban areas")])
)
land.cover <- rbind(land.cover, new_row)

#Conif arable edge
new_row <- data.frame(
  Land.cover = "Conif_Arable_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Coniferous woodland", "Arable land")])
)
land.cover <- rbind(land.cover, new_row)

#Conif grassland
new_row <- data.frame(
  Land.cover = "Conif_Grassland_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Coniferous woodland","Grassland")])
)
land.cover <- rbind(land.cover, new_row)

#Conif Heath/bog - using the heathland and bog forage scores but also includes inland rock on the map
new_row <- data.frame(
  Land.cover = "Conif_mountain_heath_bog_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Coniferous woodland", "Bog/Heathland")])
)
land.cover <- rbind(land.cover, new_row)

#Conif coastal - using saltmarsh quality score but also includes sediment on the map
new_row <- data.frame(
  Land.cover = "Conif_coastal_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Coniferous woodland", "Saltmarsh")])
)
land.cover <- rbind(land.cover, new_row)

#Conif urban
new_row <- data.frame(
  Land.cover = "Conif_urban_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Coniferous woodland", "Urban areas")])
)
land.cover <- rbind(land.cover, new_row)

#Conif suburban
new_row <- data.frame(
  Land.cover = "Conif_suburban_edge",
  Forage_Q = sum(land.cover$Forage_Q[land.cover$Land.cover %in% c("Coniferous woodland", "Suburban areas")])
)
land.cover <- rbind(land.cover, new_row)

#Scale Forage_Q between -10 and +10

#land.cover$scaled_forage_q <- scales::rescale(land.cover$scaled_forage_q, to =c(-10,10))

#Add raster values to table ####

#These values come from the mosaicked edge/core raster, which is an amalgamation of the NFI woodland map and CEH lcm
#See nfi_lcm_edges_2015_per_10k_modal_neighbours_loop_fixed.Rmd for process on classifying pixel values

#1 = BL woodland, 2 = conifer woodland, 3 = arable, 4 = imrpoved grassland 5 = neutral grassland, 6 = calcareous grassland, 7 = acid grassland, 8 = Fen, marsh,swamp, 9 = heather, 10 = heather grassland, 11 = bog, 12 = inland rock, 13 = saltwater, 14 = freshwater, 15 = supra-littoral rock, 16 = supralittoral sediment, 17 = littoral rock, 18 = littoral sediment, 19 = saltmarsh, 20 = urban, 21 = suburban, 22 = mixed mainly BL, 23 = mixed mainly conif.

#To recap the edge types:
#0.3 = Arable, 0.5 = Grassland, 0.6 = Mountain/heath/bog, 0.7 = saltwater, 0.8 = Freshwater, 0.9 = coastal, 0.202 = urban, 0.201 = suburban


land.cover.values <- land.cover %>%
  mutate(class = case_when(
            Land.cover == "Broadleaved woodland"~ 1,
            Land.cover == "Coniferous woodland" ~ 2,
            Land.cover == "Arable land"~ 3,
            Land.cover == "Improved grassland"~ 4,
            Land.cover == "Neutral grassland"~ 5,
            Land.cover =="Calcareous grassland"~ 6,
            Land.cover =="Acid grassland"~ 7,
            Land.cover =="Fenland"~ 8,
            Land.cover =="Heather"~ 9,
            Land.cover =="Heather grassland"~ 10,
            Land.cover =="Peatland bog"~ 11,
            Land.cover =="Inland rock"~ 12,
            Land.cover =="Saltwater"~ 13,
            Land.cover =="Freshwater"~ 14,
            Land.cover =="Supra-littoral Rock"~ 15,
            Land.cover=="Supra-littoral Sediment"~16,
            Land.cover=="Littoral rock"~17,
            Land.cover=="Littoral sediment"~18,
            Land.cover=="Saltmarsh"~19,
            Land.cover=="Urban areas"~20,
            Land.cover=="Suburban areas"~21,
            Land.cover=="Mixed_BL"~22,
            Land.cover=="Mixed_conif"~23,
            Land.cover=="BL_Grassland_edge"~1.500, #BL edges
            Land.cover=="BL_Arable_edge"~1.300,
            Land.cover=="BL_coastal_edge"~1.900,
            Land.cover=="BL_mountain_heath_bog_edge"~1.600,
            Land.cover=="BL_suburban_edge"~1.201,
            Land.cover=="BL_urban_edge"~1.202,
            Land.cover=="Conif_Grassland_edge"~2.500, #Conif edges
            Land.cover=="Conif_Arable_edge"~2.300,
            Land.cover=="Conif_coastal_edge"~2.900,
            Land.cover=="Conif_mountain_heath_bog_edge"~2.600,
            Land.cover=="Conif_suburban_edge"~2.201,
            Land.cover=="Conif_urban_edge"~2.202,
            Land.cover=="Mixed_BL_Grassland_edge"~22.500, #Mixed BL edges
            Land.cover=="Mixed_BL_Arable_edge"~22.300,
            Land.cover=="Mixed_BL_coastal_edge"~22.900,
            Land.cover=="Mixed_BL_mountain_heath_bog_edge"~22.6,
            Land.cover=="Mixed_BL_suburban_edge"~22.201,
            Land.cover=="Mixed_BL_urban_edge"~22.202,
            Land.cover=="Mixed_conif_Grassland_edge"~23.500, #Mixed Conif edges
            Land.cover=="Mixed_conif_Arable_edge"~23.300,
            Land.cover=="Mixed_conif_coastal_edge"~23.900,
            Land.cover=="Mixed_conif_mountain_heath_bog_edge"~23.6,
            Land.cover=="Mixed_conif_suburban_edge"~23.201,
            Land.cover=="Mixed_conif_urban_edge"~23.202,
            TRUE ~ NA_real_  # For any other cases
  ))

#Remove heathland - accounted for by heather and heather grassland:
land.cover.values <- land.cover.values %>% filter(!Land.cover %in% c("Heathland"))

#save
write.csv(land.cover.values, file.path(output_dir, "Expert_derived_quality_ranks_edge_types.csv"))

```

