Getting percentage cover of woodland edges within 400m

Including interior woodland edges for open/closed woodland types, and exterior edges

```{r}
library(sf)
library(tidyverse)
library(raster)
```

```{r}
#Read in NFI 2023 dataset

nfi <- st_read("C:/Users/ik929086/Documents/iDeer/data/raw-data/nfi-2023-raw/National_Forest_Inventory_GB_2023.shp")

unique(nfi$IFT_IOA)

#England and Wales 10k squares
ew10k <- sf::st_read("C:/Users/ik929086/Documents/iDeer/data/derived-data/10k_tiles_EW.shp")
bng <- st_crs(ew10k)

#Get Chilterns tile as an example
SU79 <- ew10k %>% filter(tile_name %in% c("SU79"))

```

```{r}
#Explore dataset

woods_only <- nfi %>% filter(CATEGORY %in% c("Woodland"))
unique(woods_only$IFT_IOA)

non_woods <- nfi %>% filter(CATEGORY %in% c("Non woodland"))
unique(non_woods$IFT_IOA)
#Grassland, Agricultural land, Other vegetation and bare area would be areas for foraging
#Other things not usable habitat

#Mixed structure habitats = open areas, or areas with good potential for foraging resources
mixed_structure_habitats <- nfi %>% filter(IFT_IOA %in% c("Bare area","Assumed woodland","Failed","Coppice","Coppice with standards","Windblow","Grassland","Ground prep","Agriculture land","Other vegetation","Felled","Low density", "Young trees","Shrub"))

#Closed habitats = mature woodland
closed_habitats <- nfi %>% filter(IFT_IOA %in% c("Conifer","Broadleaved","Mixed mainly broadleaved","Mixed mainly conifer"))

#subset for testing

closed_habitats <- st_filter(closed_habitats, SU79)
mixed_structure_habitats <- st_filter(mixed_structure_habitats, SU79)

plot(closed_habitats$geometry, col = "red")
plot(mixed_structure_habitats$geometry, col = "blue",add=TRUE)
```

```{r}
#Make an NFI raster of the two habitat types

# Create the IFT_ID column based on the IFT_IOA values
#1 = open land cover types
#2 = mature woodland types
nfi <- nfi %>%
  mutate(IFT_ID = case_when(
    IFT_IOA %in% c("Bare area", "Assumed woodland", "Failed", "Coppice", 
                   "Coppice with standards", "Windblow", "Grassland", 
                   "Ground prep", "Agriculture land", "Other vegetation", 
                   "Windfarm", "Felled", "Low density", "Young trees") ~ 1,
    IFT_IOA %in% c("Conifer", "Broadleaved", "Mixed mainly broadleaved", 
                   "Mixed mainly conifer") ~ 2,
    TRUE ~ NA_real_  # This handles other values (if needed, or you can leave it out)
  ))

#Make raster of NFI
template_rast <- raster("C:/Users/ik929086/Documents/iDeer/data/raw-data/lcm-2023/gblcm2023_25m.tif")

nfi_rast <- fasterize::fasterize(nfi, template_rast, field = "IFT_ID")

plot(nfi_rast)

#Get boundaries between 1 and 2

boundaries_nfi <- boundaries(nfi_rast, type = "inner", classes = TRUE, #make edges between classes as well as NA
                             directions = 8, #search for edges in 8 directions
                             asNA = TRUE) #non-edges returned as NA

plot(boundaries_nfi)

boundaries_nfi_sample <- raster::crop(boundaries_nfi, SU79)

# Plot the other geometries
plot(closed_habitats$geometry, col = "forestgreen")
plot(mixed_structure_habitats$geometry, col = "magenta", add = TRUE)

#plot boundaries - internal boundaries and edge boundaries
plot(boundaries_nfi_sample)

```
