iDeer WrEN sites validation
```{r}
library(raster)
library(sf)
library(tidyverse)
library(terra)
library(exactextractr)
```

```{r}
#Read in deer activity dataset

deer <- read.csv()
```


```{r}
#Read in deer impact risk raster layers

small_rast <- raster("C:/Users/aalg1m25/OneDrive - University of Southampton/R_data_transfer/Deer impact EW risk maps/output/NFI_2023_small_deer_impact_risk_EW.tif")

large_rast <- raster("C:/Users/aalg1m25/OneDrive - University of Southampton/R_data_transfer/Deer impact EW risk maps/output/NFI_2023_large_deer_impact_risk_EW_V2.tif")

# Set zeros to NA for small_rast
small_rast_int <- small_rast
small_rast_int[small_rast_int == 0] <- NA

writeRaster("C:/Users/aalg1m25/OneDrive - University of Southampton/Documents/Github/iDeer/output/NFI_2023_small_deer_impact_risk_EW_no_zeros.tif")

# Convert to integer for large_rast
large_rast_int <- large_rast
large_rast_int <- calc(large_rast_int, fun = function(x) as.integer(x))

writeRaster("C:/Users/aalg1m25/OneDrive - University of Southampton/Documents/Github/iDeer/output/NFI_2023_large_deer_impact_risk_EW_V2_Int.tif")
```

```{r}
#Read in updated rasters
small_rast_int <- raster("C:/Users/aalg1m25/OneDrive - University of Southampton/Documents/Github/iDeer/output/NFI_2023_small_deer_impact_risk_EW_no_zeros.tif")
small_rast_int
large_rast_int <- raster("C:/Users/aalg1m25/OneDrive - University of Southampton/Documents/Github/iDeer/output/NFI_2023_large_deer_impact_risk_EW_V2_Int.tif")
large_rast_int
```

```{r}
#Read in polygon datasets

small_deer_risk_sf <- st_read("C:/Users/aalg1m25/OneDrive - University of Southampton/iDeer_Manuscripts/iDeer_Tool/Supplementary Info/Risk maps/Vector version/NFI_LCM_2023_small_deer_impact_risk_EW_extraction_V3.gpkg")
large_deer_risk_sf <- st_read("C:/Users/aalg1m25/OneDrive - University of Southampton/iDeer_Manuscripts/iDeer_Tool/Supplementary Info/Risk maps/Vector version/NFI_LCM_2023_large_deer_impact_risk_EW_extraction_V3.gpkg")
```

```{r}
#Read in WrEN site shapefile
wren_sites <- st_read("C:/Users/aalg1m25/OneDrive - University of Southampton/WrEN sites/WrEN_2014sites_25Nov2014.shp")
head(wren_sites)
```

```{r}
#Extract raster values within wren sites

#Small deer --------------#

# Convert raster and vector objects to terra formats
r_small <- rast(small_rast_int)        # RasterLayer to SpatRaster
wren_vect <- vect(wren_sites)          # sf to SpatVector

# Extract values with cell IDs and coordinates
vals_small_terra <- terra::extract(
  r_small,
  wren_vect,
  cells = TRUE,
  xy = TRUE
)

# Join SITE_NO from wren_sites to extraction results
# terra::extract returns an ID column corresponding to the row number in wren_vect
vals_small_terra$SITE_NO <- wren_vect$SITE_NO[vals_small_terra$ID]

# Optional: tidy up column names
vals_small_terra <- vals_small_terra %>%
  select(SITE_NO, cell, x, y, cell_ID = cell, small_deer_risk_score = names(r_small))


#LARGE DEER -------#

# Convert raster and vector objects to terra formats
r_large <- rast(large_rast_int)        # RasterLayer to SpatRaster
wren_vect <- vect(wren_sites)          # sf to SpatVector

# Extract values with cell IDs and coordinates
vals_large_terra <- terra::extract(
  r_large,
  wren_vect,
  cells = TRUE,
  xy = TRUE
)

# Join SITE_NO from wren_sites to extraction results
# terra::extract returns an ID column corresponding to the row number in wren_vect
vals_large_terra$SITE_NO <- wren_vect$SITE_NO[vals_large_terra$ID]

# Optional: tidy up column names
vals_large_terra <- vals_large_terra %>%
  select(SITE_NO, cell, x, y, cell_ID = cell, large_deer_risk_score = names(r_large))

#write datasets
write_rds(vals_small_terra, "C:/Users/aalg1m25/OneDrive - University of Southampton/Documents/Github/iDeer/output/wren_sites_small_deer_risk_raster_pixel_extract.rds")

write_rds(vals_large_terra, "C:/Users/aalg1m25/OneDrive - University of Southampton/Documents/Github/iDeer/output/wren_sites_large_deer_risk_raster_pixel_extract.rds")
```

```{r}
#Extract polygons within wren sites

wren_sites <- st_transform(wren_sites, st_crs(small_deer_risk_sf))

#SMALL DEER -----------#
small_deer_wren <- st_intersection(wren_sites, small_deer_risk_sf)
small_deer_wren <- small_deer_wren %>%
  select(-c(large_risk_mode, small_risk_mode, Wood_Area_m2, tile_ID)) %>% 
  rename(mean_small_deer_impact_risk = mean_risk)

#LARGE DEER -----------#
  
large_deer_wren <- st_intersection(wren_sites, large_deer_risk_sf)
large_deer_wren <- large_deer_wren %>%
  select(-c(large_risk_mode, small_risk_mode, Wood_Area_m2, tile_ID)) %>% 
  rename(mean_large_deer_impact_risk = mean_risk)

#left_join the datasets

# Join small and large deer data by SITE_NO
deer_risk_combined <- left_join(
  small_deer_wren,
  large_deer_wren %>% st_drop_geometry(),  # drop geometry from right dataset to avoid conflict
  by = c("REGION","KW_COMMENT","OBJECTID","EASTING","NORTHING","SITE_NAME", "PLANT_DATE","SITE_NO","GRID_REF","patch_ID")
)

st_write(deer_risk_combined, "C:/Users/aalg1m25/OneDrive - University of Southampton/Documents/Github/iDeer/output/wren_sites_mean_deer_impact_risk.gpkg")

```



